### ISSUE TITLE
thumbnailFeaturedKeyword?

### ISSUE THREAD

**Issue by macsupport** [nanostudio-org/nanogallery2#10]
I am wondering if this is an active option setting and how one utilizes it. Not seeing any documentation or a way to enable it for individual images. Thanks for any info!

**Comment by Kris-B** [comment]
the option will search for a keyword in title/description.
if the keyword is found, the featured icon will be displayed over the thumbnail

**Comment by macsupport** [comment]
Is the keyword written with an @, i.e. @featured, like other keywords?

**Comment by Kris-B** [comment]
`@` is not required as the whole defined string will be searched. So `@kw` is not the same as `kw`.
The `@` is only required for `galleryFilterTags` to retrieve the tags.
