### ISSUE TITLE
Thumbnails not sizing as expected

### ISSUE THREAD

**Issue by PhilippeGauthier** [nanostudio-org/nanogallery2#101]
I'm guessing this is something on my end but my thumbnails aren't being rendered. The inline styles on `<div class="nGY2GThumbnail">` divs are all `style="display: block; top: 0px; left: 0px; width: 4px; height: 4px;"` with the `top` style being offset 6px with each subsequent thumbnail. I'm guessing that 4px of size is from the `nGY2GThumbnailLabel` css style which applies 4px of padding. I've confirmed that the paths to both the `src` and `srct` are valid and load if inspecting the element. Additionally clicking on the tiny thumbnails launches the lightbox as expected and everything else seems to be working.

Here's the initialization code. I'm using a CMS to generate the image paths but I've hardcoded images as well and get the same result .

```
$(document).ready(function() {
    $("#splinter-gallery").nanogallery2({
        items:[
        {{ assets:images }}
        { src: '{{ url }}', srct: '{{ glide:id w="300" }}', title: '{{ title }}' }{{ if !last }},{{ /if }}
        {{ /assets:images }}
        ],
        thumbnailWidth:  200,
        thumbnailHeight: 200,
        itemsBaseURL:    '{{ homepage }}',
        locationHash:    false,

    });
});
```

Thanks for your help and great gallery.

**Comment by Kris-B** [comment]
can you provide a sample of the items generated by the CMS?

**Comment by Kris-B** [comment]
everything looks good... possible to have an access to the page?

**Comment by PhilippeGauthier** [comment]
Sure. Here's a page using the CMS. https://staging.splintercreekms.com/gallery

**Comment by PhilippeGauthier** [comment]
I ended up using a different gallery as I couldn't figure it out. I used https://sachinchoolur.github.io/lightgallery.js/

**Comment by rastographics** [comment]
I'm also having this exact same issue as you describe. The jquery.nanogallery2.min.js file is loaded as well as nanogallery2.min.css.
Lightbox works find (icons not visible though).

Photo thumbnails are a bunch of 4px boxes though

![image](https://user-images.githubusercontent.com/3922354/135643504-4e240f4a-6b82-45a6-80de-ca44c57caa23.png)

**Comment by rastographics** [comment]
Figured this out...there was a parent container with `display:flex` applied to it. That style rule was the cause of these problems.
