### ISSUE TITLE
Album cover does not load from google photos

### ISSUE THREAD

**Issue by csicsoworks** [nanostudio-org/nanogallery2#103]
Hello, 

I tried to change the album cover in Google photos, but nano wont display it as a cover, it displays only the 1st picture as album cover.

Other: I am sure there is a way to display the album name only on the album cover, but not to display the pictures filenames on the picture, can you share that?

Thank you.

I just love your script ;)
csicso

**Comment by Kris-B** [comment]
Hey,
nanogallery displays the cover returned by the google api. I didn't test it lately, but there may be some delay after you made the change in google photos.

For pictures filenames, check: https://nanogallery2.nanostudio.org/documentation.html#ngy2_navigation_first

**Comment by csicsoworks** [comment]
Hi,

Thanks for the reply. 
Unfortunately it is not a delay. In Google Photos the albums have the previously set up covers, although on my page it is only the first picture :(

**Comment by csicsoworks** [comment]
Ok, Solved it.

So the solution was that I had to disable sharing of the albums, and than all the changes - like update of the album cover - were applied immediately. Might be a Google Photos API bug.
Thanks Kris-B to nudge me to the right direction :)

**Comment by Kris-B** [comment]
good to know, thanks for the update !
