### ISSUE TITLE
Sorting, Password protection and nicer URLs

### ISSUE THREAD

**Issue by blubbsy** [nanostudio-org/nanogallery2#105]
Hi,

three quick questions (using nano provider 2) i couldnt find answers in the user guide: 
1) I have in the First level simply several albums, but in each album there could be sub-albums mixed with single pictures. Is it possible to set the sorting to put the sub-albums to the first places? Or is the recommandable way to simply adapt the file and folder names to the sorting?

2) Is it possible to password protect single albums? I havent tried what happens if i set permisisons in the nano_provider_content folder to ask for a password, but i think it wouldnt work anyway (as it not accessed by the browser itself, but by the webserver service) :/ 

3) Is there a way to make nicer URLs?"...#nanogallery/nanogallery2/2018 India%2FTaj Mahal" is not exactly the nicest accesible url ;)

Thanks!
Blubbsy

**Comment by Kris-B** [comment]
You can request some enhancement for sorting directly on the nano_photos_provider2 issue page: https://github.com/nanostudio-org/nano_photos_provider2/issues

2 and 3 are note possible
