### ISSUE TITLE
Only text no images

### ISSUE THREAD

**Issue by Evert2311** [nanostudio-org/nanogallery2#106]
What am I doing wrong.
I installed nano_photos_provider2 on my webserver
www.name of my mywebserver/nano_photos_provider2
Installed on this location:
nano_photos_provider2.php
nano_photos_provider2.json.class.php
nano_photos_provider2.cfg
nano_photos_provider2.encoding.php
createted a folder named nano_photos_content

I placed in the head of the index.html file of my website

`` <!-- nanoGallery --> ``
 ``           <!-- jQuery --> ``
  ``              <script  type="text/javascript"  ``
``  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> ``
``            <!-- nanogallery2 --> ``
 ``               <link href="https://www.mywebsite/nano_photos_provider2/src/css/nanogallery2.css"  ``
``  rel="stylesheet" type="text/css"> ``
 ``               <script  ``
``type="text/javascript">src="https://www.mywebsite/nano_photos_provider2/dist/jquery.nanogallery2.min.js"></script> ``
       

`` I placed in the body of the index.html file of my website  ``
`` <div id="nanogallery2" data-nanogallery2='{ ``
 ``     "kind":             "nano_photos_provider2",  ``
``      "dataProvider":     "https://www.mywebsite/nano_photos_provider2/nano_photos_provider2.php", ``
``      "thumbnailHeight":  150,  ``
  ``    "thumbnailWidth":   "auto"  ``
 ` `    }'>  ``
 ``   </div> ``     
  

*****************************

When I start nano_photos_provider2.php
I see only the text below and no images

{"nano_status":"ok","nano_message":"","album_content":[{"src":"","title":"Album A","description":"","ID":"Album%20A","albumID":"0","kind":"album","t_url":["nano_photos_content\/Album A\/_thumbnails\/berlin A2-A__.jpg","nano_photos_content\/Album A\/_thumbnails\/berlin A2-A__.jpg","nano_photos_content\/Album A\/_thumbnails\/berlin A2-A__.jpg","nano_photos_content\/Album A\/_thumbnails\/berlin A2-A__.jpg","nano_photos_content\/Album A\/_thumbnails\/berlin A2-A__.jpg"],"t_width":[null,null,null,null,null],"t_height":[0,0,0,0,0],"dc":"#c6a670","dcGIF":"R0lGODdhAwADAOMAAPbaqKmKSde\/g1MkEE8tO7mXV2FLHDMkEVM\/JgAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAAwADAAAEBxAEMUgxB0UAOw","cnt":4},{"src":"","title":"Album B","description":"","ID":"Album%20B","albumID":"0","kind":"album","t_url":["nano_photos_content\/Album B\/_thumbnails\/berlin3__.jpg","nano_photos_content\/Album B\/_thumbnails\/berlin3__.jpg","nano_photos_content\/Album B\/_thumbnails\/berlin3__.jpg","nano_photos_content\/Album B\/_thumbnails\/berlin3__.jpg","nano_photos_content\/Album B\/_thumbnails\/berlin3__.jpg"],"t_width":[null,null,null,null,null],"t_height":[0,0,0,0,0],"dc":"#c3c2c1","dcGIF":"R0lGODdhAwADAOMAAOjo6Pr598\/Pzbu7u9\/f39rX0Hl9fnp7fauupQAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAAwADAAAEBxAEMUgxB0UAOw","cnt":4},{"src":"nano_photos_content%2Fberlin1.jpg","title":"berlin1","description":"","ID":"berlin1","albumID":"0","kind":"image","t_url":["nano_photos_content\/_thumbnails\/berlin1__.jpg","nano_photos_content\/_thumbnails\/berlin1__.jpg","nano_photos_content\/_thumbnails\/berlin1__.jpg","nano_photos_content\/_thumbnails\/berlin1__.jpg","nano_photos_content\/_thumbnails\/berlin1__.jpg"],"t_width":[null,null,null,null,null],"t_height":[0,0,0,0,0],"dc":"#c2baac","originalURL":"nano_photos_content%2F%2Fberlin1.jpg","imgWidth":1280,"imgHeight":848,"dcGIF":"R0lGODdhAwADAOMAAIeBX\/T194mTn+fWuujXvejp66mPbqeKYg0JAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAAwADAAAEBxAEMUgxB0UAOw"},{"src":"nano_photos_content%2Fberlin2.jpg","title":"berlin2","description":"","ID":"berlin2","albumID":"0","kind":"image","t_url":["nano_photos_content\/_thumbnails\/berlin2__.jpg","nano_photos_content\/_thumbnails\/berlin2__.jpg","nano_photos_content\/_thumbnails\/berlin2__.jpg","nano_photos_content\/_thumbnails\/berlin2__.jpg","nano_photos_content\/_thumbnails\/berlin2__.jpg"],"t_width":[null,null,null,null,null],"t_height":[0,0,0,0,0],"dc":"#c6a670","originalURL":"nano_photos_content%2F%2Fberlin2.jpg","imgWidth":847,"imgHeight":1280,"dcGIF":"R0lGODdhAwADAOMAAPbaqKmKSde\/g1MkEE8tO7mXV2FLHDMkEVM\/JgAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAAwADAAAEBxAEMUgxB0UAOw"},{"src":"nano_photos_content%2Fberlin3.jpg","title":"berlin3","description":"","ID":"berlin3","albumID":"0","kind":"image","t_url":["nano_photos_content\/_thumbnails\/berlin3__.jpg","nano_photos_content\/_thumbnails\/berlin3__.jpg","nano_photos_content\/_thumbnails\/berlin3__.jpg","nano_photos_content\/_thumbnails\/berlin3__.jpg","nano_photos_content\/_thumbnails\/berlin3__.jpg"],"t_width":[null,null,null,null,null],"t_height":[0,0,0,0,0],"dc":"#c3c2c1","originalURL":"nano_photos_content%2F%2Fberlin3.jpg","imgWidth":1260,"imgHeight":835,"dcGIF":"R0lGODdhAwADAOMAAOjo6Pr598\/Pzbu7u9\/f39rX0Hl9fnp7fauupQAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAAwADAAAEBxAEMUgxB0UAOw"}]}

**Comment by Kris-B** [comment]
there's an issue with the width of the generated thumbnails `"t_width":[null,null,null,null,null]`
can you test with another value than `"auto"`?

**Comment by Evert2311** [comment]
I changed the value in 150 with the same result. I see only text

`` <div id="nanogallery2" data-nanogallery2='{ ``
  ``    "kind":             "nano_photos_provider2", ``
``      "dataProvider":     
`` "https://www.mywebsite/nano_photos_provider2/nano_photos_provider2.php", ``
``      "thumbnailHeight":  150, ``
 ``     "thumbnailWidth":   150, ``
 ``      }'> ``

{"nano_status":"ok","nano_message":"","album_content":[{"src":"","title":"Album A","description":"","ID":"Album%20A","albumID":"0","kind":"album","t_url":["nano_photos_content\/Album A\/_thumbnails\/berlin A2-A__.jpg","nano_photos_content\/Album A\/_thumbnails\/berlin A2-A__.jpg","nano_photos_content\/Album A\/_thumbnails\/berlin A2-A__.jpg","nano_photos_content\/Album A\/_thumbnails\/berlin A2-A__.jpg","nano_photos_content\/Album A\/_thumbnails\/berlin A2-A__.jpg"],"t_width":[null,null,null,null,null],"t_height":[0,0,0,0,0],"dc":"#c6a670","dcGIF":"R0lGODdhAwADAOMAAPbaqKmKSde\/g1MkEE8tO7mXV2FLHDMkEVM\/JgAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAAwADAAAEBxAEMUgxB0UAOw","cnt":4},{"src":"","title":"Album B","description":"","ID":"Album%20B","albumID":"0","kind":"album","t_url":["nano_photos_content\/Album B\/_thumbnails\/berlin3__.jpg","nano_photos_content\/Album B\/_thumbnails\/berlin3__.jpg","nano_photos_content\/Album B\/_thumbnails\/berlin3__.jpg","nano_photos_content\/Album B\/_thumbnails\/berlin3__.jpg","nano_photos_content\/Album B\/_thumbnails\/berlin3__.jpg"],"t_width":[null,null,null,null,null],"t_height":[0,0,0,0,0],"dc":"#c3c2c1","dcGIF":"R0lGODdhAwADAOMAAOjo6Pr598\/Pzbu7u9\/f39rX0Hl9fnp7fauupQAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAAwADAAAEBxAEMUgxB0UAOw","cnt":4},{"src":"nano_photos_content%2Fberlin1.jpg","title":"berlin1","description":"","ID":"berlin1","albumID":"0","kind":"image","t_url":["nano_photos_content\/_thumbnails\/berlin1__.jpg","nano_photos_content\/_thumbnails\/berlin1__.jpg","nano_photos_content\/_thumbnails\/berlin1__.jpg","nano_photos_content\/_thumbnails\/berlin1__.jpg","nano_photos_content\/_thumbnails\/berlin1__.jpg"],"t_width":[null,null,null,null,null],"t_height":[0,0,0,0,0],"dc":"#c2baac","originalURL":"nano_photos_content%2F%2Fberlin1.jpg","imgWidth":1280,"imgHeight":848,"dcGIF":"R0lGODdhAwADAOMAAIeBX\/T194mTn+fWuujXvejp66mPbqeKYg0JAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAAwADAAAEBxAEMUgxB0UAOw"},{"src":"nano_photos_content%2Fberlin2.jpg","title":"berlin2","description":"","ID":"berlin2","albumID":"0","kind":"image","t_url":["nano_photos_content\/_thumbnails\/berlin2__.jpg","nano_photos_content\/_thumbnails\/berlin2__.jpg","nano_photos_content\/_thumbnails\/berlin2__.jpg","nano_photos_content\/_thumbnails\/berlin2__.jpg","nano_photos_content\/_thumbnails\/berlin2__.jpg"],"t_width":[null,null,null,null,null],"t_height":[0,0,0,0,0],"dc":"#c6a670","originalURL":"nano_photos_content%2F%2Fberlin2.jpg","imgWidth":847,"imgHeight":1280,"dcGIF":"R0lGODdhAwADAOMAAPbaqKmKSde\/g1MkEE8tO7mXV2FLHDMkEVM\/JgAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAAwADAAAEBxAEMUgxB0UAOw"},{"src":"nano_photos_content%2Fberlin3.jpg","title":"berlin3","description":"","ID":"berlin3","albumID":"0","kind":"image","t_url":["nano_photos_content\/_thumbnails\/berlin3__.jpg","nano_photos_content\/_thumbnails\/berlin3__.jpg","nano_photos_content\/_thumbnails\/berlin3__.jpg","nano_photos_content\/_thumbnails\/berlin3__.jpg","nano_photos_content\/_thumbnails\/berlin3__.jpg"],"t_width":[null,null,null,null,null],"t_height":[0,0,0,0,0],"dc":"#c3c2c1","originalURL":"nano_photos_content%2F%2Fberlin3.jpg","imgWidth":1260,"imgHeight":835,"dcGIF":"R0lGODdhAwADAOMAAOjo6Pr598\/Pzbu7u9\/f39rX0Hl9fnp7fauupQAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAAwADAAAEBxAEMUgxB0UAOw"}]}

**Comment by Kris-B** [comment]
are thumbnails files generated in the `_thumbnails` folder?
actually, it would be nice to have the **not modified JSON** file to avoid all these questions&answers, even better, the URL to your webserver would be great

**Comment by Evert2311** [comment]
Yes there is a folder _thumbnails `nano_photos_provider2/nano_photos_content/_thumbnails/
`. Besides that what do you mean by not modified JSON file. I did not modify or change any JSON file.
The output text above is from the website when I make a call to 
`www.defamiliemulder.nl/nano_photos_provider2/nano_photos_provider2.php`
Hopefully is this information enough to solve the problem. When not please inform me so I can take te necessary steps.

**Comment by Evert2311** [comment]
Problem solved. There was a small typo in the html file. I can see the pictures now
