### ISSUE TITLE
Can't Click Navigation Thumbnail in iOS for thumbnailLevelUp Option

### ISSUE THREAD

**Issue by ChristopherWerby** [nanostudio-org/nanogallery2#108]
I think Nanogallery2 is terrific!  I'm having a problem, however, on iOS when trying to use the thumbnailLevelUp: true option.  The 'chevron-up' thumbnail within an album can't be clicked on iOS, even though it works fine on a desktop machine.   I forked one of your pens and modified the options, stripping them down for a minimum set -- it displays the problem that the navigation "thumbnail" isn't clickable in iOS.  https://codepen.io/Pipsqueaks/pen/VXzgRL

**Comment by Kris-B** [comment]
I'm closing this issue for now because of inactivity - I personally do not have any device to reproduce the issue
