### ISSUE TITLE
Gallery pulls to the left when scrolling up/down on Samsung Android

### ISSUE THREAD

**Issue by styelz** [nanostudio-org/nanogallery2#11]
Hello,

I have a problem when displaying my gallery on my Samsung phone Galaxy i9300 using Chrome and other browsers.  The gallery pulls to the left (offscreen) when scrolling down the page dragging the thumbnails. It works fine when dragging using the scroll bar on the far right. The further to the left I place my finger on the screen the items dont scroll off to the left as far as when I pull down from closer to the right of the screen. You can see it here on this video I recorded: https://youtu.be/K3ujhHKong4

The OS is CM Android 7.1.1. Also on stock OS (verified by a friend). I have a simple gallery setup to test this here: https://www.hiphopdontstop.info/dev/gallery2.php

**Comment by Kris-B** [comment]
Hi,
I'm using hammer.js to manage the gesture, and it seems that this issue could be related to: https://github.com/hammerjs/hammer.js/issues/1050

I'm looking for a solution....

**Comment by Kris-B** [comment]
still no solution from the hammer.js team...

in the meanwhile, you can disable swipe for pagination, with the option `paginationSwipe: false`

**Comment by Kris-B** [comment]
Hi, I made some changes on the gesture handling.
Could you please check the gallery on the intro page http://nanogallery2.nanostudio.org/
to see if you still have issues on Android?
(there are still some "little jumping" but my first tests show that is better).
Thansk!

**Comment by Kris-B** [comment]
fixed in v1.2.0
Even if not perfect, I'm closing this issue for now.
