### ISSUE TITLE
Not showing Albums in Nanogallery2

### ISSUE THREAD

**Issue by Evert2311** [nanostudio-org/nanogallery2#110]
In Nanogallery the albums were visible in the root, however, since I use Nanogallery2, I do not see Albums anymore. I'm doing something wrong?
If so please provide me with a example what to do.
See my html file in the attachement
[index.docx](https://github.com/nanostudio-org/nanogallery2/files/1887387/index.docx)
:
https://www.xxxxx.xx is my webservername

**Comment by Kris-B** [comment]
I need to access your nano_photos_provider2 server, can you provide the URL ?

**Comment by Evert2311** [comment]
I like nanogallery very much. However I want Nanofallery to do more, for example sort photos in every map on exif DatTimeOriginal, put exif data Description benath the Photo etc. Therefore I am trying JAlbum.
