### ISSUE TITLE
how could I turn a image into vertical format

### ISSUE THREAD

**Issue by petereth** [nanostudio-org/nanogallery2#111]
Hi 

i am very happy about the http://nanogallery2.nanostudio.org

I put a google photo into this page with the code from the builder
http://www.ml400.net/netzburg/fotothek/

my question is how could I turn a image into vertical format

I could not find this in the doku
https://nanogallery2.nanostudio.org/documentation.html

Regards
Peter

**Comment by petereth** [comment]
https://imgur.com/a/K3c70

**Comment by Kris-B** [comment]
not possible... the browser handles the orientation
