### ISSUE TITLE
How to use custom viewertheme using HTML markup method?

### ISSUE THREAD

**Issue by wvdweerd** [nanostudio-org/nanogallery2#112]
First: thanks for developing and maintaing this great gallery!

I am using the html markup method on my new website, but would like to customize some of the lightbox styling. In particular I would like to change the background colour from black to a dark grey colour, and I want to add a thin white border around the image.

I have seen in your [user guide](https://nanogallery2.nanostudio.org/documentation.html#ngy2_colorschemes) that custom theme's are supported.

But can I do this in html markup mode? 
If so, what is the exact syntax and what are the possible values for the properties of a custom theme?

**Comment by Kris-B** [comment]
you can use this syntax:
```
      "viewerTheme": {
          "background": "#008"
      }
```
