### ISSUE TITLE
Thumbnails don't load when gallery isn't in view on page load

### ISSUE THREAD

**Issue by thanatoid** [nanostudio-org/nanogallery2#113]
If gallery is on a part of the page that isn't in the window on load (eg, lower down and needs to be scrolled to), the thumbails will not show unless the page is refreshed or resized. Tested in OSX 10.12.4, FF Dev 58.0b12, FF 52.0, Safari 10.1 (12603.1.30.0.34), Chrome 65.0.3325.181. 

After initial page load and scrolling down
<img width="1150" alt="load and scroll down" src="https://user-images.githubusercontent.com/3454076/38952146-8107b3ce-42ff-11e8-9c0c-674dab853a8d.png">

After refreshing page in same position as above
<img width="1154" alt="after page reload" src="https://user-images.githubusercontent.com/3454076/38952145-80e93282-42ff-11e8-84b3-fbde5ab49e1e.png">

**Comment by Kris-B** [comment]
Are you adding items dynamically to the gallery ?
Did you check this sample: https://codepen.io/Kris-B/pen/wJKowg

**Comment by Kris-B** [comment]
any update?

**Comment by thanatoid** [comment]
Not talking about images loaded dynamically. The images in the after refresh screenshot where already added to the page in the first. No changes, updates, or additions were made to code that builds the gallery between first load and refresh.

**Comment by Kris-B** [comment]
any feedback ?

**Comment by Ref-13** [comment]
Hello, same problem, how did you solve that? I have the latest version of nanogallery2. Thanks (I opened a topic about this)

**Comment by FrancisGarrity** [comment]
Same problem, bump

**Comment by joelz** [comment]
I just solved a problem somehow like the one described in this issue. 

There are 300+ photos in my gallery, and the gallery init code is 
```
        this.$nanogallery2.nanogallery2('destroy');
        this.$nanogallery2.nanogallery2({
            items: this.currentAlbumData.photoItems,
            itemsBaseURL: this.currentAlbumData.baseUrl,
            viewerToolbar: { display: false },

            thumbnailWidth: 'auto XS150 SM200',
            thumbnailHeight: '250 XS150 SM200',
            thumbnailAlignment: 'fillWidth',
            galleryRenderDelay: 100,
            eventsDebounceDelay: 100,

            galleryDisplayMoreStep: 15,
            galleryDisplayMode: 'moreButton',
            touchAutoOpenDelay: 0,
            touchAnimation: false,

            thumbnailL1GutterWidth: 1,
            thumbnailL1GutterHeight: 1,
            thumbnailBorderHorizontal: 0,
            thumbnailBorderVertical: 0,

            gallerySorting: 'random',
            locationHash: true
        });
```

The point to be noted is that the gallery is in a Ionic Modal: 

![image](https://user-images.githubusercontent.com/469974/51012433-fcfa0700-1597-11e9-8066-10e98126e876.png)

For now, everything seems to be ok. But when you scroll down, you see this: 

![image](https://user-images.githubusercontent.com/469974/51012499-5eba7100-1598-11e9-948c-1ae25e34fe33.png)

Some thumbnails in the first batch don't show up. 

After some search in the issues of this repo and some investigation in normal sample code，I guess there may need some code in the modal onscroll event. So I add following code in `ionViewDidLoad` event of the modal (`ionViewDidLoad`  in Ionic is somehow like  `window.onload` ): 
```
            this.content.ionScroll.subscribe((event) => {
                if (event && event.scrollTop > 150 ) {
                    this.$nanogallery2.nanogallery2('resize');
                }
            });
```

Problem solved.

Hope this helps someone.

**Comment by Kris-B** [comment]
I'm closing this issue as I don't have enough information to handle the initial issue.
