### ISSUE TITLE
Loading nanogallery with AMD

### ISSUE THREAD

**Issue by Skoucail** [nanostudio-org/nanogallery2#115]
Loading the nanogallery2 plugin with AMD is a problem.
We are expecting a anonymous module (as the comment describes)
But as you can see the define actually makes a named modules 'nanogallery2'.

`if (typeof define === 'function' && define.amd) {`
`        // AMD. Register as an anonymous module.`
`        define('nanogallery2', ['jquery'], factory);`

**Comment by Kris-B** [comment]
any suggestion to fix this?

**Comment by Skoucail** [comment]
I think the comment is correct.
So the define should be changed to:
`define([‘jquery’], factory);`
That way the module is anonymous. And woulds with the AMD loader i use.

**Comment by Kris-B** [comment]
I changed this in v2.2.0
but I couldn't test if it works now...

**Comment by Kris-B** [comment]
any feedback ? Could you test it ?

**Comment by Skoucail** [comment]
Sorry for the late answer, but i was already working on other projects.
I just tested the new version and it works with our AMD loader without problems now
Thx!

**Comment by Kris-B** [comment]
thanks for the feedback :wink:
