### ISSUE TITLE
Issue with lazy loading of images

### ISSUE THREAD

**Issue by macsupport** [nanostudio-org/nanogallery2#116]
I am having an issue when using `$('#nanoGallery').nanogallery2('displayItem', albumId);` . It seems that a bit of scrolling is necessary to load the images, even when reloading the same folder of images. I also see this occasionally when clicking on a folder as well. I am assuming this is related to lazyloading of the images. Is their an option to change the scroll threshold? I use [Lazysizes](https://github.com/aFarkas/lazysizes) in many of my projects and it implements this quite well.  Nanogallery2 lazyloading also seems very slow to me and I'm not sure why images above the viewport are removed and then have to be reloaded when one scrolls back up.

**Comment by Kris-B** [comment]
Actually, images are removed/hidden to avoid performance issues with very large galleries.
You can disable this feature with:
`thumbnailDisplayOutsideScreen: true `

Do you want some options to tweak the lazyloading (threshold and delay) ?

**Comment by macsupport** [comment]
Thanks! Some tweaking of the lazy loading would be helpful. I temporarily dealt with my issue by adding `$('html, body').scrollTop(1)`. Not the best option, but makes the images load.

**Comment by macsupport** [comment]
Yes.
 I've found the issue to be with galleryDisplayTransition. Especially rotateX. If I set that to null, no issue

**Comment by Kris-B** [comment]
Did you write a module to handle your data, like the one for Flickr or Google?
Can you please check that you set the album property `contentIsLoaded` to true when an album is created ?
For some hints, you may have a look a this codepen: https://codepen.io/Kris-B/pen/wJKowg

Instead of scrollTop you can use methods "refresh" or "resize" (better, but only available in the current DEV branch: https://github.com/nanostudio-org/nanogallery2/tree/dev)

**Comment by Kris-B** [comment]
New option `eventsDebounceDelay` in v2.2.0 for fine tuning the response delay in ms after resizing, rotation and scroll events. Lazyloading is fired by these events.

**Comment by Kris-B** [comment]
No feedback since quite a while -> I'm closing this issue but you can open it again if needed

**Comment by DannyK987** [comment]
Hi - I also have the problem, that the gallery photos need too long to load with lazy load...  I have tested shortly with "eventsDebounceDelay: 0" - but have no faster load of the pictures. Or how should I use that?
