### ISSUE TITLE
Joomla 3 CSS Conflict (.icon-*) with nanogallery2

### ISSUE THREAD

**Issue by LuxLOL** [nanostudio-org/nanogallery2#117]
HI,
nanogallery2 will not show any Icons when it is included in Joomla 3.
I found out that there is a conflict with the nanogallery2 CSS and the Joomla Bootstrap CSS.
I think every nanogallery2 CSS entry should have ".nGY2" in front of it to avoid problems with some Content Manage Systems that use Bootstrap. The main problems are the ".icon-*" CSS entries.

![nanogallery2 - joomla css conflict](https://user-images.githubusercontent.com/37483703/39390801-3ab6393e-4a9a-11e8-9886-2df714a61f57.png)

**[EDIT=I found out how to fix this]**
1 - In all nanogallery2 _*.CSS_ files replace `.nGY2Icon` with `[class^="nGY2Icon-"]`
2 - In all nanogallery2 _*.CSS_ files replace `.icon-` with `.nGY2Icon-`
3 - In the file "jquery.nanogallery2.core.js" and  "jquery.nanogallery2.core.min.js" and "jquery.nanogallery2.js" and "jquery.nanogallery2.min.js" replace `nGY2Icon icon-` with `nGY2Icon-`
This has fixed my problem. ;-)

**Comment by Kris-B** [comment]
thanks for your solution
fixed in v2.2.0
