### ISSUE TITLE
Download name is always jpg.jpg

### ISSUE THREAD

**Issue by LuxLOL** [nanostudio-org/nanogallery2#118]
HI,
When downloading a image from nanogallery2 the name of the image file is always "jpg.jpg" looks like nanogallery2 is not using the correct file name of the image file name or the link name of the image file.

**Comment by Kris-B** [comment]
How do you define the content of your gallery ? A sample ?

**Comment by LuxLOL** [comment]
I have define the content like the example gallery on this site. The Builder on this site has also the same problem.
https://nanogallery2.nanostudio.org/builder.html

**Comment by Kris-B** [comment]
not on my computer/browser...
which browser are you using ?

**Comment by LuxLOL** [comment]
I tried it on Internet Explorer Edge. And i also noticed now that in FireFox i get another behavior, there it will open the image in the same Window again without promoting me to download it.

**Comment by Kris-B** [comment]
I made some changes, can you check the version in the DEV branch ?

https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by LuxLOL** [comment]
Hi,
Now the correct file name is shown in Internet Explorer Edge and Firefox with the DEV branch. ;-)

**Comment by Kris-B** [comment]
thanks for the feedback.
fixed in v2.2.0
