### ISSUE TITLE
Thumbnails with a Single Quote wont load

### ISSUE THREAD

**Issue by LuxLOL** [nanostudio-org/nanogallery2#120]
HI,
I found out that the Thumbnails with a Single Quote **(It's Fun)** wont load, but the original image is loading when click on the empty Thumbnail.

**Comment by Kris-B** [comment]
please provide a codepen sample to reproduce this issue
thanks

**Comment by Kris-B** [comment]
I'll fix this in the next release
in the meanwhile you can replace `'` with`%27` as a workaround

**Comment by LuxLOL** [comment]
Thanks.
For now i removed the **'** but the %27 is better idea. ;-)

**Comment by Kris-B** [comment]
fixed in v2.2.0
