### ISSUE TITLE
Ajax dynamic gallery problem

### ISSUE THREAD

**Issue by ronyyu** [nanostudio-org/nanogallery2#124]
Hi,

I have a div with id="main"on my page which contains my <div id="my_nanogallery2"></div> with allpictures inside.
Here everything's ok.

When I call an ajax function to update my main div with this content and use the refresh function from the lib
<div id="my_nanogallery2">

</div>

Everything works fine and it loads the content. 

But, the problem is now when I click on a picture, it reloads everything and doesn't show the picture like it should do.

Am I missing something?

**Comment by Kris-B** [comment]
hi, do you have this when you open an image or an album ?

**Comment by ronyyu** [comment]
When I open an image

**Comment by Kris-B** [comment]
can you provide the URL of the page with this issue ?  or a codepen ?

**Comment by Kris-B** [comment]
please use this codepen example to check your code
https://codepen.io/Kris-B/pen/wJKowg

**Comment by ronyyu** [comment]
sorry for late reply. Ok thanks. I'll do this

**Comment by ronyyu** [comment]
Here is my codepen, https://codepen.io/ronyyu/pen/yjGaOO
The thing is it works perfectly on codepen, but the same code doesn't work on my locahost dev machine.
The only difference is on the codepen, "data" comes from javascript directly, and on my machine data comes from the server side.

I'll investigate more and let you know.

**Comment by Kris-B** [comment]
Ok, thanks for thé update

**Comment by shensheng27** [comment]
the same.
I assign new id each time to avoid it now.
2.2

**Comment by Kris-B** [comment]
if you refresh the data to replace them, then you need to destoy the existing gallery
`$('#your_nanogallery2').nanogallery2('destroy');` 

if you add data to an existing galery, the IDs must be unique

**Comment by ronyyu** [comment]
@Kris-B super, thanks !
The destroy method works for me.

**Comment by Kris-B** [comment]
@ronyyu thanks for the update!
