### ISSUE TITLE
Custom theme using colorSchemeViewer not working

### ISSUE THREAD

**Issue by macsupport** [nanostudio-org/nanogallery2#126]
I forked one of you code pens and added a custom colorSchemeViewer and the changes are not shown. Here is the [codepen](https://codepen.io/macsupport/pen/xjYjRq)

    jQuery(document).ready(function () {
  
    var customColorLightbox = {
    background:     '#f90', imageBorder: 'none', imageBoxShadow: 'none',
    barBackground:  'rgba(40, 40, 40, 0.7)', barBorder: '0px solid #111', barColor: '#eee',          barDescriptionColor: '#fff'
    };
     jQuery("#my_nanogallery2").nanogallery2({
  	items:[
        // album 1
        	{
					src:   'berlin1.jpg',		     // image url
					srct:  'berlin1t.jpg',	     // thumbnail url
					title: 'Berlin - album 1',   // item title
          ID: 1,                       // item ID
          kind: 'album'                // item kind
			},
			{ src: 'berlin1.jpg', srct: 'berlin1t.jpg', title: 'Berlin 1', ID: 10, albumID: 1},
			{ src: 'berlin2.jpg', srct: 'berlin2t.jpg', title: 'Berlin 2', ID: 11, albumID: 1},

         // album 2
        { src: 'berlin2.jpg', srct: 'berlin2t.jpg', title: 'Berlin - album 2', ID: 2, kind: 'album'},
			{ src: 'berlin2.jpg', srct: 'berlin2t.jpg', title: 'Berlin 2', ID: 21, albumID: 2},
			{ src: 'berlin1.jpg', srct: 'berlin1t.jpg', title: 'Berlin 1', ID: 22, albumID: 2},
			{ src: 'berlin3.jpg', srct: 'berlin3t.jpg', title: 'Berlin 3', ID: 23, albumID: 2},
      
       // top level images
	 		{ src: 'berlin2.jpg', srct: 'berlin2t.jpg', title: 'Berlin 2' },
       { src: 'berlin3.jpg', srct: 'berlin3t.jpg', title: 'Berlin 3' }
		],
     thumbnailWidth:  'auto',
  	thumbnailHeight: 170,
     itemsBaseURL:    'https://nanogallery2.nanostudio.org/samples/',
		locationHash:    false,
     colorSchemeViewer: customColorLightbox,
      });
      });

**Comment by Kris-B** [comment]
Please use `viewerTheme` instead of `colorSchemeViewer`

both should be synonymous, but there seems to be an issue...
