### ISSUE TITLE
keep it in my server: nanogallery2.min.css

### ISSUE THREAD

**Issue by mauricioclima** [nanostudio-org/nanogallery2#129]
I am trying o sabe the https://cdn.rawgit.com/nanostudio-org/nanogallery2/dev/dist/css/nanogallery2.min.css in my server, but when I do that, all the buttons disappear, just it`s image, the button shape is there.

Can I have  nanogallery2.min.css in my server and it still works?

Thanks,

**Comment by Kris-B** [comment]
you also need the css/font folder and it's content on your server
