### ISSUE TITLE
Custom color schemes not working

### ISSUE THREAD

**Issue by wykananda** [nanostudio-org/nanogallery2#13]
Hi there. Thanks for the wonderful update to the Nanogallery - I'm sure it was a ton of effort. 

I'm noticing what appear to be issues with custom color schemes.  None of the value changes seem to be taking.

Can you please have a look at [http://codepen.io/wykananda/pen/WRLVOp?editors=1010](url) and let me know if I'm doing something wrong?

thanks

**Comment by Kris-B** [comment]
codepen has been removed...

**Comment by wykananda** [comment]
Sorry, it seems I entered the URL using the wrong formatting.   Here it is fixed: [Custom Color Schemes Problem - CodePen Example](http://codepen.io/wykananda/pen/WRLVOp?editors=1010).  Can you please have a look?

Thanks!

**Comment by macsupport** [comment]
If your using html markup you need to use `"colorScheme": { "thumbnail" : { "background": "#F00", "borderColor": "#0F0" } },` instead of `"colorScheme": "myCS",`
