### ISSUE TITLE
Joomla3/Bootstrap2 Image Zoom In Bug

### ISSUE THREAD

**Issue by LuxLOL** [nanostudio-org/nanogallery2#130]
Hi,
When i use NanoGallery2 in Joomla3/Bootstrap2 Website and Zoom In an image then the image will Zoom In to the left out of the window.
I have tried to find out what could cause this problem but i had no luck to track this problem down.
Here is a Joomla3/Bootstrap2 test Website with NanoGallery v2.2.0:
http://www.zone62.com/image-gallery/full-hd-1080p-wallpapers/124-abstract

**Comment by Kris-B** [comment]
can you try the version in the DEV branch?
https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by LuxLOL** [comment]
HI,
I tried the new DEV branch and this one has fixed this Zoom In Bug.
Thanks. :).

**Comment by Kris-B** [comment]
thanks for the feedback ;-)

**Comment by Kris-B** [comment]
fix released in v2.3.0
