### ISSUE TITLE
Having issues with image deep linking

### ISSUE THREAD

**Issue by gsigouin** [nanostudio-org/nanogallery2#131]
This happens when the images are stored on a Flickr album.

When I link to a specific photo using the share button from the Nanogallery, the link sends me to the album page (with all the thumbnails), not the specific photo.  

I have noticed that when I paste the link into a browser, for example, "http://www.mywebsite/index.html#nanogallery/my_nanogeallery2/72157669542181508/42382719362", it gets changed to "http://www.mywebsite/index.html".  If I paste the full link a second time in the same browser window, it stays full and I have access to the specific photo.

(Notice that the full link contains the Flickr album ID and photo ID.)

The same happens with links created for Facebook (although I cannot paste twice in this case).

If my pictures are stored on my webserver, then everything works perfectly the first time around.  No need to paste the link twice.

This issue happens when I'm hosting my pictures on Flickr.

Note: the "locationHash" property is enabled.

You can see the code here: https://goo.gl/iTdHiG

Any idea what is going on?

Thank you.

**Comment by Kris-B** [comment]
can you please try the version in the DEV branch, and let me know if it's fixed ?

https://github.com/nanostudio-org/nanogallery2/tree/dev/dist

**Comment by Kris-B** [comment]
fix released in v2.3.0
