### ISSUE TITLE
Scroll to top on image view

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [nanostudio-org/nanogallery2#134]
Hello,

When I open an image, the page scrolls to top.

I managed to find out that this was because I did add: 

```
html {
    overflow-x: hidden !important;
}
```

to my css.

Any idea on how I could get this fixed please ?

**Comment by Kris-B** [comment]
can you post a sample on CodePen showing this issue ?

**Comment by Kris-B** [comment]
Any update ?

**Comment by Kris-B** [comment]
No update, so I'm closing this issue for now. Feel free to open it again with new details.
