### ISSUE TITLE
Google Album

### ISSUE THREAD

**Issue by dwbuss** [nanostudio-org/nanogallery2#135]
Where do I have the id for a google photos album?

div data-nanogallery2='{
        "userID": "xxxxx",
        "kind": "google2",
        "google2URL": "http://www.xxxxxxxx.com/nanogp/nanogp.php",
        "album": "?",
        "thumbnailWidth": "auto",
        "thumbnailDisplayInterval": 30,
        "thumbnailLabel": {
          "display": false
        }
      }'

**Comment by Kris-B** [comment]
open the album in Googe Photos: the album ID is in the URL
