### ISSUE TITLE
no lightbox when using nanogallery2 for shopify site

### ISSUE THREAD

**Issue by machnam** [nanostudio-org/nanogallery2#137]
Hi,
I am trying to install nanogallery2 for my site running on shopify-clone flatform. The gallery is displaying nice but no lightbox comes up when click on the thumbnails. It gets 404 errors. (as the screenshot attached).
I realize every time I click on the thumbnails, it appends `nanogallery/my_nanogallery/0` into the entire url, and the error happens.
My site is running on shopify so all asstes are not comes from main domain. I can not organize any folders tree like normal hostings. It has only one root folder
You may know how shopify front end works. Please take a look on my screenshot.
![chrome_2018-08-09_02-28-47](https://user-images.githubusercontent.com/23330093/43860454-f5064246-9b7d-11e8-8e4e-e22965ccef20.png)
Thank you very much!

**Comment by Kris-B** [comment]
can you try to disable hash tracking?
`locationHash: false `

**Comment by Kris-B** [comment]
Any update?

**Comment by Kris-B** [comment]
No update, so I'm closing this issue for now. Feel free to open it again with new details.
