### ISSUE TITLE
galleryFilterTags

### ISSUE THREAD

**Issue by brandstoretirol** [nanostudio-org/nanogallery2#138]
Hi, how does "galleryFilterTags" work?
i use galleryFilterTags: 'description' - but nothing to see :-(
thx bs

**Comment by Kris-B** [comment]
are descriptions defined ? can you post an example on CodePen ?

**Comment by brandstoretirol** [comment]
yes ...hiere is one entry

<a href="6120940_AllPassionW189_1068.jpg" data-ngthumb="6120940_AllPassionW189_1068.jpg" data-ngdesc="<b>ALL PASSION_W189</b><br><br>Art.Nr.: 612 0940 | Farbe: 10/68<br><b>one size</b><br><br>Das trendige Martini-Schlauchtuch ist individuell einsetzbar und garantiert ein angenehmes Tragegefühl durch hochwertige Microfaser.<br><br>100 % PES Micro<br><br>Skitouring | Nordic | Speed Performance | Running | Trailrunning | Free Touring | Leisure<br><br>€25,90">ALL PASSION_W189 €25,90</a>

**Comment by brandstoretirol** [comment]
data-ngdesc="<b>ALL PASSION_W189</b><br><br>Art.Nr.: 612 0940 | Farbe: 10/68<br><b>one size</b><br><br>Das trendige Martini-Schlauchtuch ist individuell einsetzbar und garantiert ein angenehmes Tragegefühl durch hochwertige Microfaser.<br><br>100 % PES Micro<br><br>Skitouring | Nordic | Speed Performance | Running | Trailrunning | Free Touring | Leisure<br><br>€25,90"

**Comment by Kris-B** [comment]
I mean:  can you build a live example on CodePen ?

**Comment by Kris-B** [comment]
any update ?
