### ISSUE TITLE
shoppingCart

### ISSUE THREAD

**Issue by brandstoretirol** [nanostudio-org/nanogallery2#139]
Hi,
how can i activate the "shoppingCart Basket"?
thx bs

**Comment by Kris-B** [comment]
just display the tool
`"thumbnailToolbarImage" : { "topLeft" : "cart" },`

**Comment by brandstoretirol** [comment]
Hi Kris.. thx 
in which filedo i need this entry?
thx bs

**Comment by brandstoretirol** [comment]
i have found it -- the cart icon is here, but there is no functionality :(

thx

**Comment by brandstoretirol** [comment]
Hi Chris,
we have a problem - can you help? https://github.com/nanostudio-org/nanogallery2/issues/152
thx
tom
