### ISSUE TITLE
Improve sharing on Facebook

### ISSUE THREAD

**Issue by RadekHavelka** [nanostudio-org/nanogallery2#141]
Hi,
  first of all, thanks for this great script!
  I'd appreciate if we can discuss how to implement better facebook sharing of a given image. Current version, as I have installed from few weeks ago, is not able to do that in some nice manner. If I hit share button, then FB, i get in facebook windown preview of GALLERY with FIRST image from that gallery as preview. That doesn't make sense for users to share as it doesn't show the image they wanted to share in first place. 
  I understand as the FB sharing script changed during years, that it is not possible to provide different IMAGE and URL parameters anymore, they have to be bound together, ideally using the meta tags (open graph properties) in HTML. Sharing the image via # segment in URL makes it impossible for FB to parse such URL and make any clever preview from that.
  I do not have any solution to this so far, I'd like to start this topic so maybe others may join in with their ideas how to solve it?
  Thanks

**Comment by Kris-B** [comment]
good point, the sharing on FB is not optimal at all, but I've no idea how to make it better....

**Comment by Kris-B** [comment]
I could not find any way to improve facebook sharing. I'm closing this issue for now.
