### ISSUE TITLE
Thumbnails small on page

### ISSUE THREAD

**Issue by calciummen** [nanostudio-org/nanogallery2#142]
I have a problem that the thumbnails are really really small. I am using the nano proto provider.

![nano gallery](https://user-images.githubusercontent.com/22883666/44715381-f9b62100-aab7-11e8-8e3b-d347ed2204cf.png)

In the image you can see how small it is.

thumbnailWidth: 'auto XS80 SM120',
thumbnailHeight: '200 XS80 SM120',

this is the width and height setting for the thumbnails

I am using bootstrap 4 on my site. Maybe this is interfering?

**Comment by Kris-B** [comment]
can you provide the URL of the page ?

**Comment by Kris-B** [comment]
any update ?
