### ISSUE TITLE
getting G+ photos instead of Google Photos

### ISSUE THREAD

**Issue by fprati** [nanostudio-org/nanogallery2#15]
Hi Christophe, very nice piece of work indeed!
I have installed your latest nanogallery2 and nanogp, but what I get displayed are the G+ photos for that account instead of the Google Photos, weird isn't it? When I use the same credentials on your builder page I get the right photos.
What can be the cause? My setup is on Windows/IIS with php enabled and I use the hosted jquery 1.9.1. Same result with your jquery 2.1.1 instruction on cloudflare.

I also tried the portable beta version, but then I get 
"nanogallery2: Could not retrieve Google data. Error: Missing access token. Please grant authorization. [ngy2p]"

**Comment by Kris-B** [comment]
Hi,
Did you create some albums in Google Photos?
When did you create your albums in Google+?

I just updated the portable version. Maybe you can try it again?
You need to grant authorization twice:
1. for the builder
2. for nanogallery portable so the galleries can be defined with the shortcode

**Comment by fprati** [comment]
Hi Christophe,
sure I have galleries in Google Photos ; after upgrade to 1.0.0 I get a missing token error or something. But now the portable version works! :)
I guess I will use that for now.

**Comment by Kris-B** [comment]
Hi Franco, thanks for your feedback!

If you enjoy nanogallery, maybe you can leave a review to share your experience: https://krisb1.typeform.com/to/zyHSZD

Chris
