### ISSUE TITLE
viewerInfo

### ISSUE THREAD

**Issue by brandstoretirol** [nanostudio-org/nanogallery2#152]
Hi,
how can i call the "viewerInfo event" with an ImageID ?

thx
tom

![image](https://user-images.githubusercontent.com/38783363/45874121-5f828980-bd94-11e8-9f0c-53939d79b791.png)

**Comment by Kris-B** [comment]
I'm not aware of this event...

**Comment by wuhi** [comment]
Hi Kris!

the question is how can we open the viewInfo dialog with a functioncall?
the viewerInfo is part of nanogallery if you press the [i] button in detail view. but we cannot find the method that opens this dialog from outside.
we have the image-id and know the gallery instance.

thanks!

**Comment by Kris-B** [comment]
You have to provide your own dialog.
Please check this sample to see how to implement it:
https://codepen.io/Kris-B/pen/VyZdOJ
