### ISSUE TITLE
Would it be possible to get the previous swipe imageTransition effect back?

### ISSUE THREAD

**Issue by Apollodore** [nanostudio-org/nanogallery2#155]
Would it be possible to give the opportunity to choose between swipe and swipe2 ? Thank you for your greta job! Best regards, Pascal

**Comment by Apollodore** [comment]
Dear Kris, It's strange, I already tried and I have exactly the same transition when I choose 'swipe' and when I choose 'swipe2', the new swipe transition with the media getting bigger during the transition. (I tried to be sure: I do have a different transistion when I choose 'slideAppear') . Thank you in advance for your help. Best regards, Pascal

**Comment by Kris-B** [comment]
Hi Pascal, sorry for the delay.
This issue will be fixed in v2.4.0
Beta is available in the DEV branch: https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by Kris-B** [comment]
v2.4.0 is released - https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.4.0

**Comment by Apollodore** [comment]
That's great, thank you very much Christophe!
