### ISSUE TITLE
Gallery appears only when the browser window is manual resize

### ISSUE THREAD

**Issue by Ref-13** [nanostudio-org/nanogallery2#156]
Hello,
My site is a onepage. The menu pages dynamically appear in jquery with DIV in "hide / show".
Problem, the gallery (**nanogallery2**) does not appear when the div toggle in "show".
Incredibly, if I resize the browser window, even a single pixel, it appears perfectly. Same if I display "inspector element" (f12)
I tried all day to solve that. I am dummy in javascript, and do not understand how to do it.
I found topics that speak (Refreshsize? (for _nanogallery1_)) But I do not understand where to put it or how to do it.
Thanks in advance !
(sorry for my english, I'm french)

**Comment by ljevarster** [comment]
Same problem. Gallery does not load thumbnails if not in view but further down the page. No console errors, thumbnails appear after resizing the browser window.
Suggested solution $('#your_nanogallery2').nanogallery2('refresh'); does not work.

**Comment by Kris-B** [comment]
@ljevarster can you provide the URL of your page for a check ?

**Comment by ljevarster** [comment]
> @ljevarster can you provide the URL of your page for a check ?

@Kris-B sure, https://tinyurl.com/moodgallerytest
Please scroll to the 3rd section (green) and resize the browser window.
Tested on Firefox and Chrome for now.

**Comment by ljevarster** [comment]
Awesome support, makes me want to buy the plugin 👍

**Comment by Kris-B** [comment]
actually, in your page, no images/medias are defined

**Comment by Kris-B** [comment]
I mean : you have to define some images/medias

**Comment by Kris-B** [comment]
I'm closing this issue for now as the page with the issue does not work. You may open it again with new details. Thanks.
