### ISSUE TITLE
Pagination with numbers / scroll up

### ISSUE THREAD

**Issue by Boris-BBB** [nanostudio-org/nanogallery2#157]
Hello, how to fix this? When I click next page in pagination bar, gallery stays at bottom, how to make it scroll up to top, to see header. In NG1 it was something simple with jquery-1.7.1.min.js, what is with NG2?
Here is example: [https://novolabels.000webhostapp.com](url)

Thanks,and sorry for bad english :) , I hope you understand the problem.

**Comment by Kris-B** [comment]
fixed in v2.4.0 - https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.4.0

**Comment by Kris-B** [comment]
Please note that package for v2.4.0 was corrupted - please use v2.4.1
