### ISSUE TITLE
Auto call "displayphoto(,)" on gallery load

### ISSUE THREAD

**Issue by speusippo** [nanostudio-org/nanogallery2#158]
Hi,
I'm making a smart digital photo frame with Raspberry PI Zero W.
I load Chromium, in kiosk mode, at startup. And I launch a webpage with nanogallery2 that takes photos from a Google Photo album.

All works smooth. But every time I have to connect the mouse and click on a picture to start the displayphotoidx function, that make a slide show at full screen.

How can I call from the index.html (on which are loaded the jquery) the displayphoto function? And what idx I have to pass? In other words, how can I start automatically the slide show (displayphotoidx function) at full screen on load?

Thanks,
J.

**Comment by Kris-B** [comment]
You can use the API method `displayItem`
