### ISSUE TITLE
Flickr limited to 1000 photos for free user

### ISSUE THREAD

**Issue by norbert45fr** [nanostudio-org/nanogallery2#159]
Hello all,
Just want to thank you all for the great work and help you are providing to non-profit associations by delivering such a great tool.
I know this may not be an issue (but perhaps it is) but you have heard about recent rules changed on flickr (https://www.businesswire.com/news/home/20181101005328/en/Flickr-Announces-New-Photographer-Centric-Improvements-Flickr-Pro) with limitation to 1000 photos to free account.

Nanogallery 1 & 2 was a great alternatives when picasa was deprecated and stopped by google. My association is using blogger from google and we have integrated nanogallery  so photo albums are published very easily and quickly. I know yo uhave written PHP alternative with google photos but we do not have PHP web site and we have some security reasons to not go this way.

My questions are: 
- is there any plan to migrate away from flickr to another photo provider in nanogallery?
- does a plugin to instagram can be a future evolution to replace flickr quickly?
- is there any plan to add more photo provider to this tool?

Thanks for any help and comment you can provide.

**Comment by rradjabi** [comment]
I have the same thoughts on this. I had been using Flickr to host my photos for the unlimited storage and a simple nanogallery2 webpage for viewing them. Any thoughts on where to migrate my photos now?

**Comment by Kris-B** [comment]
It's difficult to find another photo provider like Flickr.
One provider should:
- have an API for javascript usable directly in the browser
- the API should not need any user and password to access data
- and the API should provide automatically thumbnail images

Do you know one ?

**Comment by rradjabi** [comment]
@Kris-B

What's the requirement on auto thumbnail generation? It wouldn't be hard to write a simple script or application that generates thumbs. Do thumbnails dynamically get generated upon request? Or is a static thumbnail file acceptable?
