### ISSUE TITLE
nanogallery2: error: no image to process. [my_nanogallery]

### ISSUE THREAD

**Issue by jithu121212** [nanostudio-org/nanogallery2#16]
when i try your example ,i got nothing other than above mentioned error.pls help.

**Comment by Kris-B** [comment]
please give me some details
which example did you try?
can you provide the URL of your page?

**Comment by jithu121212** [comment]
[nanogallery.zip](https://github.com/nanostudio-org/nanogallery2/files/815879/nanogallery.zip)
and i use \
 <?= \backend\nanogallery\Nanogallery::widget()?>
in form to display it then i got above mentioned error.
![screenshot from 2017-03-03 11-07-44](https://cloud.githubusercontent.com/assets/24386580/23539476/b7722e22-0001-11e7-87e8-4b9b771f5993.png)

nb-i'm using your widget in yii2

**Comment by Kris-B** [comment]
2 single quotes are missing around `{...}`

Please change:
```
  $html= '<div data-nanogallery2={ "userID": "34858669@N00", "kind": "flickr" } ';
```
in:
```
  $html= '<div data-nanogallery2=\'{ "userID": "34858669@N00", "kind": "flickr" }\' ';
}
```

**Comment by jithu121212** [comment]
I tried it.But with mournful this doesn't correct it.Same error existing

**Comment by Kris-B** [comment]
In your browser, when you display the source code of your page, can you find following (with the exact syntax)?

```
<div data-nanogallery2='{ "userID": "34858669@N00", "kind": "flickr" }'></div>
```

**Comment by jithu121212** [comment]
there was a missing of a pair of single quote in the page source.i
corrected it ,but then the error text and the background black color
disappeared.there is nothing in that place .it gone fruitlessly. :-(

**Comment by Kris-B** [comment]
Can you give me the URL to your page? Or at least the source code of  your page (not the PHP file)?

**Comment by jithu121212** [comment]
ya finally it works.hurray..
i replaced jquery.nanogallery.core.js by jquery.nanogallery.js thats it.
![screenshot from 2017-03-04 14-47-02](https://cloud.githubusercontent.com/assets/24386580/23577590/841c0b90-00e9-11e7-8653-8f4f7827fbee.png)

**Comment by Kris-B** [comment]
Great! Thanks for the update.

**Comment by jithu121212** [comment]
it show false icons on selecting a specific category of image

![screenshot from 2017-03-04 14-57-48](https://cloud.githubusercontent.com/assets/24386580/23577669/25a54bce-00eb-11e7-8b43-af04584a8c73.png)

**Comment by rashadarose** [comment]
hey im getting the error (nanogallery2: error: no image to process. [nanogallery2])
im running a node server

var express = require('express');
var app = express();
var bodyParser = require('body-parser');

app.use(bodyParser());
app.use('/', express.static(__dirname + '/src', {
    maxAge: '1h'
}));

app.listen(8081, function () {
    console.log('Port 8081');
});

Using the Example Index
`<html>
  <head>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1">

    

    <link href="https://unpkg.com/nanogallery2@2.0.0/dist/css/nanogallery2.min.css" rel="stylesheet" type="text/css">
   

  </head>
  <body>

    <h1>gallery made with nanogallery2</h1>

    <div id="nanogallery2" data-nanogallery2='{
        
        "userID":                    "149035168@N08",
        "kind":                      "flickr",
        "photoset":                  "72157675219521270",
        "thumbnailHeight":           200,
        "thumbnailWidth":            200,
        "galleryMosaic":             [
                                       { "w": 5, "h": 3, "c": 2, "r": 1 },
                                       { "w": 2, "h": 2, "c": 1, "r": 2 },
                                       { "w": 2, "h": 2, "c": 7, "r": 2 },
                                       { "w": 2, "h": 2, "c": 2, "r": 4 },
                                       { "w": 3, "h": 4, "c": 4, "r": 4 },
                                       { "w": 3, "h": 4, "c": 7, "r": 4 },
                                       { "w": 2, "h": 2, "c": 10, "r": 5 },
                                       { "w": 4, "h": 2, "c": 11, "r": 6 },
                                     ],
        "thumbnailGutterWidth":      0,
        "thumbnailGutterHeight":     0,
        "thumbnailBorderHorizontal": 5,
        "thumbnailBorderVertical":   5,
        "galleryMaxRows":            1,
        "galleryDisplayMode":        "rows",
        "galleryDisplayMode":        "pagination", 
        "thumbnailLabel":            { "display" : false }
      }'>
    </div>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
       <script type="text/javascript" src="https://unpkg.com/nanogallery2@2.0.0/dist/jquery.nanogallery2.min.js"></script>
  </body>
</html>`

 
![captu](https://user-images.githubusercontent.com/22104931/34529250-593536b0-f079-11e7-8860-6cf5dd20b703.PNG)

**Comment by Kris-B** [comment]
I don't understand your issue : the error comes from `jquery.nanogallery2.core.min.js` but you have included `jquery.nanogallery2.min.js`  in your page ...

**Comment by Kris-B** [comment]
`jquery.nanogallery2.core.min.js` can not access Flickr
please use `jquery.nanogallery2.min.js` instead
