### ISSUE TITLE
Read out EXIF / IPTC data with nanoPhotosProvider2 to show the date the photo was taken and also sort photos

### ISSUE THREAD

**Issue by toasti2000** [nanostudio-org/nanogallery2#164]
Hello,
is it possible to read out EXIF / IPTC data with nanoPhotosProvider2 to show for example the date when the photo was taken in the viewer?
A very cool function would also to be able to sort the photos depending on their date.
Many thanks!

**Comment by Kris-B** [comment]
this is not planned
