### ISSUE TITLE
Reverse filter logic

### ISSUE THREAD

**Issue by Taroxx** [nanostudio-org/nanogallery2#169]
Hi!
First, thank you for such a functional gallery.
I have one wish caused by one problem. When I use more then 3 filtering tags, Users have very big confusion with usability, because they want to click at one of tags and get the selected result now, but in fact they do not choose it, but turn it off. I can't find any solution from documentation to solve this problem. Can you help me with this?

**Comment by Kris-B** [comment]
Filtering has evolved since v3
Please check the documentation: https://nanogallery2.nanostudio.org/documentation.html#ngy2_navigation
