### ISSUE TITLE
it shows false icon on selecting an image to view

### ISSUE THREAD

**Issue by jithu121212** [nanostudio-org/nanogallery2#17]
![screenshot from 2017-03-04 14-57-48](https://cloud.githubusercontent.com/assets/24386580/23577694/f52b779c-00eb-11e7-821c-6c7db2c439f2.png)

**Comment by Kris-B** [comment]
Check that the CSS folder on your server has the same content as in the dist folder, including font, and that all the files can be accessed access from your browser

**Comment by jithu121212** [comment]
sir i owe you one.
![screenshot from 2017-03-04 15-20-21](https://cloud.githubusercontent.com/assets/24386580/23577776/26e4dede-00ee-11e7-8918-2d940117eb69.png)
