### ISSUE TITLE
Lazy Load effectiveness or bug?

### ISSUE THREAD

**Issue by gzmichael84** [nanostudio-org/nanogallery2#171]
Hello. I am using the normal installation of the script. Using Javascript. I install it on plain html.

My settings are thumbnailHeight:180,thumbnailWidth:'auto',galleryDisplayMode:'moreButton',galleryDisplayMoreStep:2

I have 70 photos on the gallery. On the browser it is visible 2 rows of photos as expected (visible 10 photos) and i have a button at the bottom to load more (as expected). At the network activity of the browser i see that all photos (70) loaded instead of just that that are visible. When i press to load more photos, again photos that appearing are downlaoded again. And if i press again more photos are download. The question is that why at 1st load all photos are downloaded at once? Shouldn't be loanloaded batch by batch. I try at your demo also the self stored method work like this. From flickr or by using the nanoPhotosProvider doesnt have this behavior. It works as expected. Is this a bug or its expected to load all photos at once and then load again if its the simple self hosted method where photos are loaded by js ?

**Comment by gzmichael84** [comment]
If i change the thumbnailWidth:'auto' to a number it works as expected. Not loadind all photos at once at the begining. Only these at 1st batch.

**Comment by Kris-B** [comment]
The justified layout (thumbnailWidth:'auto') needs to internaly build the whole gallery, and for this, the size of each thumbnail is required.
2 possibilities:
- the size is provided for each media's thumbnail and only the displayed thumbnails are downloaded
- if not, the script needs to download all thumbnails to retrieve their size

**Comment by gzmichael84** [comment]
Yes thats true i didnt provide the size of each image. After provide it it work as expected. Thank you.
