### ISSUE TITLE
Nanogp issue

### ISSUE THREAD

**Issue by Gigiojam** [nanostudio-org/nanogallery2#172]
Hi Kris and everyone.
I have problem in "grant authorization" step, when configuring nanogp: when open the authorize.php page: http://your_webserver/nanogp/authorize.php and choose the google account, i get 403 error from server. 
Attached, Log error in nanogp folder.
[error_log.txt](https://github.com/nanostudio-org/nanogallery2/files/2654104/error_log.txt)

**Comment by jjbertin** [comment]
J'ai résolu ce problème (semble-t-il), mais sur mon site j'ai désormais ce message sur ma page 
"nanogallery2: Could not retrieve Google data. Error: parsererror, Error: jQuery1102031313561503966936_1544552068385 was not called readyState=4"

**Comment by Kris-B** [comment]
@Gigiojam do you still have this issue ?

**Comment by Gigiojam** [comment]
Yes... I don´t know to solve this problem.

**Comment by Kris-B** [comment]
@Gigiojam does the folder `admin/users` exist ?

**Comment by Gigiojam** [comment]
> @Gigiojam does the folder `admin/users` exist ?

Yes, exist!

**Comment by Kris-B** [comment]
@jjbertin: development is not finished yet, I can not answer for now

**Comment by Kris-B** [comment]
@Gigiojam which files do you have in this folder ?

**Comment by Gigiojam** [comment]
@Kris-B , only readme.txt file.

**Comment by Kris-B** [comment]
@Gigiojam 

Did you follow each step from the documentation https://github.com/nanostudio-org/nanogp ?

**Comment by Gigiojam** [comment]
@Kris-B , Yep.. I think so!

**Comment by Kris-B** [comment]
actually, after the grant authorization section, somes files should have created in the admin/users folder

can you retry https://github.com/nanostudio-org/nanogp#grant-authorization

**Comment by Gigiojam** [comment]
I try again, but no success.
"Forbidden
You don't have permission to access /nanogp/authorize.php on this server."

The URL page of this message:
http://www.bandaomega3.com.br/nanogp/authorize.php?code=4/2wBuwxGIDWDs29FiwKx2oU-Cou8U3sypPkHtKIdHJbUblLKnJ5Opy7OWIrpYNdx4UYTErZwgYuqPEas1ciZ6qA8&scope=email%20profile%20https://picasaweb.google.com/data%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email

PS: The nanogp.php was updated.

**Comment by Kris-B** [comment]
please upgrade to 
- nanogp2 v2.0.1 - https://github.com/nanostudio-org/nanogp2
- nanogallery2 v2.4.0 - https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.4.0

**Comment by Gigiojam** [comment]
OK Kris. Thanks!

**Comment by Gigiojam** [comment]
I get error again.
![captured](https://user-images.githubusercontent.com/36645299/54308060-f2fe7f80-45ab-11e9-8d89-95d1288251de.jpg)

**Comment by Kris-B** [comment]
There's an issue in your Google Console API settings.
Please check the `Authorized redirect URIs`

**Comment by Kris-B** [comment]
I'm closing this issue as it's not directly related to nanogallery2.
You may open a new issue on the nanogp repository: https://github.com/nanostudio-org/nanogp2
