### ISSUE TITLE
Accéder à un album google photos

### ISSUE THREAD

**Issue by jjbertin** [nanostudio-org/nanogallery2#174]
Bonjour,
Lorsque sur mon site web je tente d'ouvrir un album chez google photos, la page affiche ce message :

nanogallery2: Could not retrieve Google data. Error: parsererror, Error: jQuery110202583757211390558_1544636299816 was not called readyState=4
getResponseHeader=function(e){var t;if(2===b){if(!c){c={};while(t=Tn.exec(a))c[t[1].toLowerCase()]=t[2]}t=c[e.toLowerCase()]}return null==t?null:t}
getAllResponseHeaders=function(){return 2===b?a:null}
setRequestHeader=function(e,t){var n=e.toLowerCase();return b||(e=v[n]=v[n]||e,y[e]=t),this}
overrideMimeType=function(e){return b||(p.mimeType=e),this}
statusCode=function(e){var t;if(e)if(2>b)for(t in e)m[t]=[m[t],e[t]];else C.always(e[C.status]);return this}
abort=function(e){var t=e||w;return u&&u.abort(t),k(0,t),this}
state=function(){return n}
always=function(){return i.done(arguments).fail(arguments),this}
then=function(){var e=arguments;return x.Deferred(function(n){x.each(t,function(t,o){var a=o[0],s=x.isFunction(e[t])&&e[t];i[o[1]](function(){var e=s&&s.apply(this,arguments);e&&x.isFunction(e.promise)?e.promise().done(n.resolve).fail(n.reject).progress(n.notify):n[a+"With"](this===r?n.promise():this,s?[e]:arguments)})}),e=null}).promise()}
promise=function(e){return null!=e?x.extend(e,r):r}
pipe=function(){var e=arguments;return x.Deferred(function(n){x.each(t,function(t,o){var a=o[0],s=x.isFunction(e[t])&&e[t];i[o[1]](function(){var e=s&&s.apply(this,arguments);e&&x.isFunction(e.promise)?e.promise().done(n.resolve).fail(n.reject).progress(n.notify):n[a+"With"](this===r?n.promise():this,s?[e]:arguments)})}),e=null}).promise()}
done=function(){if(l){var t=l.length;(function i(t){x.each(t,function(t,n){var r=x.type(n);"function"===r?e.unique&&p.has(n)||l.push(n):n&&n.length&&"string"!==r&&i(n)})})(arguments),n?o=l.length:r&&(s=t,c(r))}return this}
fail=function(){if(l){var t=l.length;(function i(t){x.each(t,function(t,n){var r=x.type(n);"function"===r?e.unique&&p.has(n)||l.push(n):n&&n.length&&"string"!==r&&i(n)})})(arguments),n?o=l.length:r&&(s=t,c(r))}return this}
progress=function(){if(l){var t=l.length;(function i(t){x.each(t,function(t,n){var r=x.type(n);"function"===r?e.unique&&p.has(n)||l.push(n):n&&n.length&&"string"!==r&&i(n)})})(arguments),n?o=l.length:r&&(s=t,c(r))}return this}
complete=function(){if(l){var t=l.length;(function i(t){x.each(t,function(t,n){var r=x.type(n);"function"===r?e.unique&&p.has(n)||l.push(n):n&&n.length&&"string"!==r&&i(n)})})(arguments),n?o=l.length:r&&(s=t,c(r))}return this}
success=function(){if(l){var t=l.length;(function i(t){x.each(t,function(t,n){var r=x.type(n);"function"===r?e.unique&&p.has(n)||l.push(n):n&&n.length&&"string"!==r&&i(n)})})(arguments),n?o=l.length:r&&(s=t,c(r))}return this}
error=function(){if(l){var t=l.length;(function i(t){x.each(t,function(t,n){var r=x.type(n);"function"===r?e.unique&&p.has(n)||l.push(n):n&&n.length&&"string"!==r&&i(n)})})(arguments),n?o=l.length:r&&(s=t,c(r))}return this}
status=200
statusText=success

URL:https://dev.chasse-autreches.xyz/nanogp/nanogp.php?nguserid=115318255461408862217&ngalbumid=6629979550107494929&alt=json&v=3&kind=photo&thumbsize=225u,225u,225u,225u,225u,225u,225u,225u,225u,225u&imgmax=d [nanogallery2gp]

Voici le code que j'ai entré sur ma page en HTML :
 
<div ID="nanogallery2gp" data-nanogallery2='{
    "kind":             "google2",
    "userID":           "115318255461408862217",
    "google2URL":       "https://dev.chasse-autreches.xyz/nanogp/nanogp.php",
	"album":			"6629979550107494929",
    "thumbnailHeight":  150,
    "thumbnailWidth":   150
  }'>      
</div>
Pouvez-vous m'aider, car je tourne en rond
D'avance merci
(L'adresse de ma page "http://dev.chasse-autreches.xyz/copie-z-modele-VUES-GP.htm")

**Comment by jjbertin** [comment]
Le code que j'ai entré sur ma page en HTML

<div ID="nanogallery2gp" data-nanogallery2='{
    "kind":             "google2",
    "userID":           "115318255461408862217",
    "google2URL":       "https://dev.chasse-autreches.xyz/nanogp/nanogp.php",
	"album":			"6629979550107494929",
    "thumbnailHeight":  150,
    "thumbnailWidth":   150
  }'>      
</div>
JJB

**Comment by jjbertin** [comment]
Je ne parviens pas à copier le code
<div ID="nanogallery2gp" data-nanogallery2='{
    "kind":             "google2",
    "userID":           "115318255461408862217",
    "google2URL":       "https://dev.chasse-autreches.xyz/nanogp/nanogp.php",
	"album":			"6629979550107494929",
    "thumbnailHeight":  150,
    "thumbnailWidth":   150
  }'>      
</div>

**Comment by jjbertin** [comment]
> Je ne parviens pas à copier le code
<div ID="nanogallery2gp" data-nanogallery2='{
    "kind":             "google2",
    "userID":           "115318255461408862217",
    "google2URL":       "https://dev.chasse-autreches.xyz/nanogp/nanogp.php",
	"album":			"6629979550107494929",
    "thumbnailHeight":  150,
    "thumbnailWidth":   150
  }'>      
</div>

**Comment by jjbertin** [comment]
Laissez tomber, j'ai trouvé.
Merci quand même !!

**Comment by Kris-B** [comment]
please upgrade to nanogp v1.3.1
https://github.com/nanostudio-org/nanogp/releases/tag/1.3.1
