### ISSUE TITLE
Does not interpret Flickr's HTML description

### ISSUE THREAD

**Issue by vishnumaiea** [nanostudio-org/nanogallery2#176]
When a photo from a Flickr photostream with HTML formatted description is viewed on a light box, the HTML is interpreted as just text than markup. Below is a screenshot of one of my photos (https://www.flickr.com/photos/vishnumaiea) viewed through the lightbox along with the label highlighted with red stroke,

![image](https://user-images.githubusercontent.com/10383395/49950836-947b2400-ff1e-11e8-9697-07fd5f77375b.png)

Nanogallery1 would show them correctly.

Also, there's no way to set the font size or font-family of the label text.

**Comment by Kris-B** [comment]
this is by design to avoid XSS vulnerability
you can change the behaviour with the `allowHTMLinData` parameter

**Comment by vishnumaiea** [comment]
Didn't know about this. My bad that I didn't read about it. Thanks :)

**Comment by Kris-B** [comment]
no problem ;-)
