### ISSUE TITLE
Self hosted justified layout and .nGY2GThumbnailImage class

### ISSUE THREAD

**Issue by BlackSailor** [nanostudio-org/nanogallery2#18]
I have my thumbs with **the same height** and auto width created, but I always have `.nGY2GThumbnailImage` styled as `width='300' height='200'` Result is blurred thumbs with the same size. Is it a bug or I have miss something?

**Comment by Kris-B** [comment]
Can you paste your code gère?

**Comment by Kris-B** [comment]
any update?
