### ISSUE TITLE
Lightbox - ability to rotate image

### ISSUE THREAD

**Issue by smeenz** [nanostudio-org/nanogallery2#180]
I would like the ability to be able to rotate images in lightbox.   I've tried to implement it myself using a customtoolbar element which rotates the image using CSS transform: rotate(), but the rotation gets destroyed as soon as the user scrolls (zooms) the image, because the CSS transform is overwritten,  I can't even do it by applying a second class to nGY2ViewerMedia, because the first class overwrites the other

To do this properly, at any point where the a transform style is applied to the lightbox image, the desired rotation would need to included in that transform. For example, instead of setting the <img> to "transform : translate(0px,0px)", it would need to set it to "transform : translate(0px,0px) rotate(##deg)" for whatever value of rotation is appropriate

**Comment by Kris-B** [comment]
new feature for the next release

you may try the beta version from the DEV branch: `https://github.com/nanostudio-org/nanogallery2/tree/dev`

**Comment by Kris-B** [comment]
@smeenz any feedback ?

**Comment by smeenz** [comment]
Sorry, I didn't see your update. Will test and advise.

**Comment by Kris-B** [comment]
@smeenz take your time ;-)

**Comment by Kris-B** [comment]
actually, this feature is already implemented in the demo on the homepage - https://nanogallery2.nanostudio.org/

**Comment by smeenz** [comment]
Just had a look at the demo. Perfect. Thanks.
