### ISSUE TITLE
Picasa API deprecated?

### ISSUE THREAD

**Issue by marcomoret** [nanostudio-org/nanogallery2#183]
Hi, but nano gallery2 on kind: google will work?
Sometimes I get this error:
The Picasa API is deprecated. See https://developers.google.com/picasa-web/ for more details and the migration guide.

I create something to  throw away next month?
thanks

**Comment by Kris-B** [comment]
you need to update nanogp to v1.3.1 - https://github.com/nanostudio-org/nanogp/releases/tag/1.3.1

the new Google Photo API will be used in a new released, which is planned before march 31

**Comment by jjbertin** [comment]
20/01/2018- Bonjour,
J'ai bien chargé la version v1.3.1 et remplacé chez l'hébergeur sur le répertoire nanogp le contenu du répertoire dist. J'ai bien inclus mes ID, mais j'ai toujours un message d'erreur lorsque je veux regarder un album sur mon site.
Que faire pour faire fonctionner de nouveau. D'avance, merci.
Mon site : http://prod.chasse-autreches.xyz/18-12-16-VUES-GP2.htm

**Comment by jjbertin** [comment]
20/01/2019
Petite précision, avant je pouvais me connecter à google photos depuis https://nanogallery2.nanostudio.org/builder.html#
mais désormais je n'ai plus d'accès. Je suppose que cela est lié à mon précédent message.
Merci de votre aide.

**Comment by Kris-B** [comment]
@jjbertin - il faut donner les autorisations nécessaires - merci de regarder le chapitre 'Grant authorization' sur https://github.com/nanostudio-org/nanogp

L'erreur sur builder a été corrigée

**Comment by Kris-B** [comment]
In order to continue to use Google Photos after the 15 march 2019, you'll have to use:
- nanogallery2 v2.4.0
Beta available here: https://github.com/nanostudio-org/nanogallery2/tree/dev
- nanogp2
Beta available here: https://github.com/nanostudio-org/nanogp2
Documentation is not fully finished, but the add-on is working.

Please note:
- album'IDs have changed
- there's an option for generating a list of albums (including their IDs) for one specific user

**Comment by Kris-B** [comment]
please upgrade to 
- nanogp2 v2.0.1 - https://github.com/nanostudio-org/nanogp2
- nanogallery2 v2.4.0 - https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.4.0

**Comment by Kris-B** [comment]
I'm closing this issue as it's not directly related to nanogallery2.
You may open a NEW issue on the nanogp repository: https://github.com/nanostudio-org/nanogp2
