### ISSUE TITLE
Load images before scroll?

### ISSUE THREAD

**Issue by sockofleas** [nanostudio-org/nanogallery2#184]
Currently I'm seeing images load on screen only after I've scrolled to an empty (white) portion of the screen. Is it possible to load these images before I scroll to an empty area? See my site for reference: [photography.adamcircle.com](https://photography.adamcircle.com).

**Comment by Kris-B** [comment]
you may change the value of `eventsDebounceDelay`

**Comment by Kris-B** [comment]
https://nanogallery2.nanostudio.org/documentation.html#ngy2_global

**Comment by Kris-B** [comment]
@sockofleas  any update ?
