### ISSUE TITLE
Google Fotos

### ISSUE THREAD

**Issue by brandstoretirol** [nanostudio-org/nanogallery2#186]
Hi,
are there any problems with the google API?
Theres no album list in the builder an errors on my website 
(nanogallery2: Could not retrieve Google data. Error: Token revoked - )

please help
thx tom

**Comment by Kris-B** [comment]
hi tom
builder has been fixed, thanks for the notification

**Comment by brandstoretirol** [comment]
thx Kris

**Comment by Kris-B** [comment]
please upgrade to 
- nanogp2 v2.0.1 - https://github.com/nanostudio-org/nanogp2
- nanogallery2 v2.4.0 - https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.4.0

**Comment by Kris-B** [comment]
I'm closing this issue as it's not directly related to nanogallery2.
You may open a NEW issue on the nanogp repository: https://github.com/nanostudio-org/nanogp2
