### ISSUE TITLE
Google et nanogp

### ISSUE THREAD

**Issue by jjbertin** [nanostudio-org/nanogallery2#188]
Bonjour,
google vient ENCORE de changer ses règles d'autorisations. Mes albums photos ne sont plus visibles sur mon site, et je suis perdu dans cette jungle pour accéder de nouveau à mes photos.
Adresse de mon site : http://prod.chasse-autreches.xyz/19-01-13-VUES-GP2.htm

**Comment by jjbertin** [comment]
Bonjour,
J'ai bien chargé la version nanogp V1.3.1, mais je ne sais pas quoi faire avec "deprecation-extension=true".
Quelqu'un peut-il m'aider, car mes albums sont invisibles actuellement.
D'avance, merci.

**Comment by Kris-B** [comment]
#183
