### ISSUE TITLE
Nanogallery2 portable

### ISSUE THREAD

**Issue by CGuyDesigns** [nanostudio-org/nanogallery2#189]
Good Afternoon,

I have updated my site to the portable gallery since the other doesn't work and after following the steps I see this error.

Can you please assist? 

Website: http://www.allianceforaction.com/events-photo-gallery.php

Thanking you.

**Comment by Kris-B** [comment]
nanogp is still working, you must update to v1.3.1 https://github.com/nanostudio-org/nanogp/releases/tag/1.3.1

**Comment by CGuyDesigns** [comment]
i started all over with the files sent and i receive the same message.

Not sure what is happening here.

http://www.allianceforaction.com/events-photo-gallery.php

**Comment by CGuyDesigns** [comment]
Good Afternoon,

Hoping to hear from you soon.

I have removed all files and replaced with new ones and started all over again today; i now get the following message below:

nanogallery2: Could not retrieve Google data. Error: parsererror, Error: jQuery33108383024343542342_1549389912869 was not called readyState=4
getResponseHeader=function(e){var t;if(c){if(!s){s={};while(t=Ot.exec(a))s[t[1].toLowerCase()]=t[2]}t=s[e.toLowerCase()]}return null==t?null:t}
getAllResponseHeaders=function(){return c?a:null}
setRequestHeader=function(e,t){return null==c&&(e=T[e.toLowerCase()]=T[e.toLowerCase()]||e,b[e]=t),this}
overrideMimeType=function(e){return null==c&&(h.mimeType=e),this}
statusCode=function(e){var t;if(e)if(c)E.always(e[E.status]);else for(t in e)x[t]=[x[t],e[t]];return this}
abort=function(e){var t=e||C;return i&&i.abort(t),k(0,t),this}
state=function(){return r}
always=function(){return o.done(arguments).fail(arguments),this}
catch=function(e){return i.then(null,e)}
pipe=function(){var e=arguments;return w.Deferred(function(t){w.each(n,function(n,r){var i=g(e[r[4]])&&e[r[4]];o[r[1]](function(){var e=i&&i.apply(this,arguments);e&&g(e.promise)?e.promise().progress(t.notify).done(t.resolve).fail(t.reject):t[r[0]+"With"](this,i?[e]:arguments)})}),e=null}).promise()}
then=function(t,r,i){var o=0;function a(t,n,r,i){return function(){var s=this,u=arguments,l=function(){var e,l;if(!(t=o&&(r!==W&&(s=void 0,u=[e]),n.rejectWith(s,u))}};t?c():(w.Deferred.getStackHook&&(c.stackTrace=w.Deferred.getStackHook()),e.setTimeout(c))}}return w.Deferred(function(e){n[0][3].add(a(0,e,g(i)?i:I,e.notifyWith)),n[1][3].add(a(0,e,g(t)?t:I)),n[2][3].add(a(0,e,g(r)?r:W))}).promise()}
promise=function(e){return null!=e?w.extend(e,i):i}
progress=function(){return o&&(n&&!t&&(s=o.length-1,a.push(n)),function t(n){w.each(n,function(n,r){g(r)?e.unique&&l.has(r)||o.push(r):r&&r.length&&"string"!==x(r)&&t(r)})}(arguments),n&&!t&&u()),this}
done=function(){return o&&(n&&!t&&(s=o.length-1,a.push(n)),function t(n){w.each(n,function(n,r){g(r)?e.unique&&l.has(r)||o.push(r):r&&r.length&&"string"!==x(r)&&t(r)})}(arguments),n&&!t&&u()),this}
fail=function(){return o&&(n&&!t&&(s=o.length-1,a.push(n)),function t(n){w.each(n,function(n,r){g(r)?e.unique&&l.has(r)||o.push(r):r&&r.length&&"string"!==x(r)&&t(r)})}(arguments),n&&!t&&u()),this}
responseText=
status=200
statusText=OK

What am i missing here?

**Comment by Kris-B** [comment]
Did you follow the instruction for manually revoking authorization ?
https://github.com/nanostudio-org/nanogp#manually-revoke-authorization

**Comment by Kris-B** [comment]
please upgrade to 
- nanogp2 v2.0.1 - https://github.com/nanostudio-org/nanogp2
- nanogallery2 v2.4.0 - https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.4.0

**Comment by Kris-B** [comment]
Please note that package for v2.4.0 was corrupted - please use v2.4.1

**Comment by Kris-B** [comment]
I'm closing this issue as it's not directly related to nanogallery2.
You may open a new issue on the nanogp repository: https://github.com/nanostudio-org/nanogp2
