### ISSUE TITLE
Repeat calls to nanoGallery() don't update the gallery

### ISSUE THREAD

**Issue by d4rken** [nanostudio-org/nanogallery2#19]
I'm loading images dynamically from Firebase and due to the async nature of this I want to display images as they become available.

I thought I could just call nanoGallery() on my `div` again each time, but then not all images are visible.

Currently I'm just doing it after the last image was loaded, but this causes a long delay until the user sees something on the website.

https://github.com/d4rken/rollkuchen/blob/master/web/public/index.html#L60

Is this an issue with nanogallery or an issue with my code? (I'm quite new to webdev)

Maybe somekind of threading/race condition issue?

**Comment by Kris-B** [comment]
You can check this example: http://codepen.io/Kris-B/pen/wJKowg

**Comment by d4rken** [comment]
Thank you very much, this seems to work, I was unaware of the 'refresh' keyword.

In every example nanoGallery is initiated with existing data, how can i start with can empty gallery?

**Comment by d4rken** [comment]
Just it being empty makes it show an "empty gallery error".
It seems to work if init it with `items: []`. When I later add the items i get:
```
Uncaught (in promise) TypeError: Cannot read property 'albumID' of undefined
  GalleryNavigationBar	
  GalleryRender	
  Refresh	
  jQuery.fn.nanogallery2	
  Promise.all.then.values	
```
but the images show correctly.

**Comment by Kris-B** [comment]
You're right, empty galleries are not supported at this time.
I'll add it to the todo list.

**Comment by d4rken** [comment]
Would be a cool addition. Thanks for the help.
