### ISSUE TITLE
Nanogallery2 with nanophotoprovider2 and Fancybox3

### ISSUE THREAD

**Issue by Hobby001** [nanostudio-org/nanogallery2#190]
How do I pass images and related data from nanophotoprovider2 to Fancybox3 ?

Thanks

**Comment by Kris-B** [comment]
nanophotoprovider2 has been designed to provide data to nanogallery2.
Now, if you want to provide data directly to fancybox3, you may look at the fancybox3 documentation to see how to implement it.
