### ISSUE TITLE
Flickr Collection

### ISSUE THREAD

**Issue by Rushdiey** [nanostudio-org/nanogallery2#193]
Im using this coding for flickr albums
<div id="nanogallery2" data-nanogallery2='{
        "kind":            "flickr",
        "userID":          "MYID",
        "thumbnailHeight": 550, "thumbnailWidth": 550
      }'>
    </div>

Now i want to show the photo from flickr collection instead album. What i should add to work?

**Comment by Kris-B** [comment]
collections are not supported because access via Flickr's API can not be anonymous
