### ISSUE TITLE
DropdownMenu Bug

### ISSUE THREAD

**Issue by Rushdiey** [nanostudio-org/nanogallery2#194]
I dont know its a bug or my coding,
When i use dropdown to show image, it sometimes will display image and sometimes not,

When use onclick function it always works, i just wonder why i cant use dropdown menu

**Comment by Kris-B** [comment]
I'm not sure to fully understand your issue... can you share an URL where this issue can be reproduced ?

**Comment by Rushdiey** [comment]
Im using onclick
https://rhbf.penumbracommunications.com/gallery.html

**Comment by Rushdiey** [comment]
If u can see now, if i click the image wont show. i need to scroll down a bit

**Comment by Kris-B** [comment]
jquery is included 3 times in your page - please remove 2

**Comment by Kris-B** [comment]
I'm closing this issue for now, let me know if you need more help.
