### ISSUE TITLE
nanogp2

### ISSUE THREAD

**Issue by brandstoretirol** [nanostudio-org/nanogallery2#195]
Hi,

I've done the points under "https://github.com/nanostudio-org/nanogp2#arrow_forward-installation", but the Pics from the Google Gallery are not visible.

Where can i buy **nanogallery2 v2.4.O**
I think, thats the Problem

thx
tom

**Comment by sintech** [comment]
I have done the same steps described in https://github.com/nanostudio-org/nanogp2/blob/master/README.md
I have sucesfully received albums list in 'google_photos_data.txt', but i cant display any album on my site.
I used css and js from dev branch of nanogallery2.
My div example:
`div id="nanogallery2" data-nanogallery2='{
    "kind":             "google2",
    "userID":           "1176XXXXXXXXXXX4636",
    "google2URL":       "http://site/gallery/nanogp2/nanogp2.php",
    "album": 'AB4aXXXXXXXXXXXXYBC8',
    "thumbnailHeight":  150,
    "thumbnailWidth":   150
  }'>
</div>`

**Comment by brandstoretirol** [comment]
i have also the google_photos_data.txt

**Comment by Kris-B** [comment]
@brandstoretirol v2.4.0 beta is available in the DEV branch: https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by Kris-B** [comment]
@sintech can you share the URL of your page with the issue ?

**Comment by sintech** [comment]
@Kris-B, I screwed it up with quotes a little bit (in `album`). 
Now it works as it should be.
Thanks.

**Comment by Kris-B** [comment]
@sintech  thanks for the update !

**Comment by Kris-B** [comment]
v2.4.0 is released - https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.4.0

**Comment by Kris-B** [comment]
Please note that package for v2.4.0 was corrupted - please use v2.4.1

**Comment by brandstoretirol** [comment]
thank you very much.. i'll try

**Comment by brandstoretirol** [comment]
Hi Kris,
is there a manual for the update prozedure?
thx best tom

**Comment by Kris-B** [comment]
how do you include nanogallery2's files in your page ?

**Comment by brandstoretirol** [comment]
Hi Kris,
i've made the update, but the new google gallery don't work :(
i've copied the new files on "assets\nano-gallery"

please help
thx tom

**Comment by brandstoretirol** [comment]
HI Kris,
the are no pics loaded but also not an error message
(https://www.brandstore.tirol/shop) 
any idea?
thx tom

**Comment by brandstoretirol** [comment]
![image](https://user-images.githubusercontent.com/38783363/54481205-fa36bf00-4831-11e9-9b8c-55611c4441cd.png)

![image](https://user-images.githubusercontent.com/38783363/54481215-189cba80-4832-11e9-8a2d-2f5857da2e69.png)

Hi Kris, any idea?
thx tom

**Comment by brandstoretirol** [comment]
it works! thx
