### ISSUE TITLE
How to append custom data and access it with shopping cart

### ISSUE THREAD

**Issue by kevinmamaqi** [nanostudio-org/nanogallery2#196]
I am trying to append a custom data tag and log it afterwards via jQuery.

The HTML looks like this:

```
<a
	href="myurl_big.jpg"
	data-customData='{ "photoID": myphotoID}'
	data-ngThumb="myurl.jpg"
>
```

I'm trying to log it into the console via:

```
$("#my_nanogallery2").on( 'shoppingCartUpdated.nanogallery2', function(e) {
	console.log(e.customData); // I know it wont work, but I don't know what else to write for the example.
});
```

**Comment by Kris-B** [comment]
since v2.4, the callback function will also get  the item, which contains your custom data.

https://codepen.io/Kris-B/pen/NbEWbe
