### ISSUE TITLE
No images loading when attempting to dynamically create a gallery

### ISSUE THREAD

**Issue by Oxboll19** [nanostudio-org/nanogallery2#197]
Hi,

I'm attempting to create a gallery using ajax. I have a folder of images and a txt file with the names of the images in it. I am getting all the files names from the txt file and then attempting to create a gallery using those file names. However whenever I load my web page I get an error message that says:

"nanogallery2: error: no media to process. [my_nanogallery2]"

The code I am using to load the images is:

```javascript
    $.get(dir + "images.txt", function(data){
        var fileNames = data.split(",");
        var images = [];

        for(let i = 0; i < fileNames.length - 1; i++){
            var name = fileNames[i].replace(/(\r\n|\n|\r)/gm, "");
            var friendlyName = name.replace(/_/g, " ");

            var obj = {
                src: dir + name,
                srct: dir + name,
                title: friendlyName,
                description: ""
            }

            images.push(obj);
        }

        $('#my_nanogallery2').nanogallery2({
            items: images,
            thumbnailWidth: 'auto',
            thumbnailHeight: 200,
            locationHash: false
        });
    })
```

and the HTML for the gallery looks like this:

```html
    <main class="container" onload="loadImages">
        <div id="my_nanogallery2" data-nanogallery2>

        </div>
    </main> 
```

Am I doing something wrong here?

Thanks.

**Comment by Oxboll19** [comment]
Managed to fix this. Issue was being caused by the empty data-nanogallery2 attribute in the gallery div.

**Comment by Kris-B** [comment]
thanks for the update!
