### ISSUE TITLE
Switching between multiple galleries on one page

### ISSUE THREAD

**Issue by whollaus** [nanostudio-org/nanogallery2#198]
I have multiple galleries on one page. In fullscreen mode you go back to the beginning at the end of the first gallery. Same in gallery two. 

Is it possible to switch from the end of the first gallery to the start image of the second gallery?

If not at the moment, this would be a great new feature :)

Thanks a lot!

**Comment by Kris-B** [comment]
Galleries are independant of each other, implementing this feature would have too much impacts on the code.
