### ISSUE TITLE
thumbnailSelectable issue

### ISSUE THREAD

**Issue by macsupport** [nanostudio-org/nanogallery2#20]
If one enables ````thumbnailSelectable: true```` , the Select icon is toggled if the entire image or album image is clicked , not just when the icon itself is clicked, even though the icon toggles to a checkbox. If ones first selects the image and then clicks to see the lightbox, the nGY2GThumbnailIconImageSelect icon is toggled off instead of the lightbox opening, so you have to click twice and then your image is now unselected. One expects the GUI to work like the other thumbnail icons. Clicking on share opens the share dialog, clicking on download, downloads the image, etc. so shouldn't clicking the select icon just toggle the icon and not disable the lightbox? It seems that clicking on the image should not toggle the select icon, only clicking the icon itself.
I want to be able to use the select icon so users can toggle  images as "favorites" and still be able to open the lightbox, which is not possible. Thanks

**Comment by Kris-B** [comment]
Some details:
- if no thumbnail is selected, the select icon is toggled when the user clicks on it
- if at least one thumbnail is selected, the user can click anywhere on the thumbnail to swicth the select status.

This behaviour is already implemented in nanoGALLERY (and many other web applications).
But you're right: it's no more possible to display the image when selection mode is activated. I'll add a new thumbnail icon for this.

For your use case: the user could also directly click on a "favorite" icon on the thumbnail to enable/disable it.
Here's an example: https://codepen.io/Kris-B/pen/RpWKMJ

**Comment by macsupport** [comment]
Thanks for the demo. One thing I can't determine, is how to add ````customData: { favorite: false}```` if one is using markup rather than javascript? Does one use a data attribute? I can't find any documentation on this.

**Comment by Kris-B** [comment]
you can use this syntax:
`<a href="berlin3.jpg" data-ngthumb="berlin2t.jpg" data-customData='{ "favorite": false}'>Berlin 3</a>`

and here's an example: https://codepen.io/Kris-B/pen/jBYYeo

**Comment by Kris-B** [comment]
FIY, a thumbnail tool (`display`) is now available to display an image even if in selection mode
