### ISSUE TITLE
How to set the image size( or height or width) in lightbox

### ISSUE THREAD

**Issue by stormtide11** [nanostudio-org/nanogallery2#202]
Hi, Thank you very much for the great gallery. 
I try to use Nanogallery in my project. 
Now one of the our users requirement is the default responsive lightbox image is too large(full height). 
So is it a way to set the image height or width in the lightbox?  I don't see some hint in the document. 
Thanks in advance.

**Comment by Zohaad97** [comment]
@stormtide11 the normal behaviour is responsive in the lightbox. However if you are still facing any issues, please create a [Fiddle](https://jsfiddle.net/). So I will help you out with your code.

**Comment by Kris-B** [comment]
No update so I'm closing this issue for now
