### ISSUE TITLE
Curl error400

### ISSUE THREAD

**Issue by bkring** [nanostudio-org/nanogallery2#203]
Hello,

I am getting the following error on my site. I had been working for the last few months but now is not.

nanogallery2: Could not retrieve Google data. Error: curl error400 - - https://picasaweb.google.com/data/feed/api/user/.....  [MelroseWebsiteGallery]

I am not sure where to start in fixing this.

thanks,

**Comment by Kris-B** [comment]
please update nanogp to the new version nanogp2 - https://github.com/nanostudio-org/nanogp2

**Comment by bkring** [comment]
Thanks, That got it working. The hardest part was finding the Google Album ID. Google does not make these things easy. There must be a better way but to find it I removed the old album id from my html and then loaded the page. The closed album then appeared on the page in my browser and I was able to get it from the url. anyway. thanks again

**Comment by Kris-B** [comment]
for the album's IDs, you can generate a report on your server: https://github.com/nanostudio-org/nanogp2#arrow_forward-retrieve-one-users-list-of-albums
