### ISSUE TITLE
"thumbnailWidth": "100%", "thumbnailHeight": "100%",

### ISSUE THREAD

**Issue by ProsperoDead** [nanostudio-org/nanogallery2#204]
Hi, thanks for the gallery, really like it.
Tell me how to do
"thumbnailWidth": "100%",
"thumbnailHeight": "100%",
Thus, the image must fill the entire container. Sorry for my English(

**Comment by ProsperoDead** [comment]
when I put 100%, it displays 100px

**Comment by Kris-B** [comment]
you can set the value 100% only to 1 size (thumbnailWidth <b>OR</b> thumbnailWidth)

**Comment by ProsperoDead** [comment]
![369852147 — копия](https://user-images.githubusercontent.com/40237322/55420427-b0fba480-557f-11e9-9d7d-4eadfa9504c4.png)

I put 100% only in width

<div id="ngy2p" data-nanogallery2='{
        "itemsBaseURL": "/images/portfolio/Portrait/",
        "thumbnailWidth":  "100%", 
        "thumbnailHeight":  "250",
        "thumbnailAlignment": "center"
      }'>
	   
      <a href="5DM33213.jpg" data-ngthumb="5DM33213.jpg" class="col-4 col-12-mobile" data-ngdesc=""></a>
      
    </div>

**Comment by ProsperoDead** [comment]
![369852147 — копия](https://user-images.githubusercontent.com/40237322/55420905-b9081400-5580-11e9-80d4-1046dddc86e6.png)

**Comment by Kris-B** [comment]
Don't set any class, the layout is managed by nanogallery2, not by bootstrap

**Comment by Kris-B** [comment]
any update ?

**Comment by ProsperoDead** [comment]
what am I doing wrong?
![1111111111111111111](https://user-images.githubusercontent.com/40237322/55870804-0c3a2200-5b92-11e9-9496-d574e6625057.png)
![2222222222222222](https://user-images.githubusercontent.com/40237322/55870814-10663f80-5b92-11e9-9cbe-4448c0224739.PNG)

**Comment by ProsperoDead** [comment]
I put 100%, get 100px

**Comment by Kris-B** [comment]
are you still using 100% for both sizes ?

**Comment by ProsperoDead** [comment]
only width 100%

**Comment by Kris-B** [comment]
Please provide the full settings of your gallery.
The URL of a page with your issue would be very helpful.

**Comment by ProsperoDead** [comment]
http://emalahov.ru/The-Descent-of-the-Holy-Spirit

**Comment by Kris-B** [comment]
with these settings:
```
"thumbnailWidth":  "auto XS370 SM211 ME231 LA290 XL437",
"thumbnailHeight":  "auto XS300 SM200 ME231 LA200 XL350",
```
you'll always have a fixed value. 
The value auto is your default size, but it will be ignored as you defined a fixed value in px for each possible screen size.

**Comment by ProsperoDead** [comment]
these options are not used for the first gallery

**Comment by Kris-B** [comment]
your settings for the first gallery:
```
"thumbnailWidth": "80",
"thumbnailHeight": "100",
```
You don't use the value `auto`, the size is also fixed, in pixels. Where's the issue?

**Comment by Kris-B** [comment]
PS: previous comment may be incorrect. You can set a value in pixel or the value auto. 100% will also be converted to 100px.

**Comment by ProsperoDead** [comment]
how can it be set in%? so it does not convert to px

**Comment by Kris-B** [comment]
you cannot: the width/height is:
- fixed in px,
- or, if value `auto` is used, it is calculated by nanogallery2.

**Comment by ProsperoDead** [comment]
that's what I wanted to understand

**Comment by Kris-B** [comment]
ok, sorry for misunderstanding...
