### ISSUE TITLE
Google photos pairing fails, indefinite load

### ISSUE THREAD

**Issue by sockofleas** [nanostudio-org/nanogallery2#205]
Just finished installation of nanogp2 and nanogallery2. Nanogallery2 loads for a long time and then presumably times out. No photos are ever displayed.

Error from the console:
`Uncaught TypeError: Cannot read property 'openSearch$startIndex' of undefined
    at Object.success (jquery.nanogallery2.min.js:58)
    at i (jquery-3.2.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.2.1.min.js:2)
    at A (jquery-3.2.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-3.2.1.min.js:4)`

As an additional note, how do I create a .htaccess file to cut access to the admin folder?

**Comment by Kris-B** [comment]
Please check all the settings, especially the settings in the google console.

I"m closing this issue for now. If you still have difficulties, please open a new on the nanogp2 project page: https://github.com/nanostudio-org/nanogp2
