### ISSUE TITLE
Refresh or Reload using the data-nanogallery2 inline options

### ISSUE THREAD

**Issue by DioVayne** [nanostudio-org/nanogallery2#206]
I'm loading my albums using the html inline options (data-nanogallery2 ='{"options":"here"}'). This works fine but after an ajax reload of the album the options won't load. I tried using the $('#albumid').nanogallery2('refresh') method and even the $('#albumid').nanogallery2('reload') but the options are ignored. Even calling location.reload() doesn't work. Only a hard refresh of the page reloads the options.
Am I doing something horribly wrong or is it just a missing feature?

**Comment by Kris-B** [comment]
What do you mean with ajax load ?

**Comment by DioVayne** [comment]
The album is reloaded inside the page through a jquery ajax load.

**Comment by Kris-B** [comment]
sorry but I need much more details to understand your issue

**Comment by Kris-B** [comment]
any update ?
