### ISSUE TITLE
How to center albums/thumbnials when the width is "auto"?

### ISSUE THREAD

**Issue by ies25** [nanostudio-org/nanogallery2#207]
when my thumbnails have set widths and heights, they will be centered on my page, however, when trying to achieve a justified layout, I am unable to center the thumbnails, even when making the thumbnail alignment 'center'

**Comment by Kris-B** [comment]
The parameter `thumbnailAlignment ` can not be applied to justified layout. This is by design as it makes no sense: with this layout, the full available width of it's container is used.
