### ISSUE TITLE
A few problems and wishes...

### ISSUE THREAD

**Issue by Epexa** [nanostudio-org/nanogallery2#21]
Hello!

Thank you very much for your library!

This is the best solution of all existing! (I conducted a study.)

But I had a few problems:
1. Options "**background**" and "**borderColor**" in "**colorScheme.thumbnail**" does not work.
My temporary solution:
```
#nanogallery2.nGY2 .nGY2GThumbnail {
	background-color: #fff;
}
```
2. If use data source self hosted when the page is scrolled up or down, thumbnails disappear and are re-draw _(.nGY2GThumbnail display: none and display: block)_. If set value "0" in options "**thumbnailDisplayInterval**" and "**thumbnailDisplayTransitionDuration**" then it does not help.
Please see [this video](https://drive.google.com/file/d/0B30YAoM7dAaeVml4emVsbjRVTFU/view).
I think if use data source self hosted then it's not necessary.
3. Option "**galleryLastRowFull**" does not work. Please see my example.

[My example.](http://sheveleva.by/nanogallery2.html)

My wishes:
1. Add the ability to create a **language file**. For translate all button, modal window "Share to".
2. Add the ability to add a button to **another social network in share**. Example "VK.com".
3. Add in the ability to **remove parameters** "ID" and "gallery_id" (if gallery_id = 0) **from share link**.
Example link: http://example.com/nanogallery2.html#nanogallery/nanogallery2/0/3
Would be better: http://example.com/nanogallery2.html#nanogallery/3
4. Make **separate js files plugins of data sources**.
Example:
```
jquery.nanogallery2.core.min.js
jquery.nanogallery2.google.min.js
jquery.nanogallery2.flickr.min.js
jquery.nanogallery2.local.min.js
```

Thanks!

**Comment by Kris-B** [comment]
Hi, and thanks for your feedback!

Your problems:
1. I need to check this
2. This is by design. Thumbnails are hidden for performance purposes. If you want, I could add an option to disable/enable this if the gallery has more than a certain amount of thumbnails.
3. This is a bug, i'll fix it

To your wishes:
1. Ok
2. Ok
3. The problem with an URL like  `http://example.com/nanogallery2.html#nanogallery/3`, is how to make the difference between an album or an image. By design, `.../#nanogallery/3` is a link to an album, not an image.
I doubt that users make any difference between the 2 syntaxes.
4. OK, but what is `jquery.nanogallery2.local.min.js` ?

**Comment by Epexa** [comment]
@Kris-B Hello! You are welcome!

About problems:
2. Understand about performance, yes please add option!

About wishes:
3. I think if use only one album, then no need "0" value in url.
4. I mean "local" - data source self hosted.

Thank you very much for your help!

**Comment by smitrens** [comment]
Hi, I found this bug:

 viewerToolbar.autoMinimize on default 800 does the opposite of what you're saying. 

Breakpoint for switching between minimized and standard toolbar.
If the width is lower than this value, the toolbar is switched to minimized.

-> If the width is higher than the value it switches to a minimized toolbar. I don't think this is what you wanted to do. Glad to help! Awesome gallery!

**Comment by Kris-B** [comment]
@Epexa 
You have only one album, but other people can have several. The hash handling needs to be the same for all use cases.
I'll add following files in the dest folder:
```
jquery.nanogallery2.core.min.js
jquery.nanogallery2.google.min.js
jquery.nanogallery2.flickr.min.js
```
Local will remain in core as it is very small.
Thanks for your proposals!

**Comment by Kris-B** [comment]
@smitrens 

Yes, I changed a little bit the usage ;-)

**Comment by Kris-B** [comment]
@Epexa 
`Options "background" and "borderColor" in "colorScheme.thumbnail" does not work.` -> I could not see any issue here.
Can you give me more details?

**Comment by smitrens** [comment]
@Kris-B 

When do you update the code here on github? Can I get it already somewhere else?

Thanks in advance.

**Comment by Epexa** [comment]
@Kris-B Understand! Thanks!
About ```background``` and ```borderColor``` options please see [my example](http://sheveleva.by/nanogallery2.html). I set red color, but does not work...

**Comment by Kris-B** [comment]
@smitrens 
The code is update when a new release is ready ;-)

**Comment by Kris-B** [comment]
@Epexa 
The background is not visible in your example.
Thumbnail background is behind the image, and is, for example, visible in grid layout when images are not cropped.

**Comment by Epexa** [comment]
@Kris-B Ok!
But how change border color in thumbnails?
![nanogallery2](https://cloud.githubusercontent.com/assets/2198826/24058641/f05424be-0b5c-11e7-934c-fc7fc89b24cc.png)

My temporary solution:
```
#nanogallery2.nGY2 .nGY2GThumbnail {
	background-color: #fff;
}
```
Can this be done through options?

**Comment by Kris-B** [comment]
@Epexa 
Your border color definition is correct. But the `<link rel='stylesheet' id='nanogallery2_css-css'  href='http://www.sheveleva.by/wp-content/themes/florence/nanogallery2/nanogallery2.min.css?ver=4.7.3' type='text/css' media='all' />
		<style>` should be in the HEAD of the page

**Comment by Kris-B** [comment]
@smitrens - code update with v1.2.0

**Comment by Epexa** [comment]
@Kris-B Thanks for help and update!
> 3. Option "galleryLastRowFull" does not work. Please see my example.

> This is a bug, i'll fix it

When can you fix it?

**Comment by Kris-B** [comment]
@Epexa 
will be fixed in the next release

**Comment by Kris-B** [comment]
@Epexa 
v1.2.1 just released - https://github.com/nanostudio-org/nanogallery2/releases/tag/v1.2.1

**Comment by Epexa** [comment]
@Kris-B Thank you!

_galleryLastRowFull option good work!_

You can in the future add social network [VK.com](https://vk.com/dev/Share) in "Share to"?

_Do you think it is possible to reduce the size of the library? 200kb it's a lot. Example maybe separate TinyColor library. Or to allocate some functions also to individual libraries. Such as albums, different types of galleries (grid, justified, cascading), effects, etc. Or do not use the code in native javascript, but use only the jQuery 3 functions._

**Comment by Kris-B** [comment]
I'll add VK.com

It's difficult to reduce the size of the library. Externalizing embed script will not bring anything as they are mandatory. Focusing on jQuery 3 would bring many compatibility issues with some CMS.
nanogallery2 has a width range of features. To split in, it would be necessary to create many separate files, which is difficult to maintain and to understand by novices.
I'll try to optimize the code to reduce its size, but the gain will be minimal...

**Comment by Epexa** [comment]
@Kris-B Thank you for VK.com!

Ok, let's forget about jQuery 3.
_Maybe you can not use native javascript, use only jQuery (1.7.1+). I have seen in the source code of some of the functions that are written in native javascript, but can be written to the jQuery. I think it would reduce the size of the library._
> nanogallery2 has a width range of features. To split in, it would be necessary to create many separate files, which is difficult to maintain and to understand by novices.

I think it's a good idea to split the functionality.
``jquery.nanogallery2.min.js`` - full default library (for non-advanced users);
And for advanced users now:
``jquery.nanogallery2.core.min.js`` - not a full library without flickr & google data source.
Maybe can split ``jquery.nanogallery2.core.min.js`` ?
Example:
``jquery.nanogallery2.core.min.js`` - not a full library without flickr & google data source
and more features:
``jquery.nanogallery2.core.grid.min.js`` - grid layout.
``jquery.nanogallery2.core.cascading.min.js`` - cascading layout.
``jquery.nanogallery2.core.effects.min.js`` - effects features.
``jquery.nanogallery2.core.navigation.min.js`` - navigation/filters features.
``jquery.nanogallery2.core.events.min.js`` - events features.
And in such a case maybe, instead of 199kb the necessary components would weigh 100kb...

Great libraries have builder components, example [Bootstrap](http://getbootstrap.com/customize/), [jQuery UI](https://jqueryui.com/download/), etc.

**Comment by Kris-B** [comment]
This is a library to display image galleries. I'm not sure that some bytes less will be noticeable compared to all the images/thumbnails to download...

But I may be wrong: you're free to split the code and make a PR so everyone can enjoy the benefits. I'll be happy to help you if you need some support.

**Comment by Epexa** [comment]
@Kris-B I will not do this, but thanks anyway!

**Comment by AdrianMos** [comment]
I've been trying out nanogallery2 (v.2.4.2) and found the same behavior as [here](https://github.com/nanostudio-org/nanogallery2/issues/21#issuecomment-287443522), I was unable to change the thumbnail border color. 

The editor has changed the encoding of my template file. It was tough to figure it out because all the other functionalities worked ok.
