### ISSUE TITLE
srct : base64 encode data not display

### ISSUE THREAD

**Issue by hoonguy** [nanostudio-org/nanogallery2#214]
Hi,
I have problem to display the thumbnail with Item object as below :
items : [ 
  src: "data:image/jpg;base64,/9j/4AAQSkZJRgABAQEASABIAAD.../",
  srct: "data:image/jpg;base64,/9j/4AAQSkZJRgABAQEASABIAAD.../" 
]

src has good display by clicking thumbnail but thumbnail image couldn't be displayed.
Thumbnail image box has just black like the not found.
I got the same result with width and height value.

**Comment by Kris-B** [comment]
not supported....

**Comment by MoroccanGeek** [comment]
is base64 is not supported anymore ? because i'm trying to use it but don't work at all, and i check the source code and it is correct, but in console it gives me this error "error: no media to process."
