### ISSUE TITLE
Image hover text effect?

### ISSUE THREAD

**Issue by amberleya** [nanostudio-org/nanogallery2#216]
Love the look of this gallery, I think it will suit me nicely. My only query is, is it possible to have a hover effect with text? I've read through everything on the site and noticed a few great hover effects, but nothing relating to text.

**Comment by Kris-B** [comment]
To animate text, check effects for label:
https://nanogallery2.nanostudio.org/documentation.html#ngy2_gallery_thumbnails_hover

**Comment by amberleya** [comment]
Ah, apologies. I was oblivious to the label hover effects. Thanks so much! I now have a new query: The text doesn't fit in the image, some of it disappears off screen. Looking at your gallery demos with text, they all seem to have the same issue. Is there a way to make the text fit within the thumbnail?

**Comment by Kris-B** [comment]
Only with CSS
