### ISSUE TITLE
Album "image count"

### ISSUE THREAD

**Issue by FL-Retiree** [nanostudio-org/nanogallery2#217]
The first album thumbnail within a gallery comprised of multiple albums displays an image count (overlay) of one greater than the actual number of images in the album.  All other album thumbnails reflect the correct number of images within them.  I'm using the latest version of the nano_photos_provider2.php (7/19/2007) with the latest version of NanoGallery2-2.4.2 on Windows 10 with Apache 2.4.39 and PHP 7.3.5.

**Comment by Kris-B** [comment]
this is an issue in nanoPhotosProvider2 - resolved in v1.2.0 - https://github.com/nanostudio-org/nano_photos_provider2/releases/tag/v1.2.0
