### ISSUE TITLE
Dragging in Firefox

### ISSUE THREAD

**Issue by Largo** [nanostudio-org/nanogallery2#219]
Zooming into an Image in Firefox and then dragging does not seem to work smoothly. It seems to be possible to drag and drop the image somewhere.

I fixed it this way:
`        .nGY2ViewerMedia {
                    pointer-events: none;            
                }`

**Comment by Kris-B** [comment]
Implemented with some modifications due to incompatibility with hosted videos.
Thanks @Largo 
Available in v3.0.0 - https://github.com/nanostudio-org/nanogallery2/releases/tag/v3.0.0
