### ISSUE TITLE
Thumbnail not loaded entirely

### ISSUE THREAD

**Issue by SandroRiz** [nanostudio-org/nanogallery2#220]
Sometimes, (not so common, but not so rare) one of the thumbnail of my album is not loaded correctly and a  white "space" on right/bottom is left.
Doing F5 (reload) resolves the issue. 
If I try to load 10 times the same album, 8 times is ok, other 2 with issues but never on the same photo (not so common the issue is on two or more photo)
I don't think it is network or server related (I have the webserver in LAN), and even the client is powerful (i9, etc.)
Chrome Browser 75.0.3770.142  (and I suspect he's the guilty)

![nanogalleryIssue1](https://user-images.githubusercontent.com/7381657/62040006-0e83c300-b1f9-11e9-830a-81219927135e.jpg)
![nanogalleryIssue2](https://user-images.githubusercontent.com/7381657/62040014-117eb380-b1f9-11e9-9b0d-ec34100757a1.jpg)

**Comment by Kris-B** [comment]
There seems to be an issue with the size of some thumbnails which couldn't be retrieved.
Are you using the latest version ?

**Comment by SandroRiz** [comment]
Yes, 2.4.2

**Comment by Kris-B** [comment]
can you share the URL of your gallery ?

**Comment by SandroRiz** [comment]
The above samples are taken from here:
https://www.rizzetto.com/photo/EuropaTour/Bruges/
https://www.rizzetto.com/photo/EuropaTour/Gent/

but remember it doesn't happens always, just random... (tried now with this https://www.rizzetto.com/photo/Test24-70II-bis/ 
and it happens)

Thx

**Comment by SandroRiz** [comment]
BTW I wrote a blog post (italian only, but google translate does a decent job) about the implementation of this fantastic library
https://www.rizzetto.com/Blog/post/Implementare-una-nuova-photogalleries-gioie-e-dolori

**Comment by Kris-B** [comment]
Nice article, thanks for the promo ;-)

For the moment I could not reproduce your issue...

Ideally, you asp.net application should also provide the size of each thumbnail (`data-ngthumbImgHeight` and `data-ngthumbImgWidth`).
This will avoid the gallery to have to retrieve the size of each thumbnail (which is a complicated process) - and so the gallery display will also be faster (especially on slow internet connections).
Do you have the possibility to implement this ?

**Comment by SandroRiz** [comment]
I have to try how much slow is doing at runtime with asp.net (open each image width a stream and recover wxh with Image.FromStream )

thank for suggestion

Bye

**Comment by Kris-B** [comment]
@SandroRiz  any update ?

**Comment by SandroRiz** [comment]
Oh Yes…

I followed your advice and I wrote a little program that stores in the database the dimension of the thumbnails (both for the existing 14000! and for the new ones when I'll upload them)

So rendering from the db the data-ngthumbimgwidth and data-ngthumbimgheight for each photo, the issue is gone.

Thanks
Sandro

**Comment by Kris-B** [comment]
thanks for the update !
