### ISSUE TITLE
Any ways to disable the auto hide toolbar feature in thumbnail and lightbox？

### ISSUE THREAD

**Issue by joelz** [nanostudio-org/nanogallery2#221]
Hi, 
Is there a way to disable the auto hide toolbar feature in thumbnail and lightbox？ I want them to always show in a mobile app. 

Many thanks.

**Comment by lgw728** [comment]
I think the only way is giving to the configuration section this parameter
 ```
<div id="nanogallery2" data-nanogallery2='{
                    "viewerHideToolsDelay": 30000
                      }'>
```

You can't exactly disable the auto hide, but you can increase its timing a lot (30 seconds in this case). 
By the way, no configuration setting is working for me. Seems like the configuration section is simply ignore. Someone knows why?

**Comment by Kris-B** [comment]
Only delay can be set

**Comment by genescu** [comment]
function ViewerToolsHide() {
      if( G.VOM.viewerDisplayed ) {
        G.VOM.toolbarsDisplayed = false;
        ViewerToolsOpacity( (G.O.viewerHideToolsDelay === '-1') ? 0 : 1);
      }
    }
