### ISSUE TITLE
blurred thumbnails

### ISSUE THREAD

**Issue by nahlaoui** [nanostudio-org/nanogallery2#222]
Hi,
I create the gallery with javascript. On first load everything looks ok, but when I add images programmatically (based on this example : https://codepen.io/Kris-B/pen/wJKowg) new thumbnails images are blurred. 
I think the problem is when using this : newItem.thumbSet( baseURL + 'berlin2t.jpg', 135, 204), because I have to set the height when what I want (and what I do on the init of the gallery) is to set the height to 'auto', and that may be the source of the blurred thumbnails issue.

I need a help here please
thanks

**Comment by Kris-B** [comment]
The value 'auto' can only be used to configure the layout of a gallery.
The real size is needed for individual thumbnails.
