### ISSUE TITLE
Lower portion of image in full screen is cropped

### ISSUE THREAD

**Issue by tyeeman** [nanostudio-org/nanogallery2#224]
I'm using nano_photos_provider2.php add-on and I get cropping in bottom third of image (approx). That part of image is just white. Ever heard of this?

**Comment by Kris-B** [comment]
Can you share an URL to see this behaviour ?

**Comment by tyeeman** [comment]
It's strange, sometimes it happens then sometimes it doesn't. Try [here ](http://padlr.net/capescott/#nanogallery/nanogallery2/2-Gods%20Pocket%20-%20Jepther%20Pt)

**Comment by Kris-B** [comment]
I've tried several times but could not reproduce your issue...

Which system and browser are you using ?

**Comment by Kris-B** [comment]
@tyeeman  any update ?

**Comment by tyeeman** [comment]
I updated my browser a couple of days ago and it seems to work fine now.

**Comment by Kris-B** [comment]
ok, thanks for the update
