### ISSUE TITLE
A Design Question - Can nanogallery2 do what I want?

### ISSUE THREAD

**Issue by pmi123** [nanostudio-org/nanogallery2#225]
I have a database of thousands of pictures, and each picture has associated metadata in the database. I want to be able to search the database on a variety of fields and display the resulting images in nanogallery2 in a mosaic. However, the size of the image in the mosaic is proportional to the number of entries for that criteria. When I click on an image in the mosaic, I want to drill down to the pictures that meet the specific criteria. 

Perhaps an example will make this more clear. Assume there are 1000 pictures of "John Smith" in the database, and they cover the years from 1920 to 2000. I would like to display in the mosaic one picture from each decade (eg 1920, 1930, 1940, etc) and the size of that picture is proportional to the number of pictures in that decade. When I click on the picture for John Smith in 1940, I get another mosaic based on the number of pictures of John Smith in each year of 1940 with varying sizes based on the number of pictures in each year. I click on the picture for 1945 and I get a mosaic or gallery of all the images for that year (all the same size).

A second application involves images, based on certain metadata, in a time line. (Does nangallery2 support time lines?). Image size is also dependent on the number of images for that period in time. Click on an image, and the time line expands with more images as in the above example. 

Am I faced with a lot of modifications to nanogallery2 (js or css), or can I confine my work to the back-end database stuff, where I am more comfortable? Are there sufficient APIs for nanogallery2 to make the front-end work trivial?

Let me be clear. I only want nanogallery2 to display the images and make requests back to the server. The searching, sorting, selecting of images will be done in the back-end Django and python code. I just need to know if I can create a mosaic or images to drill down into the data in the database as I described above without a huge javascript and css coding effort, as I am not a great javascript/css guy. Same with a timeline effect.

Thanks!

Mark

**Comment by pmi123** [comment]
Let me be clear. I only want nanogallery2 to display the images. The searching, sorting, selecting of images will be done in the back-end Django and python code. I just need to know if I can create a mosaic or images to drill down into the data in the database as I described above. Same with a timeline effect. Thanks!

**Comment by pmi123** [comment]
Can videos and images be combined in the same image mosaic?

**Comment by Kris-B** [comment]
Well, videos and images can be conbined, but for the other features, as they are very specific to your project, you'll have to implement them by yourself.
