### ISSUE TITLE
thumbnailSelectable breaks navigation into album and opening lightbox

### ISSUE THREAD

**Issue by supersexy** [nanostudio-org/nanogallery2#227]
With `thumbnailSelectable: true` the thumbnail on click behavior is changed in an unexpected way: 

1. opening the lightbox for **any** image does not work, when **one** thumbnail is selected
2. it is not possible to navigate into **any** album if **one** thumbnail is selected

You can check the first point in your own demo at https://codepen.io/Kris-B/pen/RyaLaG

This is related to #20 - I was able to use the workaround for opening the lightbox with setting 
`thumbnailToolbarImage : { topLeft: 'select', topRight: 'display'}`
and can live with that, but the navigation into an album still is broken, what makes this issue a showstopper. 

BTW the `display` tool should be added to the documentation.

Thank you very much for your attention.

**Comment by Kris-B** [comment]
this is by design
