### ISSUE TITLE
Breadcrumb navigation broken at multi-level-directories

### ISSUE THREAD

**Issue by killerbees19** [nanostudio-org/nanogallery2#228]
Steps to reproduce:

* Create a directory `test` in `nano_photos_content`.
* Copy all example directories and files to `test` folder.

Now navigate to your gallery, test folder and one directory deeper (i.e. `Album A`):

![nav-ok](https://user-images.githubusercontent.com/21372289/65925774-75d51380-e3f2-11e9-86df-125be7280fec.png)

Now reload the page by pressing F5. The album reloads (thanks to _locationHash_), but the navigation is broken:

![nav-broken](https://user-images.githubusercontent.com/21372289/65925773-753c7d00-e3f2-11e9-8ab9-f7fc599058bf.png)

Sadly this is **not** only a cosmetic issue. It's impossible to use the `Galleries` menu item without reloading the page again. It doesn't matter if you're using _breadcrumbOnlyCurrentLevel_ or not, the navigation is broken and can't be used at this point anymore… ☹

**Comment by Kris-B** [comment]
for the documentation:
```
- Limitations   
The nanogallery2 option locationHash should NOT be enabled if albums have more than 2 levels.
```

**Comment by killerbees19** [comment]
Oops, sorry! I missed this line! 😳

/closed
