### ISSUE TITLE
Separate download URL

### ISSUE THREAD

**Issue by JonMerlevede** [nanostudio-org/nanogallery2#23]
Allow specification of a download URL that is different from the large-scale image.

Use case: I want my users to be able to download full-size images through the download button (5MB+), but I don't want to use these for online viewing.

**Comment by Kris-B** [comment]
good point. I'll add this possibility
thanks

**Comment by Kris-B** [comment]
available in v1.2.0 (options 'downloadURL' or 'ngdownloadurl')
