### ISSUE TITLE
Styling the Title and Description text

### ISSUE THREAD

**Issue by Drzayuss** [nanostudio-org/nanogallery2#230]
Hi,

I've gone over the documentation, but haven't found a method to address some of these issues: How do I remove the black stroke from the title and description text? Also, is there any way to increase the size of the description font (I see the method for increasing the title font, but no the description)? Finally, I have a color filter on the thumbnails as well and it seems to apply to the description text and the thumbnail (but not the title text). Is there a way to keep the color filter from applying to the description? My apologies if I have missed this stuff in the documentation. 

Thanks!
Justin

**Comment by Kris-B** [comment]
You have to set directly the CSS properties.
Only a few are supported via parameters.
