### ISSUE TITLE
opening and closing the gallery is getting history and pressing the browser's back button is disrupting the navigation flow

### ISSUE THREAD

**Issue by BrendonIwata** [nanostudio-org/nanogallery2#231]
opening and closing the gallery is getting into the browsing history and pressing the browser's back button is disrupting the browsing flow because instead of returning to the previous page it is returning to the gallery

**Comment by Kris-B** [comment]
set `locationHash` to `false` to disable this behaviour

**Comment by BrendonIwata** [comment]
thanks
