### ISSUE TITLE
Uncaught TypeError: jQuery(...).nanogallery2 is not a function

### ISSUE THREAD

**Issue by maeonian** [nanostudio-org/nanogallery2#232]
I'm not sure what's happening but I get this error: Uncaught TypeError: jQuery(...).nanogallery2 is not a function

I've self-hosted the three files (css, nanogallery2, and even jquery). Any help would be appreciated.

**Comment by Kris-B** [comment]
please check that jquery is loaded before nanogallery2.

**Comment by julk3772** [comment]
I have the same problem, I have the libraries included as follows:

`
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  <link href="https://unpkg.com/nanogallery2@2.3.0/dist/css/nanogallery2.min.css" rel="stylesheet" type="text/css">
  <script type="text/javascript" src="https://unpkg.com/nanogallery2@2.3.0/dist/jquery.nanogallery2.min.js"></script>` 
I don't understand why I get: "jQuery(...).nanogallery2 is not a function"

**Comment by Kris-B** [comment]
@julk3772 please check that jquery is only included once
