### ISSUE TITLE
Display Issues - Random background appearing under thumbnails

### ISSUE THREAD

**Issue by PeteBarcham** [nanostudio-org/nanogallery2#234]
Hi there,
I'm new here so please be kind. 
I've come across a display issue with the gallery that I'm going to implement on our website. It's difficult to replicate, however I have taken a couple of screenshots to show what happens. 

**An example of the grey background (which appears to be the space that the image will fill when the zoom animation is finished):**
![Capture](https://user-images.githubusercontent.com/58075654/69432850-61e2c980-0d32-11ea-9875-324ebe83c1bc.JPG)

**An example a landscape image not filling the thumbnail space:**
![Capture2](https://user-images.githubusercontent.com/58075654/69432855-64452380-0d32-11ea-902b-da875cc16cdc.JPG)

Any advice on how to stop this from happening will be great as I'm hoping to launch this soon.

Thanks,
Pete

**Comment by PeteBarcham** [comment]
Here's another example @Kris-B 

![image](https://user-images.githubusercontent.com/58075654/73003346-67759200-3dfd-11ea-962a-c0f9ac594f46.png)

**Comment by Kris-B** [comment]
can you share the URL of the page with this issue ?

**Comment by PeteBarcham** [comment]
It's currently in development on my vagrant box, so I can't share a link at the moment.

**Comment by Kris-B** [comment]
can you share at least your source code ?

**Comment by PeteBarcham** [comment]
Thanks for responding to me by the way.

Here's the source code for the page effected:

[source-code.txt](https://github.com/nanostudio-org/nanogallery2/files/4104339/source-code.txt)

**Comment by Kris-B** [comment]
I can't see anything special in your code...
The sizes of the thumbnails are not set, so the script needs to download them to retrieve their size. And, as you are using full sized image for thumbnails, maybe it takes too long to retrieve their size.
This could be the explanation.

I would: use small images for the thumbnails, and set their size.

**Comment by Kris-B** [comment]
@PeteBarcham, any update ? thanks.

**Comment by PeteBarcham** [comment]
@Kris-B, the issue is still occurring. Not as often as before though. 

In response to your previous comment we set the height and the width to auto as recommended for the justified layout in the documentation (see below a snippet from our code):

`            nanoGallery.thumbnailHeight = 400;
            nanoGallery.thumbnailWidth = "auto";`

I'll keep an eye on the issue and let you know if it gets better or worse.

Thanks

**Comment by Kris-B** [comment]
Hi @PeteBarcham 
Any update ? Can this issue be closed ?

**Comment by Kris-B** [comment]
I'm closing this issue for now due to inactivity. You may open it again if needed. Thanks.
