### ISSUE TITLE
Items from local host

### ISSUE THREAD

**Issue by dorswisa** [nanostudio-org/nanogallery2#237]
I tried to use in my localhost website images from my computer, but it didn't open them.

I tried this code:
```
jQuery(document).ready(function () 
{
   jQuery("#my_nanogallery2").nanogallery2({
   items:[
           { src: '1.jpg', srct: '1.jpg', title: '1' },
           { src: '2.jpg', srct: '2.jpg', title: '2' },
           { src: '3.jpg', srct: '3.jpg', title: '3' }
         ],
   thumbnailWidth:  'auto',
   thumbnailHeight: 100,
   itemsBaseURL:    '../app/images/',

    locationHash:    false
  });
});
```

That line should help me get to the desired folder, right?
`itemsBaseURL:    '../app/images/',
`
Anyone have any idea how to make it work through photos I choose their target? Thanks.

**Comment by Kris-B** [comment]
Maybe a little bit late, but I don't see any issue here.  Did you check the browser's console?
