### ISSUE TITLE
404 Error on redirect from Google

### ISSUE THREAD

**Issue by db123v** [nanostudio-org/nanogallery2#239]
Hi,
When i access the authorize.php page, then i am taken to the google page to allow permissions to the photos and after clicking allow, the redirect is giving me a 404 error despite having the redirect specified correctly in google. 
Any help with this would be highly appreciated.
Thank You

**Comment by Hermann12** [comment]
Does this gallary support google photo ? I used a picase gallary and search now for an alternative.

**Comment by Kris-B** [comment]
@Hermann12 yes, with the add-on nanogp2 (https://github.com/nanostudio-org/nanogp2)
But the security of the Google API has been enhanced, so that the implementation is not simple.

**Comment by Kris-B** [comment]
@db123v if you still have your issue, you may open a ticket on the nanogp2 repo: https://github.com/nanostudio-org/nanogp2
