### ISSUE TITLE
Stretch small images

### ISSUE THREAD

**Issue by JonMerlevede** [nanostudio-org/nanogallery2#24]
Allow smaller images to be stretched to the window size (by default), similar to how large images are made to fit a smaller window.

Use case: Mainly for high-resolution but small-screen mobile phones.

**Comment by Kris-B** [comment]
but other people asked me the opposite ;-)
I'll see if I'll add an option to configure this.

How would you detect high dpi display on mobile phone?

**Comment by JonMerlevede** [comment]
I was looking at window.devicePixelRatio. CSS pixels are apparently not defined as physical pixels but rather correspond to a visual angle of 0.0213 degrees; this property maps the visual angle back to physical pixels.

**Comment by Kris-B** [comment]
window.devicePixelRatio is used to detect high-density screen, like smartphones, but also retina display...

**Comment by JonMerlevede** [comment]
I suppose it would be possible to combine it with a way of detecting whether the user is using a mobile phone (e.g. by looking at the user agent). I admit I hadn't thought about this much.

**Comment by Kris-B** [comment]
It's difficult to detect mobile device based on user agent because the list is constantly moving.
There's also no way to get the physical screen dimension.

I'm closing this request for now as I don't see any reliable solution to detect a mobile device at this time. But I'm still open for any advice.

**Comment by Kris-B** [comment]
@JonMerlevede 

upscale is now implemented in the DEV branch (https://github.com/nanostudio-org/nanogallery2/tree/dev)
 
you can also check it on the main site: http://nanogallery2.nanostudio.org/index.html

It's activated by default for now, but in the final release this will not be the case.
To enabled it: set value `upscale` to option `viewerImageDisplay`
