### ISSUE TITLE
NanoGallery2 Album List Doesn't Refresh On Return FRom Album View

### ISSUE THREAD

**Issue by gmusgrave** [nanostudio-org/nanogallery2#240]
I have a site with some albums of artists' work. When the site had nine albums, everything worked flawlessly. When I added a tenth album, a problem developed.

Once the tenth album was added, its thumbnail showed up in the album list exactly as expected. If I click on this album, and go to the album view, it shows thumbnails for all of the images in the album. Clicking on a thumbnail brings up the full-size image, and I can navigate through the images in the album. So far so good...

However, when I click on the album name to go back to the list of albums, I no longer have an album list. I have to refresh the page to make it re-appear.

Attached image "**_9 Albums.jpg_**" shows the album list with nine albums: 

![9 Albums](https://user-images.githubusercontent.com/803620/73099239-b29cad00-3eb0-11ea-878c-55b274f2e3da.jpg)

Image "**_9 Albums - Karen Spencer_**" shows the album view for artist Karen Spencer: 

![9 Albums - Karen Spencer](https://user-images.githubusercontent.com/803620/73099237-b2041680-3eb0-11ea-8a1c-b3b3daf71f16.jpg)

If I click on the album name with the left arrow, we go back to the album view ("**_9 Albums.jpg_**"). All of this is what I expect.

When I add a tenth album, the album list looks like "**_10 Albums.jpg_**:" 

![10 Albums](https://user-images.githubusercontent.com/803620/73099242-b3354380-3eb0-11ea-9059-37c5d7e85881.jpg)

Notice the new album for David Winston in the second position. This album works perfectly. But when I click on the album name from the album view (and this can be from ANY album, including Karen Spencer), I return to a screen with no album list ("**_10 Albums - Return.jpg_**"): 

![10 Albums - Return](https://user-images.githubusercontent.com/803620/73099241-b3354380-3eb0-11ea-9f93-b7ce443090ab.jpg)

If I refresh the page, the album list returns (as in "**_10 Albums.jpg_**").

I have reviewed the code until I'm cross-eyed, and cannot spot a coding error (although often another set of eyes will spot something immediately – this is what I'm hoping). I've attached the page source code for your reference ("**_Gallery.html.txt_**"). I'm completely baffled, and I hope it's something silly I'm just not seeing (forest for the trees).

Thank you for any help you can provide,
Garry Musgrave

[gallery.html.txt](https://github.com/nanostudio-org/nanogallery2/files/4110408/gallery.html.txt)

**Comment by gmusgrave** [comment]
I found a work-around...

If I eliminate the DisplayTransition parameters from the data-nanogallery2 declaration, the problem goes away, and the gallery behaves as expected.

Specifically, I eliminated these lines:
  
    "galleryDisplayTransition": "rotateX",
    "galleryDisplayTransitionDuration": 500,
    "thumbnailDisplayTransition": "flipDown",
    "thumbnailDisplayTransitionDuration": 500,  
    "thumbnailDisplayInterval": 30,

Can anyone explain this?

Thanks,
Garry

**Comment by Kris-B** [comment]
I could not reproduce this behaviour.
Can you provide a Codepen example where this issue occurs ?
Thanks.

**Comment by Kris-B** [comment]
@gmusgrave any update ?
