### ISSUE TITLE
nano photos_provider2 not returning any images

### ISSUE THREAD

**Issue by avj243** [nanostudio-org/nanogallery2#241]
I've setup nanaogallery 2 with the nanoPhotosProvider addon, but its not returning any images, just an error message...
-----------------------------
nanogallery2: Could not retrieve nanoPhotosProvider2 data. Error: error, readyState=0
getResponseHeader=function(e){var t;if(h){if(!n){n={};while(t=Pt.exec(p))n[t[1].toLowerCase()+" "]=(n[t[1].toLowerCase()+" "]||[]).concat(t[2])}t=n[e.toLowerCase()+" "]}return null==t?null:t.join(", ")}
getAllResponseHeaders=function(){return h?p:null}
setRequestHeader=function(e,t){return null==h&&(e=s[e.toLowerCase()]=s[e.toLowerCase()]||e,a[e]=t),this}
overrideMimeType=function(e){return null==h&&(v.mimeType=e),this}
statusCode=function(e){var t;if(e)if(h)T.always(e[T.status]);else for(t in e)w[t]=[w[t],e[t]];return this}
abort=function(e){var t=e||u;return c&&c.abort(t),l(0,t),this}
state=function(){return i}
always=function(){return s.done(arguments).fail(arguments),this}
catch=function(e){return a.then(null,e)}
pipe=function(){var i=arguments;return k.Deferred(function(r){k.each(o,function(e,t){var n=m(i[t[4]])&&i[t[4]];s[t[1]](function(){var e=n&&n.apply(this,arguments);e&&m(e.promise)?e.promise().progress(r.notify).done(r.resolve).fail(r.reject):r[t[0]+"With"](this,n?[e]:arguments)})}),i=null}).promise()}
then=function(t,n,r){var u=0;function l(i,o,a,s){return function(){var n=this,r=arguments,e=function(){var e,t;if(!(ipromise=function(e){return null!=e?k.extend(e,a):a}
progress=function(){return s&&(t&&!i&&(l=s.length-1,u.push(t)),function n(e){k.each(e,function(e,t){m(t)?r.unique&&f.has(t)||s.push(t):t&&t.length&&"string"!==w(t)&&n(t)})}(arguments),t&&!i&&c()),this}
done=function(){return s&&(t&&!i&&(l=s.length-1,u.push(t)),function n(e){k.each(e,function(e,t){m(t)?r.unique&&f.has(t)||s.push(t):t&&t.length&&"string"!==w(t)&&n(t)})}(arguments),t&&!i&&c()),this}
fail=function(){return s&&(t&&!i&&(l=s.length-1,u.push(t)),function n(e){k.each(e,function(e,t){m(t)?r.unique&&f.has(t)||s.push(t):t&&t.length&&"string"!==w(t)&&n(t)})}(arguments),t&&!i&&c()),this}
responseJSON=undefined
status=0
statusText=error

URL:http://jordin.name/nano_photos_provider2/nano_photos_provider2.php?albumID=0&hxs=150&wxs=auto&hsm=150&wsm=auto&hme=150&wme=auto&hla=150&wla=auto&hxl=150&wxl=auto [nanoGallery1]

The web page is http://jordin.name/gallery.html
and there are two images available in  nano_photos_provider2\nano_photos_content

Can anyone tell me where I've gone wrong...?

Many thanks, 
Adrian

**Comment by avj243** [comment]
OK, moving on...I cured that error by sorting out a same origin issue, but I now get another error...

-----------------------
nanogallery2: Could not retrieve nanoPhotosProvider2 data. Error: parsererror, SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data readyState=4
getResponseHeader=function(e){var t;if(h){if(!n){n={};while(t=Pt.exec(p))n[t[1].toLowerCase()+" "]=(n[t[1].toLowerCase()+" "]||[]).concat(t[2])}t=n[e.toLowerCase()+" "]}return null==t?null:t.join(", ")}
getAllResponseHeaders=function(){return h?p:null}
setRequestHeader=function(e,t){return null==h&&(e=s[e.toLowerCase()]=s[e.toLowerCase()]||e,a[e]=t),this}
overrideMimeType=function(e){return null==h&&(v.mimeType=e),this}
statusCode=function(e){var t;if(e)if(h)T.always(e[T.status]);else for(t in e)w[t]=[w[t],e[t]];return this}
abort=function(e){var t=e||u;return c&&c.abort(t),l(0,t),this}
state=function(){return i}
always=function(){return s.done(arguments).fail(arguments),this}
catch=function(e){return a.then(null,e)}
pipe=function(){var i=arguments;return k.Deferred(function(r){k.each(o,function(e,t){var n=m(i[t[4]])&&i[t[4]];s[t[1]](function(){var e=n&&n.apply(this,arguments);e&&m(e.promise)?e.promise().progress(r.notify).done(r.resolve).fail(r.reject):r[t[0]+"With"](this,n?[e]:arguments)})}),i=null}).promise()}
then=function(t,n,r){var u=0;function l(i,o,a,s){return function(){var n=this,r=arguments,e=function(){var e,t;if(!(ipromise=function(e){return null!=e?k.extend(e,a):a}
progress=function(){return s&&(t&&!i&&(l=s.length-1,u.push(t)),function n(e){k.each(e,function(e,t){m(t)?r.unique&&f.has(t)||s.push(t):t&&t.length&&"string"!==w(t)&&n(t)})}(arguments),t&&!i&&c()),this}
done=function(){return s&&(t&&!i&&(l=s.length-1,u.push(t)),function n(e){k.each(e,function(e,t){m(t)?r.unique&&f.has(t)||s.push(t):t&&t.length&&"string"!==w(t)&&n(t)})}(arguments),t&&!i&&c()),this}
fail=function(){return s&&(t&&!i&&(l=s.length-1,u.push(t)),function n(e){k.each(e,function(e,t){m(t)?r.unique&&f.has(t)||s.push(t):t&&t.length&&"string"!==w(t)&&n(t)})}(arguments),t&&!i&&c()),this}
responseText=
Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in E:\domains\family-web-sites.package\httpdocs\jordin.name\nano_photos_provider2\nano_photos_provider2.php on line 62

status=200
statusText=OK


URL:nano_photos_provider2/nano_photos_provider2.php?albumID=0&hxs=150&wxs=auto&hsm=150&wsm=auto&hme=150&wme=auto&hla=150&wla=auto&hxl=150&wxl=auto [nanoGallery1]

--------------
Any ideas?
Many thanks,
Adrian

**Comment by Kris-B** [comment]
try updating php to v5.3
