### ISSUE TITLE
More of a question about GPS location...

### ISSUE THREAD

**Issue by timecott01** [nanostudio-org/nanogallery2#244]
Not really an issue, but...The nanogallery2 content settings have a documented attribute 'data-ngexiflocation' but I cannot find any example which shows the required format for this attribute. I currently use ofhter EXIF data such as Camera model etc. Can anyone please advise the required format, and/or give an example? Currently I extract EXIF GPS data, if it is present, into two PHP variables $gpslat and $gpslong. These are values such as 55.32323 and 10.53434 for 55+ degrees North and 10+ degrees East. I return negative values for latitudes in the southern hemisphere, and for longitudes in the western hemisphere.
Any info would be welcome. Thank you.

**Comment by yeupou** [comment]
I made my own perl script to build my gallery. To get the GPS relevant values, I use the following perl code:

`   my $exifTool = new Image::ExifTool;
    my %exifTool_options = (DateFormat => '%x');
    my $info = $exifTool->ImageInfo($File::Find::name, ("CreateDate","GPSLatitude","GPSLongitude","GPSDateTime", "Make", "Model", "Software", "FocalLength", "Flash", "Exposure", "ISO"), \%exifTool_options);
    $comment{$url} = $info->{"CreateDate"};
    $comment{$url} = $info->{"GPSDateTime"} if $info->{"GPSDateTime"};
    
    if ($info->{"GPSLatitude"} and $info->{"GPSLongitude"}) {
	$gps{$url} = $info->{"GPSLatitude"}." ".$info->{"GPSLongitude"};
	$gps{$url} =~ s/\sdeg/°/g;
    }`

Later, the $gps{$url} is printed with escapeHTML() (in PHP, probably htmlentities() or something like this) so ° get htmlized.

It is enough for Google Maps to work to simply concatenate both GPSLatitude and GPSLongitude with "deg" string replaced by the degree symbol °.


Full code there https://yeupou.wordpress.com/2020/11/21/generating-static-galleries-with-nanogallery2/

You can probably do something quite similar in PHP
