### ISSUE TITLE
A question about image downloading from nanogallery

### ISSUE THREAD

**Issue by timecott01** [nanostudio-org/nanogallery2#245]
Is there a way of preventing images in nanogallery being downloaded using the download button? I would prefer images to be download inhibited. I appreciate that images can be copied using other means, but I would prefer that the image download function could be disabled. Is this possible??
Any information welcome.
Thank you.

**Comment by Kris-B** [comment]
The download button on the lightbox can be removed - see file:///C:/Github/nanoGALLERY2_DEV/src/nanogallery2/gh-pages/documentation.html#ngy2_lightbox
If you want to disable the context menu, you have to implement it by yourself.
