### ISSUE TITLE
Android issues

### ISSUE THREAD

**Issue by JonMerlevede** [nanostudio-org/nanogallery2#25]
First off, thanks for this beautiful library, it is very user-friendly and does precisely what I want it to! I submitted a couple of nice-to-have feature requests separately from this issue to make them easier to track.

I'm having some issues with Chrome-on-Android:

* I use pagination and sometimes, it seems like after the gallery is fully loaded, I can no longer swipe to the next page. I can still use the page number buttons to move from page to page. I'm also getting the problem with pagination that is mentioned in issue #11.
* Similarly, I often can't open the lightbox. There is just no more response to me pressing on the thumbnails.
* The first image to open in the lightbox is shown fullscreen; subsequent images usually have a small black border around them. After some testing I now think that the images that are pre-loaded appear with a border, and the ones that still have to be loaded (while you see the loading animation) appear full screen. The images that are full screen seem to shrink a bit before they disappear as I swipe right or press the right arrow. Compare [this](https://acd.5ha.re/KPQ2gt0R4yQOZ8pBsklRF39ZZYuV7LIw54Xamdaxnns/1) to [this](https://acd.5ha.re/KPQ2gt0R4yQOZ8pBsklRF39ZZYuV7LIw54Xamdaxnns/0).

I know these descriptions are not very specific, please let me know if I can help by getting you more detailed information.

**Comment by Kris-B** [comment]
Yes, there are some problems with gestures on Android/Chrome. nanogallery2 is using hammer.js and several people have issues with the latest versions of chrome on android.
I could not find any good workaround for now. Other gesture libraries have similar problems.
I'm still searching for a fix...

The last point is related to high DPI display. Images are "zoomed-in" on these displays to avoid blurring.
But this is only possible if the size of the image is known.
Ideally, the image size should be defined with data-ngimageWidth/data-ngimageHeight or width/height options. If not, this kind of effects can happen.

**Comment by Kris-B** [comment]
I made some changes on the gesture handling.
Could you please check the gallery on the intro page http://nanogallery2.nanostudio.org/
to see if you still have issues on Android?
Thanks!

**Comment by JonMerlevede** [comment]
The demo gallery seems to be working fine for me! I was already defining width and height options, but I'll check again to see if I didn't make a mistake.

**Comment by JonMerlevede** [comment]
I still haven't found a way around the black border surrounding preloaded images.

I now correctly specify the width and the height of my images using the `width` and `height` properties; everything is working fine on desktops. When I do not resize my images, everything works fine on Chrome on Android too, even without specifying dimensions. However, when I resize images to correspond precisely to the size of the screen, a black border surrounds images that are preloaded. Images are loaded at a resolution that should allow for an unstretched preview (1440x1080 on SGS6) and given correct width and height properties.

I do not have this issue with the gallery on the intro page, but then those pictures are usually wider than 1440px.

**Comment by Kris-B** [comment]
I made some changes in the management of image sizes: are you interested in testing a beta version?

**Comment by Kris-B** [comment]
changes released in v1.3.0
https://github.com/nanostudio-org/nanogallery2/releases/tag/v1.3.0

I'm closing this issue for now, please open it again if you still have problems
