### ISSUE TITLE
Lightbox ViewerToolbar area gets darkened even with viewerToolbar: {display: false}

### ISSUE THREAD

**Issue by rsuzuki0** [nanostudio-org/nanogallery2#250]
I took everything out of the viewer toolbar in both standard and minimized forms and turned off the whole toolbar. There is nothing to show there. However, the part of the image where the toolbar gets overlaid gets darkened until times out in 3000.

I would like to see this corrected to darken areas that are being actively used and leave other areas alone.

Thank you for your attention in advance.

**Comment by Kris-B** [comment]
Please, share your settings.

**Comment by Kris-B** [comment]
I'm closing this issue for now but you can re-open it if you need.

**Comment by rsuzuki0** [comment]
{
                        descriptionFontSize: "0.1 em",
                        navigationFontSize: "0.1 em",
                        titleFontSize: "0.1 em",
                        galleryRenderDelay: 0,
                        galleryDisplayTransitionDuration: 250,
                        breadcrumbHideIcons: true,
                        thumbnailDisplayTransition: "fadeIn",
                        thumbnailDisplayOutsideScreen: false,
                        thumbnailHeight:  'auto',
                        thumbnailWidth:   320,
                        thumbnailAlignment: "center",
                        thumbnailCrop: 'false',
                        thumbnailBorderVertical: 0,
                        thumbnailBorderHorizontal: 0,
                        thumbnailLabel:     { display: false, position: 'overImageOnBottom', hideIcons: true },
                        thumbnailL1Label:     { display: true, position: 'overImageOnBottom', hideIcons: true },
                        viewerToolbar:    {
                           standard:  '{display:false}',
                           minimized: '{display:false}',
                           position: 'bottomOverImage',
                        },
                        viewerTools:    {
                           topLeft:   '',
                           topRight:  'playPauseButton, fullscreenButton, closeButton'
                        },
                        viewerImageDisplay: 'upscale',
                        itemsBaseURL:     'Im/',
                        icons: {
                          thumbnailCounter: '',
                          thumbnailImage: '',
                          thumbnailIcon:  '',
                          }

**Comment by Kris-B** [comment]
you should not put `'` around ojects.
Replace:
```
  standard: '{display:false}',  
  minimized: '{display:false}',
```
with:
```
  standard: {display:false},  
  minimized: {display:false},
```

**Comment by rsuzuki0** [comment]
Thanks Kris for your response. I tried that, but without the quotes the gallery breaks and won't display images in Viewer at all.
