### ISSUE TITLE
addcustomUrl on first gallery view (onThumb)

### ISSUE THREAD

**Issue by tancetin** [nanostudio-org/nanogallery2#251]
Hi All, I using ng2. How can I add custom icon on thumb view for redirect to external url for image? It has addCustomUrl function? I can't find in your documents.

**Comment by Kris-B** [comment]
The custom image URL can be defined:
- with markup using `data-ngdest`
Example:
```
<a href="img_01.jpg" data-ngthumb="img_01t.jpg"  data-ngdest="YOUR URL">Title Image1</a>
```
- with javascript using `destURL`
Example:
```
{ src: 'image_01.jpg', srct: 'image_01t.jpg',  title: 'Title Image1', destURL: 'YOUR URL' }
```

 <br>
The default icon can be changed with this option:

```
icons : {
  thumbnailDisplay: 'YOUR MARKUP FOR CUSTOM ICON'
}
```
