### ISSUE TITLE
Can I use a string as the item ID?

### ISSUE THREAD

**Issue by krid** [nanostudio-org/nanogallery2#253]
I want to use strings (filename minus the extension) for item IDs to provide stable permalinks:
      `http://example.com/pics/#nanogallery/gallery/0/cute-cat-pic`
Instead of:
      `http://example.com/pics/#nanogallery/gallery/0/1`
Is there anything in the existing codebase, or any planned features, that would make that problematic?  

I looked through the code and I don't see anything that depends on the IDs being integers.  I tried using strings as the IDs and nothing seems to break.

If this is workable and doesn't interfere with planned new features it'd be nice to update the documentation to include this technique (https://nanogallery2.nanostudio.org/datasource.html#ngy2_define_javascript).

**Comment by Kris-B** [comment]
yes, you can use strings.
