### ISSUE TITLE
Customise Info Popup

### ISSUE THREAD

**Issue by philipstratford** [nanostudio-org/nanogallery2#259]
Given the incredible level of customisation that NanoGallery2 allows, I can't believe that it isn't possible to customise the popup that's displayed when clicking the info button in the gallery and lightbox views, but I've searched all of the documentation and Googled more widely and can't find any suggested solution.

I want to be able to customise this popup to match the styling of the rest of my site, and to display custom data - the image's title, description and several other things which I'm returning from my database (e.g. year, people in photo, etc.).

There doesn't even seem to be an event or callback I can use to hook into the displaying of the popup. Any ideas, anyone? Am I missing something?

**Comment by Kris-B** [comment]
available in v3.0.0 - https://github.com/nanostudio-org/nanogallery2/releases/tag/v3.0.0

 callback: fnPopupMediaInfo

```
...
  fnPopupMediaInfo: my_popup_info,
          
...
        // Function called before the popup for media info is displayed
        // Content and title can be changed
        function my_popup_info(item, title, content){
          var my_title = title + ' <b>nanogallery2</b>';
          var my_content = content + '<br><br>[The content of this popup can be customized with some javascript.]';
          return {title: my_title, content: my_content};
        }
...
```
