### ISSUE TITLE
Thumbnail selection

### ISSUE THREAD

**Issue by JonMerlevede** [nanostudio-org/nanogallery2#26]
When enabling thumbnail selection, the first thumbnail needs to be pressed on the circle in the upper left corner; otherwise, the lightbox opens with a view on the picture and the picture remains unselected. All subsequent pictures can be selected by clicking in the middle of the thumbnail.

**Comment by Kris-B** [comment]
this is by design.

**Comment by JonMerlevede** [comment]
Just for reference: In my opinion the change in behavior after selecting the first image is not intuitive.

**Comment by Kris-B** [comment]
it's the same behavior since years (with nanoGALLERY), and for users, it's not easy to change this.

note: google photos has the same behavior

**Comment by JonMerlevede** [comment]
Google Photos has the same behavior, but then their images are always selectable. I'm having my users press a button "select pictures for downloading" before making it possible to select pictures. Then it's not as intuitive. Anyway, since you have consciously chosen for this design, I respect your decision!

**Comment by Kris-B** [comment]
I'm not sure to understand this.
Actually, I don't see a big difference between nanogallery2 and google photos: in both cases, the user clicks a checkbox on the top left corner of the thumbnail to activate the selection mode. After that, each thumbnail is selectable, as long as more than 1 thumbnail is selected.
Did I miss something?

**Comment by JonMerlevede** [comment]
Yeah, I guess it makes perfect sense to use thumbnail selection that way. I am currently doing it differently, which is why I thought selection is not intuitive.

I make users press a button ("download images") before thumbnails become selectable; clicking this button changes the `thumbnailSelectable` property of the gallery. After pressing such a button, users expect to be able to click anywhere on the image; they expect "selection mode" to be activated. With the current behavior they still have to activate selection mode by selecting the first image in the upper-left corner.

The selection behavior of nanogallery is not unintuitive, but it is when using it like I am. It's weird to have to press two buttons to "really" activate selection. A way to activate selection mode using Javascript would solve this for me. I don't think that this is currently possible, but I understand that you can't support every use case perfectly.
