### ISSUE TITLE
New version breaks my code

### ISSUE THREAD

**Issue by amartini** [nanostudio-org/nanogallery2#265]
After nanogallery updated to version 3 i get blank squares besides my photos.

I set up a fiddle here https://jsfiddle.net/bortao/ejkbafvd/
If i change version to v2.4.2 it displays correctly: https://jsfiddle.net/bortao/pxke48bm/

The thing is between each image I have to add a `<script>` block to update a progress bar. I removed the code on the fiddle. Is there a way to specify I only want the `<a>` entries to be used? Why this works on the previous version and now won't work anymore?

**Comment by Kris-B** [comment]
Since v3, all HTML element's types can be used to define content.
I just changed the code to ignore elements without media data, like `<script>`, in your case.
Can you please check the version in the DEV-branch ? https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by amartini** [comment]
Yeah, that fix it. Thanks!

**Comment by Kris-B** [comment]
Thanks for your feedback.
Your usage with scripts seems interesting: can you share it?
