### ISSUE TITLE
Layout is not adjusted immediately anymore when resizing the browser window 

### ISSUE THREAD

**Issue by lxb301** [nanostudio-org/nanogallery2#266]
**Describe the bug**
Gallery layout/size is not adjusted immediately anymore when resizing the browser window or rotating the smartphone.

**Expected behavior**
With nanogallery 2.4.2 the layout and thumbnail sizes for Mosaic and Cascading layouts were automatically adjusted while the window was being resized.
Nanogallery 3.0.1 does not do this anymore. The layout stays and pictures gets cropped (cf. screenshot) until one moves a scrollbar. Then the layout change is triggered and everything looks as it should.

I have added two JSfiddles an a screenshot to illustrate this:
Made with 3.0.1: https://jsfiddle.net/kfznvLyj/
Made with 2.4.2: https://jsfiddle.net/ujec5bqL/
Examples are made with 

![resize](https://user-images.githubusercontent.com/67793612/86478995-94828500-bd4b-11ea-93c5-6515824f3400.jpg)

A similar behaviour can be observed when viewing the page on a smartphone and the display is rotated. 
=> 2.4.2 automatic adjustment of layout as soon as screen is rotated 
=> 3.0.1 no adjustment of layout until scrolling up or down
 
Tested: 
Cascasing and Mosaic layouts
Win10: Firefox, Chrome, Edge
Android: Firefox

Any help is very much appreciated.

Cheers,
Alex

**Comment by Kris-B** [comment]
@lxb301 thanks for the detailed issue description. 
I pushed a new version to the DEV branch. Can you please check? 
https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by lxb301** [comment]
Hi Kris-B,

Thanks for the quick response. I did a brief test and the issue seems to be solved in the new version.

All the best and thanks for this amazing piece of software!!
Alex
