### ISSUE TITLE
Can't make self hosted video to play

### ISSUE THREAD

**Issue by yell0w4x** [nanostudio-org/nanogallery2#267]
Hi, sorry to bother you with this matter, but searching the web and reading the docs didn't help me much.

I tried both javascript and html markup. I also tried `.mp4` and `.webm`, the gallery is rendered fine and video tag also exists. But by default video is stopped. Also when I click on play button the gallery just slide to next image (or video). I couldn't make it play the video. I looked through the documentation but found nothing. I also tried [v2.4.0 where the video support had been added](https://github.com/nanostudio-org/nanogallery2/issues/147#issuecomment-471772278), but got same result.

If I do in console something like that: 
`$('video.nGY2ViewerMedia').get(0).play()`
the video starts playing... Looks like the handler that forwards to next slide prevents video from playing when I click on 'Play' button.

I added `autoplay` attribute to the `<video>` tag (line: 6149), but it's not the best solution. Could you please clear this out for me.

What have I missed? 
Thanx in advance.

**Comment by ophocl** [comment]
excuse me, the topic is still needed
add an attribute _autoplay_ is bad advice - the video starts to show but the gallery scrolls next item without waiting for the end of this video
does anyone have a solution?
