### ISSUE TITLE
Self hosted video is not playing when clicked

### ISSUE THREAD

**Issue by yell0w4x** [nanostudio-org/nanogallery2#268]
The video format don't matter, javascript or html markup also.
The gallery is rendered fine and video tag also exists. By default video is stopped, when I click on play button the gallery just slide to next image (or video). Also [v2.4.0 where the video support had been added](https://github.com/nanostudio-org/nanogallery2/issues/147#issuecomment-471772278), has same issue.

I can add autoplay attribute to the <video> tag (line: 6149), but it's not the best solution.

**Comment by Kris-B** [comment]
can you please check the version in the DEV-branch ?
https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by yell0w4x** [comment]
Checked, the same behavior

**Comment by Kris-B** [comment]
Did you test with the new CSS file also ?

**Comment by yell0w4x** [comment]
of course

**Comment by Kris-B** [comment]
There seems to be an issue with the Grunt CCS minify task in the DEV-branch, and I cannot find it out...
Please use the files in the master-branch.

**Comment by yell0w4x** [comment]
I tried non-minified css and it works. Thanx.

**Comment by Kris-B** [comment]
fixed in v3.0.2
