### ISSUE TITLE
viewerGallery 'none' not working

### ISSUE THREAD

**Issue by AlessandroZero** [nanostudio-org/nanogallery2#269]
I'm trying to hide the viewergallery bar in lightbox.
For what I can understand, I must set it to 'none' in jquery.nanogallery2.min.js but if I do that, the gallery stops responding (clicking on thumbnails does not start the lightbox and I'm also unable to scroll the thumbnail page).
The only options working for me are 'bottomOverMedia' and 'bottom'.

Can I have some help?
Thank you

**Comment by AlessandroZero** [comment]
Nevermind, using jquery.nanogallery2.js (not ".min") and setting:

  viewerGallery:	'none'

works as intended.

**Comment by Kris-B** [comment]
Yes, I push a new in progress version in the wrong branch : actually the version on the DEV branch should correct this bug.

**Comment by Kris-B** [comment]
I have some issue with the CSS Minify Grunt task in the DEV branch.
For now, I'm not using the DEV branch anymore, and I'll push the latest work in progress in the master branch.
I'll notify you as soon as the fixed version will be released.

**Comment by AlessandroZero** [comment]
No problem.

You're great

**Comment by jjbertin** [comment]
Bonjour,
Je ne sais pas si je suis au bon endroit car mon anglais est nul.
Depuis quelques temps des photos miniatures apparaissent en bas de mes photos plein écran ; je voudrais supprimer ces miniatures.
Comment faire ?
D'avance merci

**Comment by Kris-B** [comment]
fixed in v3.0.2

**Comment by Kris-B** [comment]
@jjbertin il faut utiliser la version 3.0.2 avec l'option ``viewerGallery: 'none'``

**Comment by jjbertin** [comment]
Merci de votre réponse.

**Comment by jjbertin** [comment]
Désolé, mais je sais pas actualiser la version.
1) Comment intégrer la version 3.0.2
2) Comment appliquer la clé API de Flickr (que j'ai récupéré), car j'ai le message d'erreur suivant 
nanogallery2: Please set your Flickr API Key (option flickrAPIKey) [my_nanogallery]
nanogallery2: Could not retrieve Flickr album: Invalid API Key (Key has invalid format) (code: 100). [my_nanogallery]
D'avance merci de votre aide

**Comment by Kris-B** [comment]
@jjbertin 
Utilisez l'option ``flickrAPIKey`` pour définir la clef d'API dans votre galerie. Cf.: https://nanogallery2.nanostudio.org/datasource.html#ngy2_flickr

Je ne sais pas comment vous intégrer nanogallery2 dans vos pages à l'heure actuelle. Il existe différentes manières de le faire (téléchargement depuis github, utilisation de NPM ou d'un CDN).
Tous les liens pour ces possibilités sont sur la page: https://nanogallery2.nanostudio.org/

**Comment by jjbertin** [comment]
Merci mille fois, je peux de nouveau voir mes albums.

En revanche, je n'ai pas compris comment passer à la version 3.0.2
Pouvez-vous m'aider ; d'avance merci

**Comment by Kris-B** [comment]
@jjbertin comme indiqué je ne sais pal quelle méthode vous utiliser actuellement pour intégrer le script dans vos pages. Il m'est donc difficile de vous répondre. Néanmoin, je dirais que vous si vous avez un message concernant la clef API de Flickr, vous utilisez déjà la version 3.0.2. Vous n'avez donc rien de plus à faire.

**Comment by jjbertin** [comment]
Ok, merci de votre réponse.
Pour information, j'utilise le logiciel OpenElement pour générer mon site.
J'ai ce code en Header.
<link href="https://unpkg.com/nanogallery2/dist/css/nanogallery2.min.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="https://unpkg.com/nanogallery2/dist/jquery.nanogallery2.min.js"></script>
Ensuite, j'ai le code html précisant les différents codes Flickr.

Merci pour l'aide apportée.

**Comment by Kris-B** [comment]
@jjbertin avec le lien utilisé, le numéro de version n'est pas précisé et vous allez donc automatiquement utiliser la dernière version.

**Comment by jjbertin** [comment]
Parfait, et merci beaucoup pour tout ce que vous faites.
