### ISSUE TITLE
Max rows does not work with pagination when thumbnail height is set to auto

### ISSUE THREAD

**Issue by janne-anttila** [nanostudio-org/nanogallery2#27]
If I define nanogallery2 as follows

```
			<div data-nanogallery2='{ 
				"kind": "flickr",
				"userID": "<my user id>", 
				"galleryMaxRows": 2,
				"thumbnailHeight": "auto",
				"thumbnailWidth": 336.66,
				"galleryDisplayMode": "pagination",
				"thumbnailBorderHorizontal": 0,
				"thumbnailBorderVertical": 0,
				"thumbnailGutterWidth": 30,
				"thumbnailGutterHeight": 30
			}' ></div>
```

Nanogallery2 will load all images, instead of displaying pagination..

**Comment by Kris-B** [comment]
When the height is set to auto, you don't have rows anymore.
In this case, `galleryMaxRows` is ignored.

I'll mention this in the documentation. Thanks for the report.

**Comment by roaldarbol** [comment]
Just a quick comment for the portable builder: It would be great if the `Gallery display mode` (and associated settings) was made inaccessible when the `Cascading` layout is chosen - it took me some time to realise that it could be related to this. :-) 
And by the way, massive thanks for having made nanogallery2 - it's really really awesome!
