### ISSUE TITLE
error with Visual Builder

### ISSUE THREAD

**Issue by marchoso** [nanostudio-org/nanogallery2#270]
Whe I try to use the Visual Builder, https://nanogallery2.nanostudio.org/builder.html,  I get the next error. 
nanogallery2: Please set your Flickr API Key (option flickrAPIKey) [nanoGallery3]
nanogallery2: Could not retrieve Flickr album: Invalid API Key (Key has invalid format) (code: 100). [nanoGallery3]

I can choose my album, but when I choose "build gallery" I'got this error.

Can you help me?

Thanks.

**Comment by Kris-B** [comment]
Fixed.
You now need a to request an API key from Flickr. It can be obtained directly from the Builder.
