### ISSUE TITLE
Upgraded to nanogallery2 with Google Photos - full size image issue

### ISSUE THREAD

**Issue by elivne** [nanostudio-org/nanogallery2#273]
Sorry if I'm repeating an existing issue, can't find one:
This is our gallery https://www.strictly-israeli-dancing.co.uk/gallery.htm using Google Photos albums
Album and thumbnails show fine, but when clicking to open full size (on laptop, tablet or mobile) something goes wrong and it's mostly a black screen with some bits of images on the margins. Am I missing some lightbox settings?
Thanks

**Comment by Kris-B** [comment]
Where did you get your CCS file ?
Can you try with this one: https://cdn.rawgit.com/nanostudio-org/nanogallery2/master/dist/css/nanogallery2.min.css

**Comment by elivne** [comment]
Been using https://rawgit.com/nanostudio-org/nanogallery2/master/dist/jquery.nanogallery2.min.js since a long time ago - will try with your suggestion

**Comment by elivne** [comment]
Been using an old downloaded version - will try with your suggestion
Also been linking to this script - still good? https://rawgit.com/nanostudio-org/nanogallery2/master/dist/jquery.nanogallery2.min.js
Lastly I also have a link to https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js - can't remember if this is needed for nanogallery or not and, if yes, does it need updating.

**Comment by Kris-B** [comment]
Actually, it's not a good practice to link files directly to the github repository, because you may use a work in progress version.
Use a CDN version, like:
``https://cdnjs.cloudflare.com/ajax/libs/nanogallery2/3.0.2/css/nanogallery2.min.css``
``https://cdnjs.cloudflare.com/ajax/libs/nanogallery2/3.0.2/jquery.nanogallery2.min.js``
