### ISSUE TITLE
Move ItemDisplayInfo in a separate file

### ISSUE THREAD

**Issue by SandroRiz** [nanostudio-org/nanogallery2#275]
[Feature Request]

it would very nice to have a mode to customize the Iteminfo form of single photo (some people want more or less exif data, eg. this is how I customize mine...). A sort of template/placeholder editor
![Annotation 2020-07-20 105426](https://user-images.githubusercontent.com/7381657/87919017-8042c580-ca77-11ea-9ec5-c5ba64664298.png)

When not possible, it would be better to move the function outside the main js file (eg. a in jquery.nanogallery2.custom.js that is called from the main), so when it makes an upgrade you can copy all the original files without fear to lose your customization (and you don't have to redo the minify)

thanks

**Comment by Kris-B** [comment]
The callback `fnPopupMediaInfo` can already be used to fully customized the info popup.
Did you check it ?

**Comment by Kris-B** [comment]
Just define your function, and then assign it in the gallery settings.
```
function myPopupInfo(ng2item, title, content) {
  var r = { title: 'Foo', content: 'Bar' };
  return r;
}

jQuery("#nanogallery2").nanogallery2( {
  thumbnailHeight:  150,
  thumbnailWidth:   150,
  fnPopupMediaInfo: myPopupInfo,
  ...
});


```

**Comment by SandroRiz** [comment]
Hi Kris, I return to this old point...

if I assign the function in my div the thumbnailLabel are always displayed no matter display is false; and the viewerTools are displayed with a default (rotate + fullscreen) instead what defined in viewerTools property (and without the infoButton I cannot try the popupFunction). Thanks

    <div id="nanogallery2" data-nanogallery2='{
    "viewerToolbar":    {
        "display":    true,
       "standard":   "label",
    "minimized": "minimizeButton, label, sharebutton, fullscreenButton" },
    "viewerTools":    {
        "topRight":  "zoomButton, fullscreenButton, infoButton, shareButton, closeButton" },
    "thumbnailHeight": "200",
    "thumbnailWidth":  "auto",
    "thumbnailBorderHorizontal" : "0",
    "thumbnailBorderVertical" : "0",
    "thumbnailLabel" : { "display" : false },
    "fnPopupMediaInfo": myPopupInfo
     }'>

**Comment by SandroRiz** [comment]
Moving the gallery setup on javascript, it works!
