### ISSUE TITLE
Setting 'thumbnailOpenInLightox' to false breaks links

### ISSUE THREAD

**Issue by TrueAegis** [nanostudio-org/nanogallery2#276]
I am attempting to create a gallery with unique URLs for each image in the gallery. Figure it would be as simple as putting in the url and disabling the lightbox. Unfortunately setting "thumbnailOpenInLightox" to false breaks the link. Is there a reason for this? What would be a solution to get the links working again?

**Comment by Kris-B** [comment]
I'm not sure to understand: what is the purpose of unique URLs pointing to single images if the lightbox is disabled ?

**Comment by TrueAegis** [comment]
@Kris-B I would rather have the images in the gallery open up to a new web page specific to the image clicked. (Kind of like a navbar made into a gallery is the simplest I can explain it) 

I figure since the images in the gallery are just links I should just be able to put the URLs for those web pages in the reference. However, as soon as the lightbox is disabled, the links cease working as links and become unclickable.

**Comment by Kris-B** [comment]
You don't need to disable the lightbox.
Just set a destination URL for each image (with ``data-ngdest`` or ``destURL``).

**Comment by TrueAegis** [comment]
Naturally, I overcomplicate things. Hey, thanks for the quick answer. That is very awesome and I appreciate it a lot. Keep up the good work.
