### ISSUE TITLE
Flickr requests new API Key

### ISSUE THREAD

**Issue by Drzayuss** [nanostudio-org/nanogallery2#277]
Hi,

I am using Nanogallery with Flickr as the host of my images. Things have worked great for months and months. Yesterday, upon loading the page . . . The gallery appears as  a black box with two read sentences:

"nanogallery2: Please set your Flickr API Key (option flickrAPIKey) [Placements]

nanogallery2: Could not retrieve Flickr album: Invalid API Key (Key has invalid format) (code: 100)."

I have another gallery implementation on the same page that is functioning correctly.

Any idea as to what may have happened?

Thanks!

Justin

**Comment by Kris-B** [comment]
hey justin,
Since v3.0.2, you need to set a Flickr API key in order to access your data (option ``flickrAPIKey``).
To get one, visit : https://www.flickr.com/services/apps/create/

Full updated Flickr documentation:
https://nanogallery2.nanostudio.org/datasource.html#ngy2_flickr

**Comment by Drzayuss** [comment]
Thank you!

Sent from my iPhone

On Jul 23, 2020, at 7:46 AM, Christophe Brisbois <notifications@github.com> wrote:

﻿

hey justin,
Since v3.0.2, you need to set a Flickr API key in order to access your data (option flickrAPIKey).
To get one, visit : https://www.flickr.com/services/apps/create/

Full updated Flickr documentation:
https://nanogallery2.nanostudio.org/datasource.html#ngy2_flickr
