### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MohsenEs** [nanostudio-org/nanogallery2#278]
jQuery.nanogallery2[("data_" + u.O.kind)] is not a function
error
what?

**Comment by Kris-B** [comment]
more details, please

**Comment by MohsenEs** [comment]
![2020-07-30_18-04-39](https://user-images.githubusercontent.com/46873097/88929511-75fea380-d28f-11ea-98a5-ca7075a547fc.jpg)

**Comment by MohsenEs** [comment]
* jQuery JavaScript Library v1.12.4


mu jquery

**Comment by MohsenEs** [comment]
Thanks for answering, it worked
The problem was the JavaScript reference
