### ISSUE TITLE
Setting navigationBreadcrumb borderRadius does not have impact

### ISSUE THREAD

**Issue by janne-anttila** [nanostudio-org/nanogallery2#28]
Code is using incorrrectly cs.navigationFilter.borderRadius instead of cs.navigationBreadcrumb.borderRadius: https://github.com/nanostudio-org/nanogallery2/blob/master/src/jquery.nanogallery2.core.js#L5530

**Comment by Kris-B** [comment]
will be fixed in the next version
thanks!

**Comment by Kris-B** [comment]
fixed in v1.2.0
