### ISSUE TITLE
More buttons on top right toolbar in lightview

### ISSUE THREAD

**Issue by Gae84** [nanostudio-org/nanogallery2#280]
Good morning,
i have a question.
In lightbox view it is possible to add custom buttons on top right toolbar (next the close button) with custom handlers (as it happens for the buttons below the photos..the viewerToolbar) ?
Thanks everyone!
Gae

**Comment by Kris-B** [comment]
Please check this demonstration on codepen: https://codepen.io/Kris-B/pen/GWpWBR

**Comment by Gae84** [comment]
Thanks for your help...How to have an icon instead of text for the custom button?

**Comment by Kris-B** [comment]
Simply use an icon font.

Example with Font Awesome:
```
viewerCustomTool2: '<i class="far fa-question-circle"></i> Customized-Button'
```
I've updated the codepen demo: https://codepen.io/Kris-B/pen/GWpWBR

**Comment by Gae84** [comment]
Ok thanks, i tried with an img tag and custom image and works. Great! I hope my employer doesn't ask too much, that's enough for me. Thank you so much.
