### ISSUE TITLE
Set title for slides

### ISSUE THREAD

**Issue by yell0w4x** [nanostudio-org/nanogallery2#283]
I'm reading documentation and can't find any option to set the slides' title. Is it possible?

**Comment by Kris-B** [comment]
What do you mean with: slide's title?

**Comment by yell0w4x** [comment]
These are for thumbs.

```
            thumbnailLabel: {titleMultiLine: true},
            items: [
                { src: '1.png', srct: 'thumb/1.png', title: 'Add new server instance'},
                { src: '2.png', srct: 'thumb/2.png', title: 'Select server location' },
            ..
```
I would like to have a caption or title or whatever string that is shown alongside with the large image. When user is watching slides. Above or below e.g.

**Comment by Kris-B** [comment]
You can display the title defined for the thumbnail.
3 areas are available:
- top left tools
- top right tools
- or toolbar

Use the tool named `label` to display the title.

Example to display the title on the top left corner:
```
...
viewerTools:    {
        topLeft:    'label'
      }   
...
```

For more details, see the documentation: https://nanogallery2.nanostudio.org/documentation.html#ngy2_lightbox
