### ISSUE TITLE
Justified Images are Being Cropped

### ISSUE THREAD

**Issue by TrueAegis** [nanostudio-org/nanogallery2#284]
Having an issue with images being cropped using a justified gallery. Currently have thumbnailWidth set to "Auto" is there anything else that I need to do to? The documentation states that there should be no cropping of the images in the gallery.

**Comment by Kris-B** [comment]
Are all images of your gallery cropped ?
Did you define the size of each of the thumbnail images (using `"data-ngthumbImgWidth"` / `"data-ngthumbImgHeight"` or `imgtWidth` / `imgtHeight`)?

**Comment by TrueAegis** [comment]
@Kris-B It seems they are all cropping the image if they have an excessive height. 

No, I have not. Would these properties be suggested? What is the difference between just using width and height?

**Comment by Kris-B** [comment]
In justified mode, the real size of each thumbnail image is required to calculate the position and display size of each thumbnail. If the size is not provided, the script needs first to download the images to retrieve their size, which may lead to numerous layout recalculations. So it's a good practice to set their size.

For your cropping issue: can you provide the URL to a page where it can be reproduced ? or a codepen ?

**Comment by TrueAegis** [comment]
I think I understand what you are saying. So the "data-ngthumbImgWidth" and "data-ngthumbImgHeight" properties should be set? The documentation just says it is highly suggested for performance improvements not really sure what that means. 

At the moment I cannot, I feel it may have something to do with the images in the gallery and less of the code. I cannot share these images anywhere. I am thinking that the ratio of these images is really the issue here. For example, I set the gallery with a height of 200px and the image is 206px high it'd have to crop the image would it not?

**Comment by Kris-B** [comment]
If the gallery height is set to 200px, then the 206px height image will be resized to 200px height. It's width will also be changed to respect the image height/width ratio. So the full image will still be displayed (if cropping would be applied, then part of the image would not be displayed).

But note that this is theoretical, and that each gallery line height may vary, and may be less height than the defined gallery height.

**Comment by Kris-B** [comment]
I'll close this issue for now, but open it again if you still have any question about the justified layout.
