### ISSUE TITLE
HTML markup inside data-ngdesc not work for nanogallery2 but work v1.0

### ISSUE THREAD

**Issue by macauhome** [nanostudio-org/nanogallery2#286]
I want to make some html markup inside ***data-ngdesc*** like `</br>,` it is work on nanogallery but not nanogallery2.

***exapmle***
`<a href='./3741.jpg' data-ngthumb='./3741.jpg' data-ngid='1' data-ngalbumid= '1002' data-ngdesc='bli bli ba ab </br> bli bli'>title is here</a>`

**Comment by Kris-B** [comment]
By default, HTML tags cannot be used in titles and descriptions of images (to avoid XSS (cross site scripting) vulnerability).
To enable HTML tags, set the option ```allowHTMLinData: true```

**Comment by Kris-B** [comment]
@macauhome did this fix your issue ?

**Comment by macauhome** [comment]
Yes,it's worked,thanks so much.

在 2020年10月3日 週六 04:17，Christophe Brisbois <notifications@github.com> 寫道：
