### ISSUE TITLE
How can open viewer with script nanogallery2('openViewer') not exist ?

### ISSUE THREAD

**Issue by wobility** [nanostudio-org/nanogallery2#287]
Hello,

I'm wondering if a way exist to open viewer with code like 

> $('#my_nanogallery2').nanogallery2('openViewer');

A function exist to close the viewer but not to open it. This function works well. 

> $('#my_nanogallery2').nanogallery2('closeViewer');

Any way to open the viewer simply ?

note: It's an awesome Script ! Thanks a lot to the maker.

**Comment by Kris-B** [comment]
Use the API method ```displayItem```.

To open the viewer, use the syntaxe: ```$('#your_nanogallery2').nanogallery2('displayItem', 'albumID/imageID');```

**Comment by wobility** [comment]
Thanks for your reply, I saw this syntax but I don't understand how can use it because I found no information about how to set albumID on the documentation... Do you know how we can set albumID ?

**Comment by Kris-B** [comment]
If you didn't set an albumID, use the default value: ```0```
