### ISSUE TITLE
removeIf polyfill breaks AngularJS in weird ways

### ISSUE THREAD

**Issue by bhartvigsen** [nanostudio-org/nanogallery2#288]
https://github.com/nanostudio-org/nanogallery2/blob/96d9c366ba60f9e69001533c5c5dc3e4a86f4d03/src/jquery.nanogallery2.core.js#L7902

I spent all morning on this. After opening nanogallery2 my AngularJS (1.2.15) routes would no longer load their controllers when navigating to a new page.

I have no idea why this breaks old AngularJS, and I don't know that you necessarily need to add a fix, but I figured if I opened an issue anyone searching for this problem might find it on a search engine.

So if you are hopelessly searching why your AngularJS controllers no longer work / stop working after having a nanogallery2 session open, it's due to this polyfill section causing some sort of a conflict. Just remove it.

**Comment by Kris-B** [comment]
@bhartvigsen thanks for reporting this issue! I'll fix it in the next release.

**Comment by Kris-B** [comment]
fixed in v3.0.4 - thanks for your contribution
