### ISSUE TITLE
How to make items(photos) number always show up in album

### ISSUE THREAD

**Issue by macauhome** [nanostudio-org/nanogallery2#290]
Hi,
 Every album has a items number show up at the corner when cursor hover , is it possible make it always appear no matter the cursor in or out the album and how to change the number style ,thanks.

**Comment by macauhome** [comment]
I found the solution, using thumbnailHoverEffect2 and  thumbnailToolbarAlbum :{ topRight : 'counter'}  can met the require.

**Comment by Kris-B** [comment]
Yes, that's the right way.
