### ISSUE TITLE
Play video from Facebook API ?

### ISSUE THREAD

**Issue by krabouilleur** [nanostudio-org/nanogallery2#291]
Hi !
Is it possible to play video from facebook API with link like this ? : [https://video-cdg2-1.xx.fbcdn.net/v/t42.9040-2/119317278_326760191913180_4863825994773497448_n.mp4?_nc_cat=109&_nc_sid=985c63&efg=eyJybHIiOjkwMCwicmxhIjo1MTIsInZlbmNvZGVfdGFnIjoibGVnYWN5X3NkIn0%3D&_nc_ohc=mM-vP_8ecCoAX-QeJ5j&rl=900&vabr=500&_nc_ht=video-cdg2-1.xx&oh=cc880096dc44acdba5f4212670114e93&oe=5F8D0643](https://video-cdg2-1.xx.fbcdn.net/v/t42.9040-2/119317278_326760191913180_4863825994773497448_n.mp4?_nc_cat=109&_nc_sid=985c63&efg=eyJybHIiOjkwMCwicmxhIjo1MTIsInZlbmNvZGVfdGFnIjoibGVnYWN5X3NkIn0%3D&_nc_ohc=mM-vP_8ecCoAX-QeJ5j&rl=900&vabr=500&_nc_ht=video-cdg2-1.xx&oh=cc880096dc44acdba5f4212670114e93&oe=5F8D0643)

**Comment by krabouilleur** [comment]
I've found the solution by changing the source code

**Comment by Kris-B** [comment]
hi @krabouilleur 
can you please share your solution ?

**Comment by krabouilleur** [comment]
> 
> 
> hi @krabouilleur
> can you please share your solution ?

Just in the js file there is a "mediaList"  with daylimotion, youtube.....

Just add "facebook" and the regex for the video api
