### ISSUE TITLE
Position "label" below image in lightbox?

### ISSUE THREAD

**Issue by PA-ThePhilosopher** [nanostudio-org/nanogallery2#295]
Hello,
I was wondering if it is possible to position the "label" just below the image in the lightbox (this is where the eyes tend to land easily). Currently, "viewerTools" only allows for "topleft" and "topright" placement.

Thank you!

-Davide

**Comment by Kris-B** [comment]
Hi Davise, you should use the```viewerToolbar``` for this, instead of the ```viewerTools```. The same items can be used for both.

**Comment by PA-ThePhilosopher** [comment]
> viewerToolbar

Perfect, thank you!
