### ISSUE TITLE
How difficult would this styling be to achieve?

### ISSUE THREAD

**Issue by PA-ThePhilosopher** [nanostudio-org/nanogallery2#297]
Hello,
I would like to change the styling a bit to resemble the screenshot below, adding a white background behind the image, with the title/description immediately below the image. Is this something that can easily be done? Or would significant changes to core code be necessary? Thank you

![ice_screenshot_20201024-112857](https://user-images.githubusercontent.com/56554751/97085584-548e2900-15ec-11eb-936a-ade8dd5a5f1f.jpeg)

-Davide

**Comment by Kris-B** [comment]
Not sure that this can be achieved to 100%, you can try to change the CSS file. If you really want this layout, you may replace the internal lightbox with the one which you took the screenshot from.

**Comment by Kris-B** [comment]
No feedback, so I'm closing this issue for now. You may open it again if needed. Thanks.
