### ISSUE TITLE
Thumbnail for videos not working

### ISSUE THREAD

**Issue by PA-ThePhilosopher** [nanostudio-org/nanogallery2#299]
Hi,
Sorry for al the questions. I noticed that when I set a thumbnail for a video, I do not see the thumbnail. But when I change the SOURCE video to an image, then the thumbnail works. When I change it back to a video, then the thumbnail no longer appears again.

Do thumbnails just not work with videos, or am I missing some setting somewhere?

Thanks,

Davide

**Comment by Kris-B** [comment]
Can you share your settings ?

**Comment by Kris-B** [comment]
Fixed in v3.0.5
