### ISSUE TITLE
add dynamically items for cascading display

### ISSUE THREAD

**Issue by krabouilleur** [nanostudio-org/nanogallery2#301]
Hi,
I have a gallery with a display in "cascading mode"

so, the settings: 
- "thumbnailHeight": "auto"
- "thumbnailWidth": 300

All works. But, then, I add dynamically an item by this:
```
var newItem = NGY2Item.New(instance, "the_name", "the_desc", theId, theAlbumID, 'image', '');
newItem.thumbSet( "the_path", 300, 0);
newItem.setMediaURL(  "the_path", 'img');
newItem.addToGOM();
```

the problem is the height of thumbs : there is no more cascading (it seems the "thumbnailHeight: "auto") is no more used), all images have the same height.

Everyone can see the problem ?
(in the method "thumbSet" it's no possible to set "auto" to the height, it's a number so I write => 0 for the height)

**Comment by krabouilleur** [comment]
for example : [https://codepen.io/krabouilleur/pen/qBNKoyq](https://codepen.io/krabouilleur/pen/qBNKoyq)

At start, the first image is loaded "normally" (landscape)
if you click on "add 1 image" multiple times, all images have the same size : the other image has never the "lanscape" mode even if it's the same image

**Comment by Kris-B** [comment]
When adding items dynamically you'll have to specify the real (or natural) size of the thumbnail image you're adding.
So, to add an item with a thumbnail which image size is 300 x 200 pixels, you should use ```newItem.thumbSet( "the_path", 300, 200);```.
For an item with a thumbnail which iamge size is 150 x 400 pixels, you should use ```newItem.thumbSet( "the_path", 150, 400);```.

It's important to make the difference between the gallery thumbnail size and the size of each thumbnail displayed in the gallery.
Gallery thumbnail size is defined in the gallery's options.

**Comment by AntSmith60** [comment]
Hi, sorry to add this here but I opened a ticket over 1 month ago and have had no response at all - I wonder if I have done something wrong; how do I open a ticket in a way that gets it seen? Can either of you help at all???

**Comment by Kris-B** [comment]
No feedback, so I'm closing this issue for now. You may open it again if needed. Thanks.
