### ISSUE TITLE
Global css background-color hides thumbnails.

### ISSUE THREAD

**Issue by alainpluquet** [nanostudio-org/nanogallery2#303]
Great tool ! Nevertheless when the css of the document contains a global background-color property, thumbnails are hidden.
For instance, in you CodePen https://codepen.io/Kris-B/pen/LyBwvN , if you add in the css zone a statement like 
 * {background-color:black;}
then the black background hides the three thumbnails.
Any hint to solve that ? Thanks.

**Comment by Kris-B** [comment]
Can you be more precise and provide a working example ?

**Comment by Kris-B** [comment]
No feedback, so I'm closing this issue for now. You may open it again if needed. Thanks.
