### ISSUE TITLE
pageChanged event

### ISSUE THREAD

**Issue by JonMerlevede** [nanostudio-org/nanogallery2#31]
The `pageChanged.nanogallery2` event is fired when moving to the previous or the next page, but not when moving to a specific page (by clicking on a specific rectangle/page number/...). This is also the case in the demo gallery at http://nanogallery2.nanostudio.org/api.html. Is this intended behavior, and if so, can we get an event that is also fired when moving to a specific page?

edit: `itemSelected.nanogallery2` and `itemUnSelected.nanogallery2` are also not triggered by calls to `itemsSetSelectedValue`. Is this intentional?

**Comment by Kris-B** [comment]
I'll fix the pageChange event

for itemSelected and itemUnSelected, it's intentional but I must admit I was not sure about it... what's your opinion?

**Comment by Kris-B** [comment]
pageChange fixed in v1.2.1 - https://github.com/nanostudio-org/nanogallery2/releases/tag/v1.2.1

**Comment by JonMerlevede** [comment]
Thanks, it works now!

For `itemSelected` and `itemUnSelected`, I did expect the event to trigger. Now that I think about it this might cause more problems - e.g. when selecting multiple images simultaneously using JavaScript, do you trigger the event once or multiple times? What when unselecting and selecting different images at the same time? My opinion is that the behavior is clear as it is; I do think it would be a good idea to add this to the documentation.

**Comment by Kris-B** [comment]
documentation updated
thanks
