### ISSUE TITLE
debugger; sentence uncommented stops web load.

### ISSUE THREAD

**Issue by Dioniggio** [nanostudio-org/nanogallery2#311]
Hello! 

In file jquery.nanogallery2.js there's a "debugger;" sentence uncommented.

Just comment it to prevent the browser to stop loading the page when developer tools window is open.

Thanks!

**Comment by Kris-B** [comment]
Hi @Dioniggio, thanks for reporting this issue !
Will be fixed in the next release.

**Comment by Kris-B** [comment]
Fixed in v3.0.5
