### ISSUE TITLE
Quickstart page has a bug

### ISSUE THREAD

**Issue by mayurjobanputra** [nanostudio-org/nanogallery2#312]
On https://nanogallery2.nanostudio.org/quickstart.html, Step 2, their is a syntax error on the last line. 

Currently says: <script  type="text/javascript">src="jquery.nanogallery2.min.js"></script>
Should say:      <script  type="text/javascript" src="jquery.nanogallery2.min.js"></script>

**Comment by Kris-B** [comment]
Fixed.
Thanks for the report!
