### ISSUE TITLE
Thumbnails not showing for youtube vids

### ISSUE THREAD

**Issue by 1danzi** [nanostudio-org/nanogallery2#314]
I created an album via using the HTML method. I have a link to a youtube video that is private. The video plays fine but the thumbnail does not show. When I set the permissions in youtube to public the thumbnail shows but I want the video to remain private. So can this be fixed because I tried manually setting a thumbnail with the same method I would use to set a image to see if it would work but It didn't for youtube videos.

**Comment by Kris-B** [comment]
Thanks for reporting.
Fixed in v3.0.5

**Comment by Kris-B** [comment]
Closed due to inactivity. If you still need help, you can continue to use this case and I'll open it again. Thanks.
