### ISSUE TITLE
Video file extension is case sensitive

### ISSUE THREAD

**Issue by rrrpdx** [nanostudio-org/nanogallery2#319]
**Describe the issue**  
I was trying to play videos, and they display a "spinner" without playing. The root cause is that my video was named, for example, XYZ.MP4... When you check for file types for selfhosted videos, you only check for "mp4" (line 6178), so "MP4" does not match, and it tries to display it as an image instead of video.

**Comment by Kris-B** [comment]
fixed in v3.0.5
