### ISSUE TITLE
getItems

### ISSUE THREAD

**Issue by JonMerlevede** [nanostudio-org/nanogallery2#32]
The `getItems` API command does not seem to be working. It does not return a list of items, but rather the jQuery element containing the entire gallery.

**Comment by Kris-B** [comment]
actually, the documentation is not up-to-date...

You should use the API method `data`, which returns a pointer to all items, to the current displayed gallery elements, and to the lightbox.

Example to get the selected items:
```
var items=$('#your_nanogallery2').nanogallery2('data').gallery.items;
items.forEach( function(curr) {
  if( curr.selected === true ) {
    console.dir(curr);
  }
});
```

**Comment by JonMerlevede** [comment]
Thanks!
