### ISSUE TITLE
nanogallery2 is too slow on loading photos from google

### ISSUE THREAD

**Issue by spyros2017** [nanostudio-org/nanogallery2#33]
-loading images from google photos is realy slow, especially when they are too big.. >5mb
-You could say, please do not  upload too big or original photos on google photos, or resize them first with a resize tool, but i want them for safety reasons in ORIGINAL state  uploaded. 
-I want to have the originals on google photos but serve lower quality and size on the gallery to speed up things.
-Is it possible;

**Comment by Kris-B** [comment]
hey @spyros2017 
The equation is quite simple: upload big images = download big images ;-)
Did you already try to set `viewerZoom` to `false`?
Disabling the zoom will download the image with the same resolution as the user's screen.

**Comment by Kris-B** [comment]
Please do not put quotes around false

**Comment by Kris-B** [comment]
no feedback, so I'm closing this issue but you may open it again if needed
