### ISSUE TITLE
Fail to load the content on IE 11

### ISSUE THREAD

**Issue by panglivlal** [nanostudio-org/nanogallery2#332]
**Describe the issue**  
When i try to use IE to open your website i found out fail to load the content. Is It mean this library not compatible on IE ?

 
![Capture](https://user-images.githubusercontent.com/10703311/107103999-daac4380-685a-11eb-89ee-b17bc92cca46.JPG)

**URL of your page**  
https://nanogallery2.nanostudio.org/documentation.html

**Comment by Kris-B** [comment]
IE11 is too outdated...
