### ISSUE TITLE
Image description

### ISSUE THREAD

**Issue by ViKoCZ** [nanostudio-org/nanogallery2#34]
I'm trying to solve two issues with image description in my project with nanogallery 2 using Google photos:

1) Is possible to use image description from EXIF instead of the one coming from google?

2) Currently if google description is empty, nanogallery2 replaces it with filename. I want to display description only if there is one, I don't want to display filename. So far I did it (and it works) by removing condition in the javascript section //Get the description:
`if( itemDescription != '' )`
but I wonder if there is some "clean" way doing it in configuration.

Thanks a lot for any recommendation :-)

**Comment by Kris-B** [comment]
1. I could not retrieve the EXIF description in the Google data.
It's difficult to use the EXIF data from the image itself as it would be available only after the image if fully downloaded.

2. Actually, this is a bug...
From the next release, by default the title will remain empty if not defined.
You can still display the filename using the variables `%filename`, `%filenameNoExt`

**Comment by Kris-B** [comment]
point 2 is fixed in v1.3.0
https://github.com/nanostudio-org/nanogallery2/releases/tag/v1.3.0
