### ISSUE TITLE
Drop jQuery as dependency

### ISSUE THREAD

**Issue by andimg93** [nanostudio-org/nanogallery2#344]
Hello,

is there any plan to drop jQuery as dependency? Bootstrap5 hast it and as i use it for all new projects, it would be fine to stay plain - So how does it look here?

**Comment by Kris-B** [comment]
Any help is welcome for this task: are you interested ?

**Comment by andimg93** [comment]
I would really like to do that, although I am currently working on a side project, and therefore don't have the time for any more right now.
