### ISSUE TITLE
Can nanogallery2 be used to create a static gallery

### ISSUE THREAD

**Issue by mhucka** [nanostudio-org/nanogallery2#349]
**Describe the issue**  
I've searched the user guide but cannot find an answer: can this be used to create a purely static gallery, meaning one that does not need an http server? For example, can I create a gallery out of images stored in a folder on a disk, viewable by simply opening a web page in a web browser?

**CODE PLAYGROUND**  
(not relevant)

**URL of your page**  
(not relevant)

**Comment by Kris-B** [comment]
This is not possible : one js running in a browser can not natively access a folder on a disk.

**Comment by mhucka** [comment]
Thanks for the super quick response. May I suggest adding some clarification to the documentation somewhere, to mention that a server is needed? (Or, conversely, that this is not a static gallery generator.) It might save people in the future asking about it :-)

**Comment by Nekkowe** [comment]
I think there's some confusion here.
 
Nanogallery2 creates "static" galleries in the sense of "static hosting" / "static websites", content that's pre-prepared (as opposed to created _"dynamically"_ on the fly) without any server-side code being required. 

**For example, you can put nanogallery2 galleries on Github Pages, Neocities etc. just fine.**

> meaning one that does not need a http server

This part of your question is a little confusing to me. Are you asking if nanogallery2 can create galleries for offline use...? Even static websites do still need a web server, that's what makes them websites.

**Comment by mhucka** [comment]
> Even static websites do still need a web server, that's what makes them websites.

Are you aware that you can view local HTML pages in a browser without a web server?

As far as I can find, nowhere in the README does it explicitly state it's a gallery in the sense of a static website. My suggestion is simply to make it explicit rather than implicit, because that would be better for clarity and discoverability.

**Comment by mhucka** [comment]
> Even static websites do still need a web server, that's what makes them websites.

"static gallery" ≠ "static website"

**Comment by Nekkowe** [comment]
Okay then, since there's some kind of misunderstanding somewhere, what do you mean by "static gallery" if not a gallery on a static site?
