### ISSUE TITLE
Auto-hide address bar in mobile browsers

### ISSUE THREAD

**Issue by JonMerlevede** [nanostudio-org/nanogallery2#35]
It would be nice if the lightbox opened fullscreen on mobile browsers or if the address bar got hidden automatically when viewing pictures in the lightbox. The address bar takes up quite a lot of space, especially when viewing pictures in landscape mode.

(I haven't done this myself, but it seems like this could be achieved by either a call to `requestFullscreen`, which is not universally supported, or by top-padding the page a bit and automatically scrolling down using JavaScript.)

**Comment by Kris-B** [comment]
You can force open the lightbox in fullscreen with the option `viewerFullscreen`

You can also add the fullscreen button in one of lightbox toolbar -> the user can then easily choose to switch to fullscreen

**Comment by JonMerlevede** [comment]
I feel a bit stupid now; I didn't see the fullscreen button and should have checked better before posting. Fullscreen option works perfectly!

Thanks for the tip for customising the toolbar though, I'd probably have missed that.

**Comment by Kris-B** [comment]
:-)
Don't worry, I'm happy I could help
