### ISSUE TITLE
A way to load Flickr Collections via the name of collection and not name of Album/photos

### ISSUE THREAD

**Issue by GYama-Idevops** [nanostudio-org/nanogallery2#350]
I didn't really see this functionality but I think it would be really helpful to have the Flickr integration have an option to call on Collections via keyword vs calling on albums with keywords so that you can further organize what shows up in each gallery instance. This would be really helpful to people creating image galleries for products for example, or specific art exhibits or etc where there are several pictures of one thing/category/event and it would help to not have to have the album name the required tagged element. i.e. if I wanted to include all images from my art shows and each was subdivided into a specific event and each event had an album with several photos, etc. Just an idea anyway. Thanks for the gallery in general though, it's really great and well designed!

**Comment by Kris-B** [comment]
this is not possible as Flickr's API requests authentication to access collections
