### ISSUE TITLE
Clarification of galleryFilterTags usage

### ISSUE THREAD

**Issue by macsupport** [nanostudio-org/nanogallery2#36]
The information on how to setup `galleryFilterTags` is confusing, especially for self hosted images. It states that the options are the  possible values: false, true, 'title', 'description'. Could there be a clarification of how this works? It states I need to use a "string starting with @" but if I do that, I get my title text and and also @filter showing in the title text as well. I really don't want to see the @filter part, I just want to enable the filter itself.  Also, what is the difference between true and 'title' of "description'? If I set true, do I use title? An example would be very helpful. Thanks

**Comment by Kris-B** [comment]
for self hosted images:
- markup: use `data-ngtags`
- javascript: use the `tags` option

and here's a codepen example: http://codepen.io/Kris-B/pen/aWNXrN

**Comment by macsupport** [comment]
Thanks. One question is with the "Checkboxl" toggle. The appearance of the toggle icon would suggest it should toggle all items on/off, which it does not. It seems it should do this or if not, not show the toggle icon and say "Show All", etc. Most filters default to turning the filter on, which would show the filtered items rather than default to turning off? An example of this would be the way [isotope](http://isotope.metafizzy.co/filtering.html) filters items

**Comment by Kris-B** [comment]
To avoid translations, I prefer to use icons. Any idea for a better "show all" icon?

**Comment by neofighter** [comment]
Hello Kris,
can you provide codepen how to use galleryFilterTags with nanoPhotosProvider2 too?

**Comment by Kris-B** [comment]
Tags are now supported in nanogallery2 v1.4.0 and nanoPhotosProvider2 v1.0.0
Tags are defined in an external file for each image.

**Comment by macsupport** [comment]
Do you have documentation as to how to format the text file, location, naming, etc.?

**Comment by Kris-B** [comment]
it's explained on the nanoPhotosProvider github repository page: https://github.com/nanostudio-org/nano_photos_provider2

Juste create a file with the same name as the image, and replace the extension with `.txt`
In this file, you can set title, description and tags:
```
title= this is my title
description= this is my descritption
tags=tag1 tag2 tag3
```

**Comment by macsupport** [comment]
Not done thru nanogallery2.js? I thought there might be an option for use if a data attribute such as `data-ngtags` to be able to use directly rather than thru nano_photos_provider2?

**Comment by Kris-B** [comment]
Sorry...
Yes, you can use the attribute data-ngtags

Le 20 juin 2017 6:24 PM, "Mike Sozanski" <notifications@github.com> a
écrit :

**Comment by helmutkaufmann** [comment]
Is there a "ready to use" example for the use of nanogallery2 with nano_photos_provider2? My image sat ein sub-directories and all I want to do is display them. I

**Comment by Kris-B** [comment]
please check:
http://nanophotosprovider2.nanostudio.org/
and
http://nanogallery2.nanostudio.org/datasource.html#ngy2_npp2
