### ISSUE TITLE
Thumbnail title and description: HTML-Text formatting

### ISSUE THREAD

**Issue by ddm-studio** [nanostudio-org/nanogallery2#366]
**Describe the issue**  
We aren't able to format the title or description of our thumbnails using HTML-Tags. Currently, the HTML-Code isn't rendered... it's just being outputted raw.
Is there any possibility to do so? You can find the codepen below.

**CODE PLAYGROUND**  
https://codepen.io/ddm-studio/pen/wvqZxgo

**Comment by kerohk** [comment]
You may include `"allowHTMLinData": true` to allow customized HTML formatting.
I edited your codepen: https://codepen.io/kerokeroppi/pen/gOGYppW

**Comment by ddm-studio** [comment]
That's amazing, thank you!
