### ISSUE TITLE
Error using custom colors for colorSchemeViewer breaks nanoGallery2

### ISSUE THREAD

**Issue by macsupport** [nanostudio-org/nanogallery2#37]
I am getting an error, `TypeError: a is undefined` when using a custom color for `colorSchemeViewer`.

Using:

`var customColorViewer ={background:'#000',imageBorder:'none',imageBoxShadow:'none',barBackground:'rgba(4, 4, 4, 0.7)',barBorder:'0px solid #111',barColor:'#eee',barDescriptionColor:'#aaa'};` 

and `colorSchemeViewer: customColorViewer,`, I get the error and the viewer fails to open on click.

If I use `colorSchemeViewer: null,` I do not get an error and everything works as it should

**Comment by macsupport** [comment]
I still get an error with the recent update (1.2.2). `colorScheme` works but `colorSchemeViewer` gives an error when I use  `var customColorLightbox = {...`,  and then in nanoGallery2, `colorSchemeViewer: customColorLightbox`

**Comment by Kris-B** [comment]
v1.2.2 is not finished and not released...
I've uploaded a new source code, but only for test purposes

Stay tuned

**Comment by Kris-B** [comment]
can you please provide your full `customColorLightbox` definition?

**Comment by macsupport** [comment]
I get the error even when I am using your [default color scheme](http://nanogallery2.nanostudio.org/documentation.html#ngy2_colorschemes).
`var customColorLightbox = {
  background: '#000', imageBorder: 'none', imageBoxShadow: 'none',
  barBackground: 'rgba(4, 4, 4, 0.7)', barBorder: '0px solid #111', barColor: '#eee', barDescriptionColor: '#aaa'
}`

 and then

`colorSchemeViewer: customColorLightbox,`

**Comment by Kris-B** [comment]
actually, this should work with the v1.2.2 you downloaded....
what is you error message?

**Comment by macsupport** [comment]
It works with the current alpha version on GitHub. FYI, there was never an error message, the Lightbox would just not open when a thumb was clicked, although folders did open..

**Comment by Kris-B** [comment]
ok, thanks for the precision

**Comment by Kris-B** [comment]
fixed in v1.3.0
https://github.com/nanostudio-org/nanogallery2/releases/tag/v1.3.0
