### ISSUE TITLE
Full screen icon when opening in fullscreen

### ISSUE THREAD

**Issue by JonMerlevede** [nanostudio-org/nanogallery2#38]
When starting the lightbox in fullscreen using `viewerFullscreen: true`, the state of the full screen icon (viewerFullscreenOn / viewerFullscreenOff) does not get the proper value. The viewerFullscreenOn icon is shown; when exiting full screen mode, the viewerFullscreenOff icon is displayed.

**Comment by Kris-B** [comment]
Thanks for the report.
Will be fixed in the next version. It's not released, for now, bur you can see it in action on the homepage: http://nanogallery2.nanostudio.org

**Comment by Kris-B** [comment]
fix in v1.3.0
https://github.com/nanostudio-org/nanogallery2/releases/tag/v1.3.0
