### ISSUE TITLE
Go to next image via click on image in viewer

### ISSUE THREAD

**Issue by 3Darklight** [nanostudio-org/nanogallery2#39]
This used to work in nanogallery1, but doesn't anymore in v2.
I didn't find anything in the docs (not even a click event for images in the viewer).
Great gallery and update btw ;)

**Comment by Kris-B** [comment]
It's no more supported because in v2 you can double-click to zoom/unzoom.

I can try to implement it again, but there will be a delay (to check if it's not a double-click). Would this be acceptable for you?

**Comment by 3Darklight** [comment]
I see, makes sense.

Depending on how much time you have and how you want to handle it:
You could add two options like "clickForNext" and "doubleClickToZoom" with true/false?
Or add "click" and "dblClick" events for the lightbox/viewer so people can override those themselves?

Thanks in advance for anything you can implement ;)

**Comment by Kris-B** [comment]
click to go to next/previous is implemented on the homepage ( nanogallery2.nanostudio.org )
can you please check?

**Comment by 3Darklight** [comment]
Hmm, can't see or find anything to get it to work?
I opened the first gallery (Into the Wild) and clicked on the images in the viewer in Chrome & Firefox, but nothing happens?
Thanks for working on it already though ;)

**Comment by Kris-B** [comment]
sorry wrong file on the server...
can you please check again?

**Comment by 3Darklight** [comment]
Looks perfect, thanks for the update ;)

**Comment by Kris-B** [comment]
thanks for your feedback
the new version should be released next week

**Comment by Kris-B** [comment]
v1.3.0 just released
https://github.com/nanostudio-org/nanogallery2/releases/tag/v1.3.0
