### ISSUE TITLE
JQuery 3.6.3 Error on upgrade from JQuery 3.5.1

### ISSUE THREAD

**Issue by AntSmith60** [nanostudio-org/nanogallery2#393]
**Describe the issue**  
I tried to upgrade JQuery on my site from 3.5.1 to 3.6.3 after which attempting to open an image in the pop-up lightbox (not a gallery, just a single image) I got a Syntax Error reported in the console stating:

Uncaught Error: Syntax error, unrecognized expression: [data-nanogallery2-Lightbox

Reverting to JQuery 3.5.1 resolved the issue.

I don't actually need to update JQuery right now so I am more reporting this as FYI as thought you'd like to be aware if you are not already!

**CODE PLAYGROUND**  
I don't have one but here is the image tag where I noticed the issue:

<img loading="lazy" id="myImgimg0" class="myImg NGY2ThumbnailLightbox" alt="image illustrating Photographic Skill, The Book" title="image illustrating Photographic Skill, The Book" src="https://antsmith.net/framework/image-sizer.php?file=photos2022%2Fimages%2Fphotographic-skill.jpg&amp;curtain=&amp;rgb=ffffff&amp;v=1.091&amp;size=400" data-ngsrc="https://antsmith.net/framework/image-sizer.php?file=photos2022%2Fimages%2Fphotographic-skill.jpg&amp;curtain=&amp;rgb=ffffff&amp;v=1.091&amp;size=2048" data-nanogallery2-lightbox="{  &quot;viewerToolbar&quot;:   {        &quot;display&quot;:    false,       &quot;position&quot;:    &quot;top&quot;,       &quot;standard&quot;:    &quot;minimizeButton,label&quot;,      &quot;minimized&quot;:    &quot;minimizeButton&quot;      },   &quot;locationHash&quot;:   true,   &quot;viewerTools&quot;:     {       &quot;topLeft&quot;:   &quot;pageCounter, playPauseButton&quot;,      &quot;topRight&quot;:   &quot;custom2, fullscreenButton, closeButton&quot;      },   &quot;fnImgDisplayed&quot; : &quot;ng2_display_incidentals&quot;,  &quot;fnImgToolbarCustClick&quot; : &quot;ng2_cc_incidentals&quot;, &quot;icons&quot; : {    &quot;viewerCustomTool1&quot; : &quot;<i class='fas fa-info-circle'></i>&quot;,    &quot;viewerCustomTool2&quot; : &quot;<i id='myHeartincidentals' class='far fa-heart'></i>&quot; }}" srcset="https://antsmith.net/framework/image-sizer.php?file=photos2022%2Fimages%2Fphotographic-skill.jpg&amp;curtain=&amp;rgb=ffffff&amp;size=200 200w&amp;v=1.091,https://antsmith.net/framework/image-sizer.php?file=photos2022%2Fimages%2Fphotographic-skill.jpg&amp;curtain=&amp;rgb=ffffff&amp;size=320 320w&amp;v=1.091,https://antsmith.net/framework/image-sizer.php?file=photos2022%2Fimages%2Fphotographic-skill.jpg&amp;curtain=&amp;rgb=ffffff&amp;size=512 512w&amp;v=1.091,https://antsmith.net/framework/image-sizer.php?file=photos2022%2Fimages%2Fphotographic-skill.jpg&amp;curtain=&amp;rgb=ffffff&amp;size=1024 1024w&amp;v=1.091,https://antsmith.net/framework/image-sizer.php?file=photos2022%2Fimages%2Fphotographic-skill.jpg&amp;curtain=&amp;rgb=ffffff&amp;size=1536 1536w&amp;v=1.091,https://antsmith.net/framework/image-sizer.php?file=photos2022%2Fimages%2Fphotographic-skill.jpg&amp;curtain=&amp;rgb=ffffff&amp;size=2048 2048w&amp;v=1.091" sizes="100vw" width="400" height="570">

**URL of your page**  
The page with the above img tag is: https://antsmith.net/photography/photographic-skill/tag/skill
I have reverted to JQuery 3.5.1 so you won't see the issue replicated here

**Comment by Berenke** [comment]
It's just a typing mistake. Open the jquery.nanogallery(.min).js file in a text editor, and search this expression: "[data-nanogallery2-lightbox". In the first hit you will see there's the closing square bracket is missing. Insert it, save the file and voila! :-)

**Comment by aten-dev-avalade** [comment]
I also solved it myself before finding this report.
Just replace '[data-nanogallery2-Lightbox' with '[data-nanogallery2-Lightbox]'.
Hopefully the developer will release a new update soon, or someone could fork it and maintain it
The last commit was Feb 27, 2021, which is worrying.
