### ISSUE TITLE
Option to disable bottom thumbnails in lightbox?

### ISSUE THREAD

**Issue by SandroRiz** [nanostudio-org/nanogallery2#396]
Is there an option to not have the thumbnail in the bottom of a single displayed image? Sometimes on the phone it hides too much of the photo, expecially if the pictures has interisting details i lower part.

Thanks
Sandro
![Screenshot_20230515_100417_Chrome](https://github.com/nanostudio-org/nanogallery2/assets/7381657/076d0022-ec3b-492e-b8de-549ad5b19f95)

**Comment by AntSmith60** [comment]
I think _viewerGallery: none_ does this as part of the _data-nanogallery2-lightbox_ attribute within the HTML img tag for a single image lightbox, or within the _data-nanogallery2_ attribute of the containing div of a gallery...

So adding:
data-nanogallery2="{&quot;viewerGallery&quot; : &quot;none&quot;}"

to your id="nanogallery2" div

I think will work..! (careful with the quotes though)

**Comment by SandroRiz** [comment]
Works perfect in the initialization... thanks a lot
` <script>
                 jQuery(document).ready(function () {
                    jQuery("#nanogallery2").nanogallery2( {
                        // ### gallery settings ### 

                       viewerGallery : "none",

                        'viewerToolbar': {
                            'display': false,
                            'standard': 'label',
                            'minimized': 'minimizeButton, label, sharebutton, fullscreenButton'
                        },
                        viewerTools: {
                            'topRight': 'zoomButton, fullscreenButton, infoButton, shareButton, closeButton'
                        },     
                       viewerGallery : "none",
                        thumbnailBorderHorizontal: 0,
                        thumbnailBorderVertical: 0,
                        thumbnailHeight:  200,
                        thumbnailWidth:   'auto',
                        thumbnailLabel: { display : <%=displayLabel %>  },
                        fnPopupMediaInfo: myPopupInfo
                      });
                  });
     </script>`
