### ISSUE TITLE
Does it support integration of multiple google photo accounts.When Can we expect this feature

### ISSUE THREAD

**Issue by echinna31** [nanostudio-org/nanogallery2#4]

**Comment by Kris-B** [comment]
why aggregate multiple accounts in one gallery?

**Comment by echinna31** [comment]
In my website , I have a photo gallery and currently I'm feeding it from one google account. Sometimes it would be nice if I can add albums from another account without manually moving the photos to another account. It would even resolve the google storage limits. 

   Looping through the accounts and pushing it to the array and mapping the ids is not impossible.

**Comment by Kris-B** [comment]
Accessing to multiple Google Photos accounts in a unique gallery would impact performances. It would also impact museveral configuration settings in the gallery. So, at this time, I will not implement this feature in a near future.

In the meantime, you can implement multiple nanogallery2 galleries on one page.
