### ISSUE TITLE
Breadcrumb/No breadcrumb not working as demos in official site

### ISSUE THREAD

**Issue by ARomina** [nanostudio-org/nanogallery2#42]
Hi! I've just found this plugin and was browsing through the demonstrations, and found two that don't work. I'll post screencaps here.
![screenshot-nanogallery2 nanostudio org-2017-04-22-20-28-25](https://cloud.githubusercontent.com/assets/21130864/25309118/c3882868-279a-11e7-851e-be151a21dcd5.png)
![screenshot-nanogallery2 nanostudio org-2017-04-22-20-29-21](https://cloud.githubusercontent.com/assets/21130864/25309119/c38c643c-279a-11e7-938b-5fe2b244b899.png)

**Comment by Kris-B** [comment]
fixed.
many thanks!
