### ISSUE TITLE
Typos on homepage

### ISSUE THREAD

**Issue by ARomina** [nanostudio-org/nanogallery2#43]
Just some details :)

In demonstration part:

In Content Source>Self hosted:

> Self hosted images. Note the **uss** of the parameter "itemsBaseURL" to avoid full URL for each image and thumbnail.

In Content Source>Self Hosted - albums:

> Self hosted images. When usiung albums, IDs **muty** be assigned to each element (images and albums).

In Layouts>Cascading:

> Display an album the cascading layout. Label is positioned under the **thumbanil**. The thumbnail height is set to "auto".

In Gallery display modes>Pagination - numbers:

> Display 2 rows of thumbnails and numbers **bellow** to paginate. 

Last one also present in Pagination - dots

**Comment by Kris-B** [comment]
fixed.
many thanks!
