### ISSUE TITLE
Callback myImgToolbarCustDisplay not working

### ISSUE THREAD

**Issue by renebrenner** [nanostudio-org/nanogallery2#44]
I registered a callback (myImgToolbarCustDisplay) in my nanoGallery2 Javascript definition. However it seems that the callback is ignored. The alert(); is not popping up.

Please find attached an example on codepen:
https://codepen.io/anon/pen/PmmyZy

**Comment by Kris-B** [comment]
You need to define a custom button, like with:
` viewerTools:      { topRight: 'custom1,fullscreenButton,closeButton' }, `

here's an example: http://codepen.io/Kris-B/pen/GWpWBR

**Comment by Kris-B** [comment]
I'm closing this issue for now, you can re-open it if needed

FYI, callbacks in HTML Markup mode are supported in the just release v1.3.0 version
