### ISSUE TITLE
Lazy load for woocommerce tabs not working

### ISSUE THREAD

**Issue by Mayccoll** [nanostudio-org/nanogallery2#45]
Hi,
In woocommerce when i change tabs the images are not loading.
i have to do a little scroll.
Tnks

**Comment by Kris-B** [comment]
can you provide the URL of the page with this issue?

**Comment by Mayccoll** [comment]
It is in development.
Add an event to trigger the lazy load.

```js
jQuery("body").on('click', '.ui-tabs-anchor', function() {
    jQuery('html, body').animate({
      scrollTop: jQuery("#tab-model").offset().top-100
    }, 200);
  });
```

**Comment by Kris-B** [comment]
actually, you can use the refresh method

`$('#your_nanogallery2').nanogallery2('refresh');`

**Comment by Kris-B** [comment]
no much activity here, I'm closing this issue

you can open it again for additional info

**Comment by macsupport** [comment]
I am having this same issue when using ` $('#nanoGallery').nanogallery2('displayItem', albumId); `. It seems that a bit of scroll is needed to show the images, even when reloading a folder of images. I am assuming this is related to lazyloading. Is their an option to change the scroll threshold? Lazyloading seems very slow to me and I'm also not sure why images above  the viewport are removed and then have to be reloaded when one scrolls back up.
