### ISSUE TITLE
thumbnailHoverEffect2 issues, rotation issue

### ISSUE THREAD

**Issue by AYbarra2** [nanostudio-org/nanogallery2#46]
A few issues I’ve noticed while testing using Chrome on an Android device and using Developer tools on the desktop. 

When the internal viewer is opened, then the page is resized (for example by rotating a phone from landscape to portrait) and then the viewer is closed, the gallery does not display properly until there is a scroll event. 

Using thumbnailHoverEffect2: 'toolsAppear' only works on the first tool with class .nGY2GThumbnailIcons in the thumbnail.  So, if multiple icons are specified in thumbnailToolbarImage (e.g. topRight, topLeft), only one of them has the filter applied. The issue may be related to the function NGY2Item.prototype.CSSFilterApply, lines 
			    obj.$elt[0].style.WebkitFilter= v;
			    obj.$elt[0].style.filter= v;

On a touch/mobile device using thumbnailHoverEffect2 such as labelAppear75, opening and closing the internal viewer results in the thumbnail losing the hover effect.  But, a single tap on the same thumbnail will re-open the internal viewer without first displaying the hover effect (tested with touchAutoOpenDelay values of 0, and -1).

JSFiddle: [ https://jsfiddle.net/Aybarra/69t3jjLo/]( https://jsfiddle.net/Aybarra/69t3jjLo/)

**Comment by Kris-B** [comment]
Many thanks for reporting these issues with valuable details. 
I'll look at them and I'll come back quickly.

**Comment by Kris-B** [comment]
Should be fixed in v1.4.0
