### ISSUE TITLE
Re-instating features from nanoGALLERY

### ISSUE THREAD

**Issue by pjb493** [nanostudio-org/nanogallery2#47]
I have recently had to make the switch from 'nanoGALLERY' to 'nanogallery2' in order to continue using Google Photos for new albums. I've successfully set this up and my web page is now displaying new albums. Whilst I've come to accept some minor cosmetic changes to the gallery layout, there are some properties which I originally had which have now been deprecated, and fundamental aspects of my page's operation relied on these.

In particular, I'm referring to the `refreshSize` property. I won't try and explain why I needed this but it IS needed. Can you please either consider re-adding, at least, this property or giving me a method for manually adding it to my copy of the code?

Thanks

**Comment by Kris-B** [comment]
Did you check the `refresh` method?
`$('#your_nanogallery2').nanogallery2('refresh');`

**Comment by neofighter** [comment]
Hi pjb493,
the function you need is already in ng2.
I had to implement refresh script for my website too. Kris pointed me how to do this in ng1.
For ng1 my code was: $('#nanogallery').nanoGallery('refreshSize');
For ng2 the code is: $('#nanogallery').nanogallery2('refresh');
As you can see, I had to change the script a little bit.

**Comment by pjb493** [comment]
Much appreciated, it's working again now. I think I also had it as nanoGallery2('refresh') instead of nanogallery('refresh').
Thanks

**Comment by Kris-B** [comment]
I just noticed that the documentation was not complete
fixed
