### ISSUE TITLE
Browser Navigation Back to Base Album Doesn't Work

### ISSUE THREAD

**Issue by krkeegan** [nanostudio-org/nanogallery2#48]
I have enabled LocationHash and the browser Forward and Back buttons work well within an album.  But if I try to select the back button to go back to the base album list from an album, the URL changes but the content remains fixed.

**Comment by krkeegan** [comment]
In trying to create a workaround, I was also unable to get the API to respond to a call to the displayItem using the syntax:
`$('#your_nanogallery2').nanogallery2('displayItem', 'albumID');`

For anyone else with the issue, I inserted the following javascript in the header of my page to solve the problem temporarily.  It seems to work perfectly.  Adjust the reference to `#nanogallery2` to match the id you use:
```
    <script type="text/javascript">
        $(document).ready(function() {
          function pageChange(e) {
            var hash = window.location.hash;
            if (hash === ''){
              var instance = $('#nanogallery2').nanogallery2('instance');
              instance.GOM.albumIdx = 0;
              instance.Refresh();
            }
          }
          $(window).bind( 'hashchange', pageChange);
        })
    </script>
```

**Comment by Kris-B** [comment]
Fixed in v1.4.0

**Comment by krkeegan** [comment]
Confirmed, this works in 1.4.0.

**Comment by Kris-B** [comment]
Thx for the update
