### ISSUE TITLE
Search Within Album

### ISSUE THREAD

**Issue by AmrataRamchandani** [nanostudio-org/nanogallery2#49]
Hi ,
I tried using this $('#your_nanogallery2').nanogallery2('search', search_string); it successfully search Album Names,Is there any way to search keywords including images inside Albums ?

Also,I wanted to add appropriate message for user if the album with specified keyword is not found.How do i do it ?

**Comment by Kris-B** [comment]
Hi, this will be in v1.4.0

**Comment by Kris-B** [comment]
released with the new functions `search2` and `search2Execute`

**Comment by Kris-B** [comment]
codepen: https://codepen.io/Kris-B/pen/ryOMov
