### ISSUE TITLE
Album's not showing on Samsung devices

### ISSUE THREAD

**Issue by salsarapidoman** [nanostudio-org/nanogallery2#5]
I've two Samsung devices and the demo page http://nanogallery2.nanostudio.org/ shows no galleries.
See screen shot.
![2017-01-18 15 45 02](https://cloud.githubusercontent.com/assets/5639011/22070861/597b8928-dd95-11e6-918f-7d7b8f9fc406.png)
nanaGallery (original) does work.
I look forward to this being fixed as it's a great plugin

**Comment by Kris-B** [comment]
which Samsung devices? and which OS version?
thanks

**Comment by Kris-B** [comment]
I just made some tests.
Ok on:
- Galaxy S4 Android 4.4
- Galaxy S5 Android 4.4
- Galaxy Note 4 Android 4.4
- Galaxy Note 3 Android 4.3
But nor working on:
- Galaxy S5 mini Android 4.4
- Galaxy Note2 Android 4.1
- Galaxy S3 Android 4.1

I do not have any physical device, so it will not be so easy to find the origin of the issue...

**Comment by salsarapidoman** [comment]
I got the problem viewing with nanogallery2.nanostudio.org plus a page I created
on:
Galaxy S4 Android 5.0.1
Samsung Tab-Pro SM-T320 Android 4.4.2
I achieved everything necessary with the original version so I'm OK It's only to assist your development.
Alastair
My debug consol on the s4 says (see pic)
![2017-01-19 14 50 55](https://cloud.githubusercontent.com/assets/5639011/22111374/06c99f90-de57-11e6-8266-184f8d3026c6.png)

**Comment by Kris-B** [comment]
compatibility issue with the android stock browser
fixed in v0.9.2

**Comment by salsarapidoman** [comment]
Excellent thanks Kris :-)
Any plans to expand Nanogallery to include Instagram?

**Comment by Kris-B** [comment]
I'm not sure to be allowed to include Instagram. 
From their platform policy: `.... do not build a media viewer.`

https://www.instagram.com/developer/

**Comment by WebDragon** [comment]
Just following up to this, their [Platform Policy](https://www.instagram.com/about/legal/terms/api/) appears to have changed and no longer includes the above phrasing. 

In fact the opening paragraphs clearly state : "Finally, we provide the Instagram Platform to help broadcasters and publishers discover content, get digital rights to media, and **share media using web embeds**."

**Comment by edwardhaase** [comment]
Any plan now?
