### ISSUE TITLE
Thumbnail to navigate up not displayed correctly on mobile (Chrome on ASUS Zenfone 2)

### ISSUE THREAD

**Issue by rsieja** [nanostudio-org/nanogallery2#51]
This screenshot will simply demonstrate the issue:

![screenshot_2017-06-17-11-38-31](https://user-images.githubusercontent.com/5354958/27253810-d3bd3c4a-5351-11e7-9c07-526c8181f9e1.png)

**Comment by Kris-B** [comment]
will be fixed in the next release

**Comment by Kris-B** [comment]
beta available here: https://github.com/nanostudio-org/nanogallery2/tree/dev/dist

**Comment by Kris-B** [comment]
fixed in v1.5.0
