### ISSUE TITLE
Must press twice to open the lightbox or the album on mobile

### ISSUE THREAD

**Issue by rsieja** [nanostudio-org/nanogallery2#52]
It happens when displaying many Flickr albums or using hover effects. One press "activates" the effect, another one opens the image or album.

Using Chrome on ASUS Zenfone 2.

**Comment by Kris-B** [comment]
This is the default behaviour to see the thumbnail hover animation.
Use the option `touchAnimation` to change this, or the option `touchAutoOpenDelay` to define a delay to automatically open the thumbnail.

**Comment by rsieja** [comment]
Thanks! Decided to use `touchAutoOpenDelay` and it did.

**Comment by jackophil** [comment]
I still have to press twice on mobile device to open.
This is the code am usingi have used in HTML..                  

      <div id="nanogallery2" data-nanogallery2='{ "userID": "#XYZ", "kind": "google2", "google2URL": "#XYZ" ,"thumbnailWidth": "135", "thumbnailHeight": "100", "thumbnailL1Height": "auto" ,  "touchAnimation": "false"   }'>

**Comment by jackophil** [comment]
I was also able to solve this by setting  `"touchAutoOpenDelay": "0.0001"`

Wondering why ` "touchAnimation": "false"`  didn't work.

**Comment by Kris-B** [comment]
`"false"` is not `false`
`"false"` is not working because it is interpreted as a string by javascript
Please remove the quotes `"touchAnimation": false`
