### ISSUE TITLE
Data in the address bar

### ISSUE THREAD

**Issue by momonumana** [nanostudio-org/nanogallery2#53]
Hi, without clicking anything on the page, just after loading, data is added to the browser address bar:
mydomain.com/#nanogallery/721xxxxxxxx.../721xxxxxxxx...

Is this a bug? Can it be changed?

**Comment by Kris-B** [comment]
Hi, it's be design. It's used to support browser back/forward navigation and deep linking (each image / album has a unique url which can be shared).
This can be enable or disabled with the option locationHash

**Comment by momonumana** [comment]
Ah. Great. Thanks a lot for the explanation and answer!
