### ISSUE TITLE
Image zoom in lightbox

### ISSUE THREAD

**Issue by momonumana** [nanostudio-org/nanogallery2#54]
Is it possible to set the initial image zoom to 100%? At the moment the images are shown quite small and I need to zoom in every time.

**Comment by Kris-B** [comment]
already asked in #24

**Comment by momonumana** [comment]
I don't think it is the same question. I do not ask for stretching. There must be a rather easy way to display the image with width:100%. I can overwrite the style sheet to do this, but then the zoom buttons and pinch to zoom do not properly work anymore.

**Comment by momonumana** [comment]
Do you consider to reopen this issue?

**Comment by momonumana** [comment]
What is interesting are the demos.

here http://nanogallery2.nanostudio.org/demonstration.html it is showing the smaller version, but 
here http://nanogallery2.nanostudio.org/api.html when you click into full view it is zoomed in to full size.

**Comment by momonumana** [comment]
Actually even on the demo page it depends which category I select. Thumbnail hover effects always open small. Most others full size. All of them jump back when clicked on zoom.

**Comment by momonumana** [comment]
Do you consider reopening this issue? Or shall I create a new one?

**Comment by Kris-B** [comment]
demos are using 2 different data sources: Flickr and nanoPhotosProvider2
both data sources have the same images but not with the same resolution, so the different behavior in the lightbox

so you would like the images to be displayed with 100% width, this would mean that vertical photos would not be fully visible?

**Comment by momonumana** [comment]
Of course not. max-width and max-height should be 100%.

Look closely at the demos, they are not consistent. Also the small images have a higher resolution than initially displayed. 

And the zoom does jump back at the fully displayed images.

I really love this gallery, it's beautiful and great to use. I'd love to use it fully functioning as intended.

**Comment by Kris-B** [comment]
can you be more precise? which demos are not consistent?
thanks

**Comment by momonumana** [comment]
I mentioned two examples in a previous comment. 

Also my local installation using flickr always shows the pictures quite small, as I mentioned above it can be fixed with side effects using a css overwrite. 

Most examples on the official website show initially in 100% but if you zoom in it jumps into medium format.

**Comment by momonumana** [comment]
And thank you for looking into it! :)

**Comment by Kris-B** [comment]
the demonstration page has many examples, which one do you mean?

**Comment by momonumana** [comment]
"Thumbnail hover effects" shows small.  Most others full size.

**Comment by Kris-B** [comment]
behavior is consistent: images used in the demos do not have the same size.
Some are big, some are smaller
you cannot compare the behavior based on images which do not have the same resolution

**Comment by momonumana** [comment]
Well, look at the "Content source" category.

The first image of the flickr stream:
https://farm1.staticflickr.com/278/31460827252_36ca5cebd2_k.jpg 
width=2048 height=1363
is displayed in full size. When I click zoom in, it jumps to medium size.

The first image on at the self hosted:
http://nanogallery2.nanostudio.org/samples/berlin1.jpg 
width=1280 height=848
is display at about 50%. Open the image directly and of course 1280x848 will be quite full screen on most displays. In this case the zoom in works right.

The first image in the google album list:
https://lh3.googleusercontent.com/-bJ9TGHDbHoc/UZvctbwxzvI/AAAAAAAAEdE/4gmNdrdFI9UbiW-YV3EfhHlM8IQ3wOPywCHMYBhgL/I/DSC_0342.jpg
width=1600
height=1064
opens at about 75%. zooming in also jumps back first.

I tested it on Chrome and Safari.

**Comment by momonumana** [comment]
Also, just as a side note, on the website the flickr images with size _k are loaded. On my local installation it is _b (large).

**Comment by momonumana** [comment]
Hmm, the nanoPhotosProvider example seems to zoom in at full 100% only on first view. On the second one it shows the 100% with frame.

**Comment by momonumana** [comment]
Or another way of looking at it. For the Berlin 1 image in the self hosted sample, chrome inspections shows:
`640 × 424 pixels (Natural: 1280 × 848 pixels)`
I see it at about 50%. The image is not displayed at 100%.

**Comment by Kris-B** [comment]
sure, you have retina or another type of hi-dpi screen

**Comment by momonumana** [comment]
For a flickr image of the website sample: 1024 × 683 pixels (Natural: 2048 × 1366 pixels)
On my local installation: 601 × 401 pixels (Natural: 1000 × 667 pixels)
My actual div/window width is 1433.

**Comment by momonumana** [comment]
Yes I have a retina screen. But this should not matter at all. Look at what the browser calculates in my previous comments. Look at the possibility of fixing it with a css overwrite.

**Comment by momonumana** [comment]
Look at the jumping zoom. 

I don't know how to make the inconsistencies more obvious. 

When I load my local image that is displayed at 50% (601 × 401 pixels (Natural: 1000 × 667 pixels)) on flickr directly it shows at 100%, double the size than in nanogallery2.

**Comment by Kris-B** [comment]
it's not just a matter of CSS
if you want to contribute and to implement a solution in the code, I will be happy to help you

**Comment by momonumana** [comment]
Opening the Berlin 1 image in a new tab will show it bigger than my browsers inner window. But on the websites examples it shows at 640 × 424 pixels, really quite small.

**Comment by momonumana** [comment]
I'd be happy to help. But I don't know the code at all. But if you point me to the sections to look at I might have time in the following days.

**Comment by momonumana** [comment]
But please also reopen the issue, maybe someone else is happy to help too. I am not sure how much time I will have...

**Comment by Kris-B** [comment]
@momonumana
upscale is now implemented in the DEV branch (https://github.com/nanostudio-org/nanogallery2/tree/dev)

you can also check it on the main site: http://nanogallery2.nanostudio.org/index.html

**Comment by momonumana** [comment]
Thanks a lot Chris! It works great. But it is actually not what I asked for and I do not recommend putting it into master. Upscaling should be an option and not default behaviour. I did not argue for upscaling, but only for 100% display. The upscaling does make many pictures that are just a bit smaller than full size look, well, upscaled... Its not nice. Please, do not put this into the master branch. Only if its a non-default option. The images should not be upscaled, but shown with max-width/max-height: 100%, thus shown at their maximum size. This is how one expects it and it is experienced all over the web.

**Comment by Kris-B** [comment]
Upscaling is an option.
It's activated by default for now, but in the final release this will not be the case.
To enabled it: set value `upscale` to option `viewerImageDisplay`

Actually, what you want is to display the image without any zoom.
- If the image resolution is higher than the screen resolution, the image will not be fully visible, and the user will have to pan to see it.
- If the image resolution is lower than the screen resolution, the image will not be fit to the screen. it will be smaller.
Is that correct?

**Comment by momonumana** [comment]
Thanks, great that it is an option and won't be activated by default.

- If the image resolution is higher than the screen resolution, the image will not be fully visible, and the user will have to pan to see it.
No. I don't want the picture shown as width/height 100% but max-width/max-height 100%. There is a difference here. This will show an image to the maximum possible size without upscaling it and without going beyond its surrounding component size.

- If the image resolution is lower than the screen resolution, the image will not be fit to the screen. it will be smaller.
Yes

E.g. https://codepen.io/anon/pen/xrazEp

**Comment by Kris-B** [comment]
sorry, I don't follow you: this is the way images are handled in nanogallery2 (even before the upscale option).

Could it be that your problem is a retina screen issue?
On retina, images are displayed with half their width and height. This is be design to have a good quality on retina, if not, images would be a little bit blurred.

**Comment by momonumana** [comment]
Well, no and yes.

I do have a retina screen (as stated above). But please just look at the codepen I added above. If you set the max-width/max-height to 100% it all works perfect on my retina screen (except that the zoom buttons won't start at the correct level). 

This is independent of retina or not. If I watch the image through Lightroom, Preview, the browser or any application on macOS, it will always show the image in a proper size that is not the actual pixel size. macOS does its own upscaling. I don't know what is wrong in nanogallery, but I have never had such an issue with any other app, software, gallery etc. 

On my website I show those pictures outside of nanogallery and it is fine. Only in nanogallery are they shown half the size.

Also If I watch the images on flickr directly it all is well. But I wrote about this above.

**Comment by Kris-B** [comment]
I don't have a retina display. I can't see any difference on my screen... ;-)

Did you disabled orginal size in Flickr?

**Comment by momonumana** [comment]
:)

No. As I said it works with the css overwrite. The source image comes in the right size.

**Comment by Kris-B** [comment]
I may have found something
Can you give a try at this new version: https://github.com/nanostudio-org/nanogallery2/tree/dev/dist

**Comment by momonumana** [comment]
Thank you, but this does not seem to have a different effect for me than the production version.

**Comment by Kris-B** [comment]
could you try a new version?
https://github.com/nanostudio-org/nanogallery2/tree/dev/dist

**Comment by momonumana** [comment]
Still no difference.

I attached two screenshots. One the view on flickr, the other with nanogallery2 (prod and this dev version).

**Comment by momonumana** [comment]
Still no difference.

I attached two screenshots. One the view on flickr, the other with nanogallery2 (prod and this dev version).


<img width="297" alt="screen shot 2017-07-11 at 13 49 27" src="https://user-images.githubusercontent.com/29610198/28067196-83673244-6640-11e7-8887-ba58a4d233a9.png">
<img width="273" alt="screen shot 2017-07-11 at 13 48 41" src="https://user-images.githubusercontent.com/29610198/28067197-836898aa-6640-11e7-9240-424022f997ea.png">

**Comment by Kris-B** [comment]
screenshots are missings...

can you try to set the option `flickrSkipOriginal: false`

**Comment by momonumana** [comment]
I reposted with the screenshots... 

Still no difference with the` flickrSkipOriginal: false ` option.

**Comment by Kris-B** [comment]
can I have your Flickr user ID?

**Comment by momonumana** [comment]
148691806@N05

**Comment by Kris-B** [comment]
Your picture https://www.flickr.com/photos/148691806@N05/35289648061/sizes/l has a max size of 1000x667

For a sharp display on retina, the script needs to set the size to 500x333 (height and width / 2).
Maybe you prefer a blurry display?

**Comment by momonumana** [comment]
No, your assumption is not correct. It will not be blurry. See my screenshots. It is perfectly sharp like it is shown on flickr directly.

**Comment by Kris-B** [comment]
your screenshots are too small.....

**Comment by Kris-B** [comment]
what's your browser?

**Comment by momonumana** [comment]
Well, believe me that it is sharp when viewed "full size" like on flickr. They are only supposed to show how the image is displayed and that it is way smaller in nanogallery2. 

It is like this for Safari, Chrome and Firefox.

**Comment by momonumana** [comment]
If your assumption was correct than most images on the web would be way too small to view them with a retina display. It is not the case. You should not base your calculations on actual pixel count of the display, but on stylesheet and DOM definitions. I do not know the actual technical details of all this, but obviously web developers do not need to care about it when defining their page to be lets say 1000px wide. It will be fine on a retina display and won't look half as wide as on a "normal" resolution.

**Comment by momonumana** [comment]
Here again screenshots in higher resolution.

![screen shot 2017-07-11 at 18 37 51](https://user-images.githubusercontent.com/29610198/28079304-1a7f2f7a-6668-11e7-8133-f19e423d5df7.png)
![screen shot 2017-07-11 at 18 28 55](https://user-images.githubusercontent.com/29610198/28079214-bd3f6d2a-6667-11e7-9a75-79dddab5fc82.png)
![screen shot 2017-07-11 at 18 32 21](https://user-images.githubusercontent.com/29610198/28079215-bd6320d0-6667-11e7-8dd5-83cbc4a189ed.png)

**Comment by momonumana** [comment]
It actually looks a tiny bit blurry on the screenshots when you open them here, I guess because I resized them to reduce file size. Anyway it looks just fine in real.

**Comment by momonumana** [comment]
Btw. here is how to change the retina "simulation" in chrome, there is an option `devPixelsPerPx`: https://stackoverflow.com/a/17228146, this seems to how it is done to make resolutions compatible.

**Comment by momonumana** [comment]
And how to test a website for retina in chrome: https://uiux.cc/blog/a-wonderful-way-to-test-your-websites-for-retina-by-google-chrome-without-an-actual-retina-display/

**Comment by momonumana** [comment]
![screen shot 2017-07-16 at 13 22 18](https://user-images.githubusercontent.com/29610198/28247103-4a2c0c14-6a2a-11e7-9450-bb7a2449aff0.png)
![screen shot 2017-07-16 at 13 22 49](https://user-images.githubusercontent.com/29610198/28247104-4a2dabfa-6a2a-11e7-8fd0-c72b6589bd92.png)

At the top you can see an option `DPR`. There you can play with the device pixel ration after adding it to the bar. It can be added through the dropdown in the device toolbar.

**Comment by momonumana** [comment]
You may know all this. Trust me though that you do not need to resize the picture to make it sharp on retina. My real width is 2304, But my browser or screen.width is 1440. An image with this width is shown sharp filling the whole screen.

**Comment by Kris-B** [comment]
yes, there are several possibilities to simulate retina or other devices
my personal favorite is BrowserStack (https://www.browserstack.com/)

but impossible to check the image quality without a real retina screen....
