### ISSUE TITLE
npm doesn't work for me in vs 2015 t install nanogallery2

### ISSUE THREAD

**Issue by John-Blair** [nanostudio-org/nanogallery2#55]
PM> npm install nanogallery2
npm : npm WARN package.json nanogallery2@1.4.0 No repository field.
At line:1 char:1
+ npm install nanogallery2
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN packag...pository field.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by Kris-B** [comment]
I'm not sure to understand your issue: the "no repository field" is just a warning

**Comment by John-Blair** [comment]
The package did not install for me in visual studio I had to manually download from github. Just letting you know in case others have the issue. Great product! Thanks

Sent from my HTC

----- Reply message -----

**Comment by Kris-B** [comment]
hi @John-Blair 
I just changed the package.json file for npm
If you have the opportunity to test v1.4.1 in VS 2015, it would be nice to get your feedback
Thanks

**Comment by Kris-B** [comment]
I'm closing this issue, for now, open it again if it's not fixed for you

**Comment by John-Blair** [comment]
It's not closed... don't be so cheeku

Sent from my HTC

----- Reply message -----
