### ISSUE TITLE
Gallery does not show when a hidden tab is first opened

### ISSUE THREAD

**Issue by John-Blair** [nanostudio-org/nanogallery2#57]
I am using a bootstrap tab list and each tab has a nanogallery2 in it. When the second or subsequent tabs are initially opened the nano gallery does not display the images until a small page scroll is performed then it displays. Is there any way to force the nanogallery to display when the tab is first opened?
Thanks.

Sample code 

 <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#zac-child">Zac</a></li>
                <li><a data-toggle="tab" href="#claire-child">Claire</a></li>
                <li><a data-toggle="tab" href="#declan-child">Declan</a></li>
                <li><a data-toggle="tab" href="#cara-child">Cara</a></li>
                <li><a data-toggle="tab" href="#evan-child">Evan</a></li>
            </ul>

            <div class="tab-content">
                <div id="zac-child" class="tab-pane fade in active">
                    <h3>Zac</h3>
                    <div id="nanogallery3" data-nanogallery2>
                        <a href="/media/children/zac/1995zac.jpg" data-ngThumb="/media/children/zac/1995zac.jpg" data-ngdesc="">1995</a>
                        <a href="/media/children/zac/1996_zac.jpg" data-ngThumb="/media/children/zac/1996_zac.jpg" data-ngdesc="">1996</a>
                        <a href="/media/children/zac/1997zac.jpg" data-ngThumb="/media/children/zac/1997zac.jpg" data-ngdesc="">1997</a>
                        <a href="/media/children/zac/1998zac.jpg" data-ngThumb="/media/children/zac/1998zac.jpg" data-ngdesc="">1998</a>
                        
                        
                    </div>
                </div>
                <div id="claire-child" class="tab-pane fade">
                    <h3>Claire</h3>
                    <div id="nanogallery-claire" data-nanogallery2>
                        <a href="/media/children/claire/2004claire.JPG" data-ngThumb="/media/children/claire/2004claire.JPG" data-ngdesc="">2004</a>
                        <a href="/media/children/claire/2009claire.jpg" data-ngThumb="/media/children/claire/2009claire.jpg" data-ngdesc="">2009</a>
                        <a href="/media/children/claire/2011alan.jpg" data-ngThumb="/media/children/claire/2011alan.jpg" data-ngdesc="Claire's Dad Alan - on the left'">2011</a>
                    </div>
                </div>

                <div id="declan-child" class="tab-pane fade">
                    <h3>Declan</h3>
                    <div id="nanogallery-declan" data-nanogallery2>
                        <a href="/media/children/declan/2004declan.JPG" data-ngThumb="/media/children/declan/2004declan.JPG" data-ngdesc="">2004</a>
                        <a href="/media/children/declan/2010declan.JPG" data-ngThumb="/media/children/declan/2010declan.JPG" data-ngdesc="">2010</a>
                        <a href="/media/children/declan/2012b_declan.jpg" data-ngThumb="/media/children/declan/2012b_declan.jpg" data-ngdesc="">2012</a>
                        <a href="/media/children/declan/2012declan.JPG" data-ngThumb="/media/children/declan/2012declan.JPG" data-ngdesc="">2012</a>
                        <a href="/media/children/declan/2016declan.jpg" data-ngThumb="/media/children/declan/2016declan.jpg" data-ngdesc="">2016</a>

                    </div>
                </div>
                <div id="cara-child" class="tab-pane fade">
                    <h3>Cara</h3>
                    <div id="nanogallery-cara" data-nanogallery2>
                        <a href="/media/children/cara/2012cara.JPG" data-ngThumb="/media/children/cara/2012cara.JPG" data-ngdesc="">2012</a>

                    </div>

                </div>
                <div id="evan-child" class="tab-pane fade">
                    <h3>Evan</h3>
                    <div id="nanogallery-evan" data-nanogallery2>
                        <a href="/media/children/evan/2008evan.JPG" data-ngThumb="/media/children/evan/2008evan.JPG" data-ngdesc="">2008</a>
                        <a href="/media/children/evan/2016a_evan.jpg" data-ngThumb="/media/children/evan/2016a_evan.jpg" data-ngdesc="">2016</a>
                        <a href="/media/children/evan/2016evan.jpg" data-ngThumb="/media/children/evan/2016evan.jpg" data-ngdesc="">2016</a>

                    </div>
                </div>
            </div>

**Comment by John-Blair** [comment]
I've done a workaround for this:

1) On the tab identify the gallery in it e.g.

<a data-toggle="tab" href="#zac-child" data-gallery="#nanogallery-zac-child">

2) Handle the tab shown event and redisplay the nanogallery

$(function () {

    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        var target = $(e.target).attr("data-gallery") // activated tab
        $(target).nanogallery2('refresh');
    })
});

There is an annoying flash on redisplay of the tab, but at least the gallery now displays on tab open without needing to scroll.

**Comment by John-Blair** [comment]
The workaround is good enough for me. Thanks.

**Comment by Kris-B** [comment]
hey @John-Blair 
thanks for the update, but what is the "annoying flash on redisplay of the tab" ?

**Comment by John-Blair** [comment]
hi Christophe,


Each time 'refresh' is called on the gallery it flashes on my screen. I have to call refresh the first time the tab or panel is opened otherwise the gallery is invisible.



 $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        var target = $(e.target).attr("data-gallery") // activated tab
        $(target).nanogallery2('refresh');
    })





Thanks

John Blair


________________________________
