### ISSUE TITLE
Use base64 as img source

### ISSUE THREAD

**Issue by jlbmagic** [nanostudio-org/nanogallery2#58]
Howdy.
Forgive the basic-seeming question.
Is it possible to use a base64-encoded image as the src value in the JavaScript? What would the correct syntax be in that case?

Thanks

**Comment by Kris-B** [comment]
Hey,
You can use something like:

```
items:[
 {
   src:   'data:image/png;base64,iVBOR..........',
   srct:  'data:image/png;base64,iVBOR..........',
   title:  'test base64'
 },
 ......
]
```

please note that the property `itemsBaseURL` should not be set
