### ISSUE TITLE
Last image on self hosted

### ISSUE THREAD

**Issue by charly83** [nanostudio-org/nanogallery2#59]
Is it possible to show only the last image when I use the storage path (self hosted)?

Thank you!

**Comment by Kris-B** [comment]
I'm not sure to understand... can you give more details?

**Comment by charly83** [comment]
I want to display all the images of a folder on the webspace.
In your description you have an example (self hosted) where all the images in the source code must be named. (<a href="berlin1.jpg" data-ngthumb="berlin1t.jpg" data-ngdesc="">Berlin 1</a>)

Is it possible to select only the folder and then the script shows all or just the latest image(s).

**Comment by Kris-B** [comment]
It's not possible to read the content of a directory whithout an application on your web server.

Please check nanoPhotosProvider2 - https://github.com/nanostudio-org/nano_photos_provider2

**Comment by charly83** [comment]
Thank you, it works perfect!
