### ISSUE TITLE
nanogallery2 search ?

### ISSUE THREAD

**Issue by styelz** [nanostudio-org/nanogallery2#6]
Hello,

Love the new gallery!  I's there any way to pass a keyword for searching a flickr gallery album photos title and description or tags ?

I want to add a search box to my gallery page so visitors can do a keyword search on my photos and display them in an album view. I was thinking I would need to first generate a new/temporary album on flickr based on the keyword passed via flickr API, then get nanoGalley2 to display that album ?

Does anyone have any ideas ?

Thank you.

**Comment by Kris-B** [comment]
Hi, this is not possible at this time but it will be added.

**Comment by Kris-B** [comment]
as mentioned in stackoverflow (https://stackoverflow.com/questions/41775556/nanogallery2-keyword-search), this feature is available in v1.0.0

you may accept the response in stackoverflow in order to share it with other people

**Comment by AmrataRamchandani** [comment]
Hi ,
I tried using this $('#your_nanogallery2').nanogallery2('search', search_string);  in gallery but it doesn't work with Google Photos.
Is there any hack for it ?
