### ISSUE TITLE
Lightbox Gallery Icons are Asian Characters

### ISSUE THREAD

**Issue by theceejay98** [nanostudio-org/nanogallery2#61]
I'm not sure if this is a personal issue or something that's affecting many people, but when I first implemented nanogallery2, it was working flawlessly. However, at some point a few weeks ago all of the navigation icons in the lightbox are some form of an Asian language's characters but I had more pressing issues to work on so I didn't bother to worry about it.

I've tried it across multiple browsers to see if it was an issue with Chrome, but it seems to affect every browser. I am 99% sure I have not touched any code that would directly impact the gallery. Is there any explanation or fix for this?

Thank you guys so much and amazing work on this plugin!

**Comment by Kris-B** [comment]
can you provide the URL of your page?

**Comment by theceejay98** [comment]
Unfortunately the website I'm building is for internal use only so there's a login wall you won't be able to pass.

Here are some screenshots though!
![screen shot 2017-07-28 at 11 22 19 am 2](https://user-images.githubusercontent.com/24986386/28724171-26b7ad0e-7387-11e7-889c-510fcf1a0fe3.png)
![screen shot 2017-07-28 at 11 23 04 am 2](https://user-images.githubusercontent.com/24986386/28724174-2b551ffe-7387-11e7-8d7e-5369c7d62f9f.png)

**Comment by Kris-B** [comment]
please open the debugger tool (for Chrome: hit the F12 key), reload the page and see if you have any error

**Comment by theceejay98** [comment]
Yeah I've got four 404 errors from failed loading of the icons from the server. Here they are:

Failed to load resource: the server responded with a status of 404 (Not Found) ngy2_icon_font.woff2 

Failed to load resource: the server responded with a status of 404 (Not Found) loading.gif 

Failed to load resource: the server responded with a status of 404 (Not Found) ngy2_icon_font.woff 

Failed to load resource: the server responded with a status of 404 (Not Found) ngy2_icon_font.ttf

**Comment by Kris-B** [comment]
so now you have the origin of the issue: some files are missing, just upload them or correct their path.

**Comment by theceejay98** [comment]
My bad. For some reason I though I was embedding all of this from a CDN. 

Thanks for the help, sorry for bothering you guys!

**Comment by Kris-B** [comment]
;-)

**Comment by COTIGA** [comment]
Hi,
I have the same problem, Asian characters appear.
Should I open a new issue?
[The problem here](https://www.senegal-loisirs.com/10-galerie-photos.php)

**Comment by Kris-B** [comment]
the font files are missing (folder css/font)

**Comment by COTIGA** [comment]
They are
I deepened, I had a conflict with the CSS of the "icomoon"
`
[class^="icon-"], [class*=" icon-"]{font-family:'icomoon' !important;speak:none;font-size:3em;font-style:normal;font-weight:normal;font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}
`
I deleted
`
!important
`
And it's OK now.
Thanks

**Comment by ttbek** [comment]
@Kris-B  Is this in the documentation?  I didn't find the documentation to be very helpful in the install process, (was quite good on the how to use it though).  The examples on the site seem to include jquery and the minified javascript, and the one css file, but I didn't see anything explicitly mentioning which files one needs installed when self-hosting.  I do have it working now... but there was some guessing and checking.  

@theceejay98 Go Blue!
