### ISSUE TITLE
Android>chrome issues

### ISSUE THREAD

**Issue by elivne** [nanostudio-org/nanogallery2#62]
Hi Kris
My gallery is connected to Google Photos (thank you for earlier help! works well now).
I saw a few previous issues discussing android, I'm not sure this was addressed or answered yet: lightbox on android>chrome opens the images very small with a lot of black background. Zooming in is limited and hard to achieve. Any advice?

**Comment by Kris-B** [comment]
hi, maybe you can have a look at the DEV branch and check if the latest version resolves your issue
https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by elivne** [comment]
thanks - do you mean i should try to download the latest dev scripts, upload to my website and see how the gallery behaves? maybe can i link directly?

**Comment by Kris-B** [comment]
What kind of new issues?
Thanks

**Comment by elivne** [comment]
when i used the dev version (temporarily), cascading layout looked a little different (i noticed a large gap at some point, and a different arrangement in the last row - possibly as result of the above). also, the setting "colorScheme": { "thumbnail": {"borderColor": "rgba(x,y,z,1)"} } resulted in error because the new version supports a different syntax, if i understood correctly.

when i then reverted back to the master version, i linked to rawgit instead of the scripts i downloaded about a month ago, and then i realised the version i had was outdated (same number version but 2 weeks older than the date showing on the latest version) and it seems like the original problem i had with lightbox on android was already resolves then. I will keep checking though, because for some images the zoom is still very low initially, although none of the images are in such low resolution or poor quality. not sure this last sentence makes sense but this is the thought i had for why some images display fine and some not.
