### ISSUE TITLE
How to access list of photo items inside ProcessLocationHash()

### ISSUE THREAD

**Issue by ujjaldey** [nanostudio-org/nanogallery2#63]
Hi,

How can I access the list of images and their src attributes inside ProcessLocationHash() function? G.I seems to be showing 49 object (1 album and 48 images), but when I see G.I.length, it's showing only 1 (album).

Please help.

![image](https://user-images.githubusercontent.com/16843102/30246455-3b2a2c0e-9618-11e7-9edf-80c4452c4c42.png)

**Comment by Kris-B** [comment]
ProcessLocationHash() will check if the location hash has changed.
If yes, the ID of the item to display is extracted (album ID or album ID + image ID)
Then, this item will be loaded (if not already in memory) and displayed.

What are you trying to do?

**Comment by ujjaldey** [comment]
I am trying to enhance it so that it can accept html5Mode() urls like ../gallery/album1/photo1. So I needed to access the list of child links to extract and parse the file name (photo1.jpg).

I am able to achieve this by passing few extra parameters while creating the instance. You can check the demo here - http://v4.ujjaldey.in/gallery/streets/pwkdu. I'll share the code so that you have a look and enhance it further.
