### ISSUE TITLE
Double-tap on mobile devices

### ISSUE THREAD

**Issue by pidesign** [nanostudio-org/nanogallery2#64]
Is there any way to disable having the tools appear on initial tap of an album/image? Right now on a mobile device when you tap on an album we have the icon showing number of images in the album appearing in the upper right of the thumbnail, we'd prefer that it just go straight into displaying the album without having to tap the thumbnail again.

**Comment by pidesign** [comment]
Found the answer using touchAutoOpenDelay

**Comment by Kris-B** [comment]
thanks for the update

**Comment by rehanahmed38-38** [comment]
how do I define the following  to disable double click on mobile? 
touchAutoOpenDelay
