### ISSUE TITLE
How can I get an Image ID?

### ISSUE THREAD

**Issue by 314ortiz** [nanostudio-org/nanogallery2#66]
I'd like to get the image ID, i'm using something like that:

`<div id="ng2" data-nanogallery2>`
              ` @foreach ($photos as $photo)`
                `<a id="{{ $photo->id }}" href="{{ asset('uploads/'.$photo->path) }}" data-ngThumb="{{ asset('uploads/'.$photo->path) }}"> {{ $photo->image_name }} </a>`
              `@endforeach`
            `</div>`

How you can see, i'm "injecting" the id prop on that anchor.. How can I retrieve that ID when the gallery was build.

**Comment by Kris-B** [comment]
https://stackoverflow.com/questions/46346459/nanogallery2-how-to-get-the-image-id
