### ISSUE TITLE
First click on initialized gallery item when fnThumbnailOpen is overriden

### ISSUE THREAD

**Issue by NetsharpDEV** [nanostudio-org/nanogallery2#67]
I have overriden the fnThumbnailOpen function with my own and even then, every time gallery is initialized, first time I click on image it opens image and then my custom action is performed which shouldn't be the case.
Gallery is rendered in modal.

    $(document).ready(function () {

        $('#gallery').nanogallery2({
            thumbnailWidth: "auto",
            thumbnailBorderVertical: 0,
            thumbnailBorderHorizontal: 0,
            thumbnailSelectable: false,
            thumbnailLabel: {
                "display": false
            },
            thumbnailAlignment: "center",
            thumbnailOpenImage: true,
            galleryDisplayMode: 'pagination',
            galleryPaginationMode: 'numbers',
            galleryMaxRows: '3',
            fnThumbnailOpen: selectImage,
            galleryFilterTags: true
        })

        function selectImage(items) {
            var obj = items[0];
            $('#@(Model.ImageType)Key').val(obj.title);
            $('#@(Model.ImageType)Image > img').attr('src', obj.src);
            $('#modal-container').modal('hide');
        }

    });

**Comment by Kris-B** [comment]
which version are you using?

**Comment by NetsharpDEV** [comment]
nanogallery2 - v1.5.0 - 2017-09-07

**Comment by Kris-B** [comment]
this has been fixed in v1.5.0, but it seems the fix got lost....

I've just fixed the version in the DEV branch https://github.com/nanostudio-org/nanogallery2/tree/dev/dist
maybe you can check this one?

**Comment by NetsharpDEV** [comment]
Ok, then i will check out the dev branch :) thanks

**Comment by NetsharpDEV** [comment]
Still have the same issue

**Comment by Kris-B** [comment]
can you try again?

**Comment by NetsharpDEV** [comment]
Now it is working ok! Thanks man! 👍
