### ISSUE TITLE
destroy method didn't release hash change handler

### ISSUE THREAD

**Issue by azsane** [nanostudio-org/nanogallery2#68]
When using nano gallery2 ,I had to change gallery images from different api.
So I used $("#nanogallery2").nanogallery2("destroy") and then recontruct naively.

Everything is ok except that clicking on image doesn't show the lightbox.
And I digged a little into code,found that

In Destory method(line 1555)  
`
  jQuery(window).off('resize.nanogallery2.'+G.baseEltID);
  jQuery(window).off('orientationChange.nanogallery2.'+G.baseEltID);
  jQuery(window).off('scroll.nanogallery2.'+G.baseEltID);
`  

But in code(line 8949) where handler was binded  

` if( G.O.locationHash ) {
     jQuery(window).bind( 'hashchange', function() {
        ProcessLocationHash()});
     }}
`
Since locationHash was true by default ,destroy method didn't released the old hashchange event.
Open Image -> Change Hash -> hashchange fired -> close viewer by old gallery that should be destroyed.

Should hashchange handler also be released in destory?

**Comment by JonMerlevede** [comment]
Probably related to issue #56

**Comment by Kris-B** [comment]
thanks for these detailled informations!
I will fix it in the next release

and yes, it may be the same issue as #56

**Comment by raek11** [comment]
I hope you could fix this issue soon, it's important ... 
thanx

**Comment by Kris-B** [comment]
can you please check the latest beta version: https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by azsane** [comment]
@Kris-B I've tried the latest beta version ,the problem is solved.
Now lightbox can be shown after destruct & reconstruct.Thanks:)

**Comment by Kris-B** [comment]
final version released: https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.0.0

**Comment by Kris-B** [comment]
I'm closing this issue, for now, open it again if it's not fixed for you
