### ISSUE TITLE
Hide "nanoAlert" panel

### ISSUE THREAD

**Issue by macsupport** [nanostudio-org/nanogallery2#69]
I have `debug:false` yet I still see the black panel with error messages on the page (nanoAlert). Shouldn't this be something that can be toggled off with debug or at least be a separate  option to only show in the console.log rather than on the page itself? I'm not sure my users like seeing errors.
Also, When the specific error `nanogallery2: error: no image to process` shows, there is no error shown in console.log when `debug:true`. Why is that?

Mike

**Comment by Kris-B** [comment]
This panel is showed for blocking errors, when the gallery cannot be displayed.
Can you give more details about your use case?

**Comment by Kris-B** [comment]
I removed the error message on the black panel
you may check it in the DEV-branch

**Comment by Kris-B** [comment]
final version released: https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.0.0

**Comment by Kris-B** [comment]
no feedback since long time  - I'm closing this issue for now
open it again if you still have this issue
