### ISSUE TITLE
ReferenceError: ViewerInfoSet is not defined

### ISSUE THREAD

**Issue by macsupport** [nanostudio-org/nanogallery2#7]
Current version gives this error when image info button is clicked and the info modal is not activated.
Also noted on nanogallery2 web site.

````ReferenceError: ViewerInfoSet is not defined````

**Comment by Kris-B** [comment]
fixed in v0.9.2a: https://github.com/nanostudio-org/nanogallery2/releases/tag/v0.9.2a
thanks

**Comment by macsupport** [comment]
Oops, now getting this error:

       ReferenceError: ViewerInfoSet is not defined[Learn More]  jquery.nanogallery2.min.js:22:17360
	Ea/< http://nanogallery2.nanostudio.org/js/jquery.nanogallery2.min.js:22:17360
	n.event.dispatch http://nanogallery2.nanostudio.org/js/jquery-1.12.4.min.js:3:12392
	n.event.add/r.handle

**Comment by Kris-B** [comment]
did you test nanogallery2 homepage?

I didn't update it. done know.

**Comment by macsupport** [comment]
Sorry, I'm too impatient!

**Comment by Kris-B** [comment]
;-)
I was too slow...
