### ISSUE TITLE
overflow-x: hidden; not working after exit gallery

### ISSUE THREAD

**Issue by AlessandroZero** [nanostudio-org/nanogallery2#70]
Hi, I've a problem with horizontal scrollbar after exiting a gallery.
Opening a page set with:

body{
     background-color: black;
	 overflow-x: hidden;
     overflow-y: scroll;
}

and a nanogallery 2, all is working properly and hover the images on the right part does not trigger horizontal scrollbar appear even with the zoom effect on thumbnails.
However, after seeing an image and exit the lightbox, the horizontal scrollbar appears when hovering right side thumbnails.
Reloading the page fixes the problem until you open an image and exit lightbox again.

Example: http://zerodivider.com/vgart/asurawrath

The problem is present with nanogallery2 v 1.4 and 1.5.
I tried modifying the nanogallery2.min.css, without results, adding:

body{
	 overflow-x: hidden;
}

Thank you in advance

**Comment by Kris-B** [comment]
at this time, when the lightbox is closed, overflow is set back to the default value
I will change this behavior to set the value back to previous value
will be in the next release

**Comment by AlessandroZero** [comment]
Thank you.

Great work.

**Comment by Kris-B** [comment]
@AlessandroZero I still need some time to finalize the next version. In the meantime, maybe you can check the version in the DEV branch to see if this issue is correctly fixed? https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by Kris-B** [comment]
final version released: https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.0.0

**Comment by AlessandroZero** [comment]
Thank you
