### ISSUE TITLE
Unable to use nanogallery2 with requirejs

### ISSUE THREAD

**Issue by surabujin** [nanostudio-org/nanogallery2#71]
<img width="1268" alt="nanogallery-requirejs-issue" src="https://user-images.githubusercontent.com/2862761/31938392-17497144-b8c0-11e7-87d9-78893f7836e2.png">
Hi.

Is it a new trend to ignore collected and proved tools to load dependencies? I am talking about requirejs. You don't wrap your library inside requirejs "definition" as most JS libraries... And this is only part of the problem - much bigger issue - your own dependencies added directly into source your source code.

As result (see attached screenshot) - this is happened because tinycolor detect requirejs, and don't add itself into the window object. As far as I saw in your sources this is not first your "problem" with requirejs.

Are you going to solve compatibility with requirejs in correct way? Or you will comment out one more chunk of third party code stored into your sources?

**Comment by Kris-B** [comment]
Well, I made some modifications to the DEV branch. Maybe you can have a look at it and give some feedback.

Regarding the embedded libraries: it may not sound good but it has one big benefit: it's easy to use for non-expert people. I will not change it for now.
