### ISSUE TITLE
Config key 'album' is undocumented

### ISSUE THREAD

**Issue by envision** [nanostudio-org/nanogallery2#72]
I couldn't get the gallery to open a specific gallery/folder on startup by using 'openOnStart' config. Then I found that one example used 'album' config, and it worked! But this config is undocumented.

**Comment by Kris-B** [comment]
thanks for this, I'll update the documentation

**Comment by Kris-B** [comment]
it's documented on the content source page
https://nanogallery2.nanostudio.org/datasource.html
