### ISSUE TITLE
How to hook on window events to/or implement one picture slider

### ISSUE THREAD

**Issue by envision** [nanostudio-org/nanogallery2#73]
Is there a technical way to implement one picture slider?

This config already shows once image slider for a given album ID:

    $('#widget-gallery').nanogallery2({
        kind: 'google2',
        userID: '999',
        google2URL: '99',
        thumbnailHeight: 210,
        thumbnailWidth: 300,
        thumbnailBorderHorizontal: 0,
        thumbnailBorderVertical: 0,
        album: '99999999999999',
        galleryDisplayMode: 'pagination',
        galleryMaxRows: 1,
        galleryTheme: 'light',
        imageTransition: 'swipe',
        slideshowAutoStart: true,
        slideshowDelay: 3000,
        display: false,
        displayDescription: false,
        breadcrumbAutoHideTopLevel: true,
        displayBreadcrumb: false,
        hideIcons: false,
        breadcrumbHideIcons: false,
        thumbnailLevelUp: false
    });

But how can I make one picture album shower to act like a slider, that it would periodically change the viewed picture?

**Comment by Kris-B** [comment]
I'm not sure to understand your need, can you give me some more details?

**Comment by envision** [comment]
@Kris-B there is a difference between photo gallery/album and photo slider -kind of plugins... NanoGallery is one of the few photo gallery/album plugins that has nested folder navigation in-built. But NanoGallery seems to lack some customization options...

At least for this kind of need: Need to have a photo slider that shows just one photo at a time (from a specified folder) and changes/animates the transition to another photo. Like a regular photo slider plugin.

I did manage to tweak the configs so that only one photo is shown at a time from a specified folder in Google Photos. But there is no timer for swapping the photo. User would need to manually click pagination to swap the photo. You can see it live [here](https://karkku.fi/) that one small 300x250px widget (as you scroll down, it's the first on the third widget row when looking with a wide browser window)...

**Comment by Kris-B** [comment]
this usage seems to be a little bit out of the scope of this library
you may try the slider on gallery's last thumbnail (see option `thumbnailSliderDelay`) - https://nanogallery2.nanostudio.org/documentation.html#ngy2_gallery_thumbnails
