### ISSUE TITLE
link to the photo on flickr leads to photostream instead of album

### ISSUE THREAD

**Issue by MilanV** [nanostudio-org/nanogallery2#77]
When using flick backend, the link to the original photo on flickr (in the image toolbar, for example) leads to that photo in user's photostream. Instead, it should point to the album nanogallery took the photo from - so user has the same list of photos there.

**Comment by Kris-B** [comment]
good point
fixed in the DEV branch
you can check it: https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by MilanV** [comment]
Looks good, thanks!

**Comment by Kris-B** [comment]
:wink:
