### ISSUE TITLE
Feature/wish: images from >1 sources in the same gallery

### ISSUE THREAD

**Issue by MilanV** [nanostudio-org/nanogallery2#79]
If pictures from more "sources" could be in the same gallery, we could, finally, overcome incapabilities of original image services.
I know flickr the best so I take it as an example: although flickr provides several ways to collect photos (album, collection, gallery), there is no way to combine both my photos and photos of my friends together. For example one common gallery of photos from our weekend event.

Another step would be to be able to combine photos from different services into one nanogallery2 album: so I may merge photos from google with photos from flickr and with additional ones stored locally (in special cases).

I believe nanogallery2 is a great way to achieve this: it's data structures are well organized to allow this and then, the usage, is completely configured locally, at my side, so I do not need anything special from those services themselves.

What do you think, Kris?

**Comment by Kris-B** [comment]
This is an interesting idea, but not easy to implement.
I need to think a little bit about how to implement it...

**Comment by Kris-B** [comment]
feature has too much impact on the code
