### ISSUE TITLE
nanogallery2 not working in FF 57.0.1

### ISSUE THREAD

**Issue by pointout** [nanostudio-org/nanogallery2#80]
I have a nanogallery working in Chorme an Edge, but it is broken in FF 57.0.1.
All previewimages are overlaped on top of the page not clickable. And the div container for the previews shows the background of the images not horicontal aligned, but one below the other.

**Comment by JonMerlevede** [comment]
I suspect you'll have to provide more information. I'm using nanogallery2 v2.0.0 and FF 57.0.1 and my gallery is working fine!

**Comment by pointout** [comment]
Maybe you can take a look at:
https://www.kameraklub-linz.at/mitglied/doris-schwarz.html

**Comment by Kris-B** [comment]
I couldn't see any issue
can you provide a screenshot?

**Comment by pointout** [comment]
Galleryview:
![nanogallery2](https://user-images.githubusercontent.com/8960545/33523634-2d37ffd2-d80c-11e7-971f-fc8b98c30d24.JPG)

Viewer (#nanogallery/my_nanogallery/0/1):
![nanogallery2-viewer](https://user-images.githubusercontent.com/8960545/33523653-878f08a4-d80c-11e7-8ddd-b97bcd16cd85.JPG)

**Comment by pointout** [comment]
it seems to be a local problem. Just tested on a other machine with Firefox 57.0.1. There it worked. Thanks for helping. I'll try to find out what's wrong with my machine.

**Comment by Kris-B** [comment]
there seems to be an issue with the CSS file

**Comment by pointout** [comment]
It is the AddOn "Contao CMS-Backend Jumper", that destroyed the Gallery. If I deactivate it, the gallery works.

**Comment by leo-unglaub** [comment]
I am the creator of the Firefox Addon "Contao CMS-Backend Jumper". The error mentioned above has nothing todo with my extension. My extension does not inject code into the current page. Therefore i don't influence the page rendering.

Also when i open the website the gallery works fine even with my extension installed and active.

**Comment by Kris-B** [comment]
thanks for the precision @leo-unglaub !

@pointout , can you test your page with the debugger opened (F12 key) and check if there are some errors?

**Comment by pointout** [comment]
Thanks @leo-unglaub. I tested it on another PC and there the site worked also after installing the AddOn. So the Leos caching-hint sounds reasonable.

**Comment by pointout** [comment]
I first included nanogallery2 this way:
```
<link href="https://unpkg.com/nanogallery2/dist/css/nanogallery2.min.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="https://unpkg.com/nanogallery2/dist/jquery.nanogallery2.min.js"></script>
```
That worked in my FF only the first call. After reloading the page the gallery broke (That's why I thought the AddOn was the problem, because I did restart the browser for getting sure the AddOn is deactivated.)

If I include it the way it is shown on https://nanogallery2.nanostudio.org/, then it works also after reloading:
```
<link  href="https://unpkg.com/nanogallery2@2.0.0/dist/css/nanogallery2.min.css" rel="stylesheet" type="text/css">
<script  type="text/javascript" src="https://unpkg.com/nanogallery2@2.0.0/dist/jquery.nanogallery2.min.js"></script>
```

P.S.: By the way there is an overmuch closing '>' in the code on the website in 
`<script  type="text/javascript"> src="https://unpkg.com/nanogallery2@2.0.0/dist/jquery.nanogallery2.min.js"></script>`

**Comment by Kris-B** [comment]
`https://unpkg.com/nanogallery2/dist/css/nanogallery2.min.css` will redirect to the latest version of nanogallery2
so it now points to `https://unpkg.com/nanogallery2@2.0.0/dist/css/nanogallery2.min.css`

No idea why the second one works better than the first one...

PS: typo fixed, thanks!
