### ISSUE TITLE
loading gif

### ISSUE THREAD

**Issue by AlessandroZero** [nanostudio-org/nanogallery2#81]
The loading.gif is always present under the image into the lightbox..
This is not a problem if the image is a jpg (or any type of image without transparency) or have a size big enough to cover the gif...but if the image have some transparent part or is a png/gif with blank space or is very small, then the animated loading gif is visible.
Tested on v 1.4, 1.5 and now with 2.0.
Great work anyway, keep it up!

**Comment by Kris-B** [comment]
The loading.gif is defined as a background for the image and is just covered by the image. Actually, it's never hidden.

I see 4 possibilities to improve this:
- remove the loading gif
- hide the loading gif when a part of the image is loaded - but it may be hidden when only a very small part of the image is loaded
- hide the loading gif when the image is fully loaded - but the transparent issue may be visible during download
- display the loading gif and hide the image during download, and when the image is fully downloaded,
 display the image and hide the loading gif at the same time - but we'll lose progressive dispay from top to bottom 

any hint?

**Comment by AlessandroZero** [comment]
I'd choose the second option.

After all, the loading gif purpose is to let you know the loading is in progress.

If you see the image itself loading then you already know it's functioning properly, so there would no more need of the gif.

Otherwise, the third option would also be good.


I would discard the first and fourth options:

removing the gif totally would let the user uncertain about the working of the site while leave only the gif until the full loaded image would make the user misinterpreting for a hang when used for very big images or slow connections.

Just my two cents.

**Comment by kumar-parkash** [comment]
I have hidden that background image for the png type images with the following CSS:

.nGY2 img.nGY2ViewerMedia[src *=".png"] {
	background-image: none !important;
}

**Comment by Kris-B** [comment]
can you test the version in the DEV branch to see if transparency is now ok?
https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by AlessandroZero** [comment]
Hi,

this version works flawlessy.

I had another problem which seems resolved too:
with the previous version on different computers, when I load a heavy justified gallery, some thumbnails appears smaller than others (occuping the same space they would if they were the correct size). It's noticeable instantly because you can see the background showing in the remaining space occupied by the smaller thumbnail. Reloading the page instantly fixes the problem.
I don't know if it's due to computational power of the machine or anything else. I tested with different browsers on different machines (windows 7 - 8.1 - 10 and macos) all with the same connectivity (300 Mbps)...macos seems to work better.
Not a big problem to me, anyway, and as I said, this version seems to fix also this problem.

I'll make extended test and let you know the results if you're interested.

Sorry for my bad English, I hope you understood something of what I wrote :-)


Thank you for the great work!

**Comment by AlessandroZero** [comment]
Ok, 

I can confiirm that loading very heavy justified galleries on my machine, still cause the thumbnail size problem I mentioned.
Anyway this galleries have no use in the real word, with something like 500 thumbnails, and probably some other of my js files interfere too, so I think it's inevitable for me.

I see this version add some sort of zoom in of the images during lightbox, can you tell me how to disable? I'd like to keep a simple slide of the image shrinked to the monitor size (if too large).

Thank you very much

Alessandro

**Comment by AlessandroZero** [comment]
Hi, my problem are not the thumbnails.

My thumbnails are all the same height and variable width but they are justified flawlessy.

My problem is during the lightbox, after I click on a thumb.

During the lightbox "slideshow" the transition between images apply some sort of slight "zoom in" or "scale" (sorry, I' don't know the right term) while sliding from right to teh center of the screen; the previous version of nanogallery2 was a simple slide (without the zoom/scale effect).

I know, it's not very important but I'm not vedry experienced in coding so I've no idea where and what to look.



This is an example of my thumbnails pages, I've changed nothing here, the effect showed after I applied the dev release (which has fixed the problem of the loading gif):

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
</head>
<script type="text/javascript" src="js/jquery.js"></script>
<link href="css/nanogallery2.min.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="js/jquery.nanogallery2.min.js"></script>
<body>
<div data-nanogallery2='{
"thumbnailWidth": "auto",
"thumbnailHeight": "300",
"thumbnailLabel": {
"display": false
},
"locationHash": false,
"thumbnailHoverEffect2": "image_scale_1.00_1.20_1500",
"thumbnailAlignment": "justified",
"displayBreadcrumb": false,
"breadcrumbAutoHideTopLevel": false,
"breadcrumbOnlyCurrentLevel": false,
"viewerZoom": false,
"viewerToolbar": {
"display": false
}
}'>

<A HREF="../vgart/images/vsseries/1colossus.jpg" data-ngthumb="../vgart/thumbs/vsseries/1colossus_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/1ironman.jpg" data-ngthumb="../vgart/thumbs/vsseries/1ironman_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/1omegared.jpg" data-ngthumb="../vgart/thumbs/vsseries/1omegared_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/446.jpg" data-ngthumb="../vgart/thumbs/vsseries/446_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/5amingo.jpg" data-ngthumb="../vgart/thumbs/vsseries/5amingo_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/5cable.jpg" data-ngthumb="../vgart/thumbs/vsseries/5cable_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/5capcommando.jpg" data-ngthumb="../vgart/thumbs/vsseries/5capcommando_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/5drdoom.jpg" data-ngthumb="../vgart/thumbs/vsseries/5drdoom_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/5wolverine.jpg" data-ngthumb="../vgart/thumbs/vsseries/5wolverine_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/amingo.gif" data-ngthumb="../vgart/thumbs/vsseries/amingo_t.gif" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/apocolypse-k.gif" data-ngthumb="../vgart/thumbs/vsseries/apocolypse-k_t.gif" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/apocolypse-mshvs.gif" data-ngthumb="../vgart/thumbs/vsseries/apocolypse-mshvs_t.gif" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/big-rogue-mvc2.jpg" data-ngthumb="../vgart/thumbs/vsseries/big-rogue-mvc2_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/big-roll-mvc2.jpg" data-ngthumb="../vgart/thumbs/vsseries/big-roll-mvc2_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/big-strider-mvc2.jpg" data-ngthumb="../vgart/thumbs/vsseries/big-strider-mvc2_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/big-thanos-mvc2.jpg" data-ngthumb="../vgart/thumbs/vsseries/big-thanos-mvc2_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/big-warmachine-mvc2.jpg" data-ngthumb="../vgart/thumbs/vsseries/big-warmachine-mvc2_t.jpg" data-ngdesc=""></a>
<A HREF="../vgart/images/vsseries/big-wolvie-mvc2.jpg" data-ngthumb="../vgart/thumbs/vsseries/big-wolvie-mvc2_t.jpg" data-ngdesc=""></a>

</div>
</body>
</html>



Thank you

**Comment by Kris-B** [comment]
yes, there's a new zoom/scale effect in the lightbox, but it's just a test in the beta version.

but, you mentioned a thumbnail size problem: this is because you do not set the size of each thumbnail. The size is required to build the justified layout, if the size is not provided, the size will be known only after the thumbnail image is downloaded. To avoid this display issue, just set the size of each thumbnail's image.

**Comment by AlessandroZero** [comment]
Ok, got it, thank you for the reply.


Can I ask you if the zoom feature in lightbox will be deactivable?

Regarding the tumbnail size, considering the use of my site (mostly personal, as an online archive) and the size of the images (basically 90% of various size) it would require a godzillion of hours to get and configure all the size and I'm too lazy.

I'll let the machine do the work, the result of your code is still impressive.

Thank you for the kind support!

Bye
Alessandro

**Comment by Kris-B** [comment]
;-)

the zoom effect will be an option

**Comment by Kris-B** [comment]
fix released in v2.3.0

**Comment by AlessandroZero** [comment]
Thank you!

Flawless work as usual, and I love the simple lightbox transition.

Great, GREAT work!


Bye

Alessandro

**Comment by Kris-B** [comment]
;-)
