### ISSUE TITLE
 thumbnailAlbumDisplayImage in nanogallery2

### ISSUE THREAD

**Issue by JoROSU** [nanostudio-org/nanogallery2#82]
Hi, 
I used nanoGALLERY and thumbnailAlbumDisplayImage: true to open slider on gallery click.
How can I set this in nanogallery2?
Thanks!

**Comment by Kris-B** [comment]
this will be fixed in the next release

**Comment by JoROSU** [comment]
Thank you!

**Comment by Kris-B** [comment]
you can check the version available in the DEV branch: https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by JoROSU** [comment]
Thank you a lot,
Jovana

**Comment by Kris-B** [comment]
final version release: v2.1.0
