### ISSUE TITLE
Issues with Chrome

### ISSUE THREAD

**Issue by adityasodhani** [nanostudio-org/nanogallery2#84]
Hello, 

I am using a particular code in Safari as well as Chrome. It turns out that the gallery doesn't load every time I refresh my Chrome page but works flawlessly in Safari. Is anybody else experiencing this issue?

**Comment by Kris-B** [comment]
can you provide more details ? maybe also the URL of your page ?

**Comment by Kris-B** [comment]
https://stackoverflow.com/questions/48164619/chrome-browser-does-not-reload-nanogallery2-javascript-upon-refresh
