### ISSUE TITLE
Updated text on site, images no longer showing but I have no errors

### ISSUE THREAD

**Issue by MajorKeys** [nanostudio-org/nanogallery2#85]
I updated a few text on a website but the images no longer load or show. When I "inspect" or "inspect element" the website they are no errors or anything. 

I was wondering why this is? 

The issues are on the index and gallery page. I have pasted links below.

http://centuryfloorsdfw.com/index.html

http://centuryfloorsdfw.com/gallery.html

**Comment by MajorKeys** [comment]
I did and still no images show up.

**Comment by Kris-B** [comment]
nanogallery2 is not loaded in your page

please remove the line break between `<script` and ` src="js/jquery-3.1.1.min.js"</script>` and try again

**Comment by Kris-B** [comment]
any feedback?
