### ISSUE TITLE
Google Drive?

### ISSUE THREAD

**Issue by Awooooo** [nanostudio-org/nanogallery2#88]
Any chance of support for Google Drive so that we can mimic the "photostream" from Flickr?

The way things currently are, we can do Albums, but we can't do all-uploads that are just loose.

These uploads are actually syncing to a folder in Google Drive when checking the "recent" section of Drive and fiddling with "details" settings on the right. This folder can be made shareable and accessible, but there really aren't any good gallery tools out there that support it.

For example, I'm using nanogallery over here: www.axisorder.com/finalfantasy
And I'd like to use it for www.axisorder.com/history too, but obviously can't right now.

Example of such a folder shared: https://drive.google.com/drive/folders/1MMNX5fLNSemOOBvDYAuBHkfJxoaX9eQ9?usp=sharing

I found http://drivegal.com/awoo-awoo which was able to access and parse this. So I think it should be possible right?

Anyway, just thought I'd give requesting it a stab.

**Comment by Awooooo** [comment]
Just noticed Drivegal's source is also available here: https://github.com/jasongrimes/drivegal

**Comment by Kris-B** [comment]
A server-side app is required to generate the thumbnails.
You may build one yourself and add a provider add-on to nanogallery2 (like nanoPhotosProvider2 for self hosted images - https://github.com/nanostudio-org/nano_photos_provider2)
