### ISSUE TITLE
G.galleryTheme_light Thumbnail Border Color Bug?

### ISSUE THREAD

**Issue by RambosRide** [nanostudio-org/nanogallery2#89]
G.galleryTheme_light is defined having dark border color on the thumbs.

  thumbnail :             { ... borderColor: '#000'...},

This "feels" like a bug to me - I changed mine to 

  thumbnail :             { ... borderColor: '#fff'...}

**Comment by Kris-B** [comment]
Unfortunately, this is implemented like this since the initial release. Changing this value may break existing galleries.
