### ISSUE TITLE
Bug: calculation of thumbnail sizes for google photos (justified and cascading case)

### ISSUE THREAD

**Issue by alexanderhowell** [nanostudio-org/nanogallery2#9]
If one or both of the thumbnail sizes is set to auto then the code at rows 12036 - 12045 in the raw js will fail in computing the right length/width, and set one or the other to "NaN"

The code inside the function "GoogleAddOneThumbSize" is meant to catch the "auto" cases but doesn't because the variable it is passed is the result of a multiplication, and so gets the NaN. This means that the sizes don't compute all the way through and the RSS produced is broken.

**How to reproduce**
Set up with google photos as source, and set one or other thumbnail height/width to auto (i.e. choose a cascading or justified style); attempt to load page.

**How to fix this code**
The quickest way is to replace lines 12050  and 12053 in the raw. js as follows, from:
`function GoogleAddOneThumbSize(thumbSizes, v1, v2, c1, c2 ) {
      var v = Math.ceil( v2 * G.tn.scale ) + c2;
      if( v1 == 'auto' ) {
        v = Math.ceil( v2 * G.tn.scale ) + c2;
      }
      else if( v2 == 'auto' ) {
          v = Math.ceil( v1 * G.tn.scale ) + c1;
        }
        else if( v1 > v2 ) {
          v = Math.ceil( v1 * G.tn.scale ) + c1;
        }
        
      if( thumbSizes.length > 0 ) {
        thumbSizes += ',';
      }
      thumbSizes += v;
      return thumbSizes;
    }`

to

`function GoogleAddOneThumbSize(thumbSizes, v1, v2, c1, c2 ) {
      var v = Math.ceil( v2 * G.tn.scale ) + c2;
      if(isNaN(v1)) {
        v = Math.ceil( v2 * G.tn.scale ) + c2;
      }
      else if( isNaN(v2) ) {
          v = Math.ceil( v1 * G.tn.scale ) + c1;
        }
        else if( v1 > v2 ) {
          v = Math.ceil( v1 * G.tn.scale ) + c1;
        }
        
      if( thumbSizes.length > 0 ) {
        thumbSizes += ',';
      }
      thumbSizes += v;
      return thumbSizes;
    }`

I have submitted a pull request to fix this in this way

**Comment by Kris-B** [comment]
many thanks for this fix.

included in the latest release: https://github.com/nanostudio-org/nanogallery2/releases/tag/v0.9.2a
