### ISSUE TITLE
Lightboxes from builder stopped working

### ISSUE THREAD

**Issue by Awooooo** [nanostudio-org/nanogallery2#92]
We've been using code generated from the builder here: https://nanogallery2.nanostudio.org/builder.html

On our site here: www.axisorder.com/finalfantasy

Lightboxes for full sized image have stopped working? What would cause this? Instead of the lightboxes appearing, the images now just download.

**Comment by Kris-B** [comment]
you need to check `no` on option `Open Flickr to display images`

**Comment by Awooooo** [comment]
Yep that fixed it. Misunderstanding of the settings and forgetting that something had been altered compared to prior working versions.
