### ISSUE TITLE
Responsive layout

### ISSUE THREAD

**Issue by vh13294** [nanostudio-org/nanogallery2#93]
For thumbnailHeight and thumbnailWidth, we can set the breakpoint for differents screen sizes.

Could you do the same with ?
- "galleryMosaic":  [{ "w": 1, "h": 1, "c": 1, "r": 1 }, { "w": 2, "h": 2, "c": 2, "r": 1 }]
- thumbnailGutterWidth and thumbnailGutterHeight

Thanks,

**Comment by ShapesGraphicStudio** [comment]
Hi,
Mosaic view is really great, but I'm facing the same issue, as it's not quite responsive. did you find a workaround ?

**Comment by Kris-B** [comment]
maybe a little bit late...
available in v3.0.0 - https://github.com/nanostudio-org/nanogallery2/releases/tag/v3.0.0
