### ISSUE TITLE
Error retrieving Google Data

### ISSUE THREAD

**Issue by db123v** [nanostudio-org/nanogallery2#94]
I have setup nanogallery2 to fetch photos from my google photos account, however when i access my gallery page, i get the attached error.
[Fetch Photos Error.txt](https://github.com/nanostudio-org/nanogallery2/files/1709578/Fetch.Photos.Error.txt)

**Comment by Kris-B** [comment]
Did you install nanogp (https://github.com/nanostudio-org/nanogp) ?

**Comment by db123v** [comment]
Yes, i have installed as per instructions provided on https://github.com/nanostudio-org/nanogp

**Comment by Kris-B** [comment]
can you provide your full nanogaller2 settings?

**Comment by Kris-B** [comment]
```
        "userID": "11111111111111111111",
        "google2URL": "http://YOUR_WEB_SERVER/nanogp/nanogp.php",
```

You need to replace these values:
- `userID`: your own Google Photos user ID
- `google2URL`: full path to your nanogp installation

**Comment by db123v** [comment]
Thank you very much. My googl2url was misconfigured.
