### ISSUE TITLE
Not all albums will load

### ISSUE THREAD

**Issue by RodneyzPc** [nanostudio-org/nanogallery2#96]
http://www.afbawindgap.org/nanogallery2/afba_photos.html

After FTPing the pics to the Albums I created
http://www.afbawindgap.org/Srip/nanofotos1.jpg
http://www.afbawindgap.org/Srip/nanofotos2.jpg

And opening the Index Page
to verify they are there..which they are...with a Thumb
http://www.afbawindgap.org/Srip/nanofotos4.jpg
http://www.afbawindgap.org/Srip/nanofotos3.jpg

I have 2 Albums so far that
won't load and the Browser window just says what album I'm in.
"Ruthies" - Re-Building Bridges"
http://www.afbawindgap.org/Srip/nanofotos5.jpg

There were 3 Albums after I uploaded them that I would remove
1 pic at a time - refresh the thumbs until it worked - but
there are still 10 pics to go into that Album.

I was using Gallery1 but it's not as nice to look at and isn't
responsive...and my wife likes this one too. I've tried re-naming
the pictures...thinking the name was too long..that didn't
work either...some albums have 40 pictures in them...and
4 albums I can't get more than 10.
...Garden Commitee - no more than 10 - -
...Susies Sign Shop --- no more than 9---

I hate to go farther and upload more if it's
not going to work until I get these problems corrected.

Am I doing something wrong...? 
Thank You for your time,
~~~  Rodney ~~~

**Comment by Kris-B** [comment]
Hey Rodney,
I just checked your site but I could not see any issue.
If you change the content of one folder, please remove the folder _thumbnails to force re-genetaion of the thumbnails and the cached data
