### ISSUE TITLE
Albums not showing up when there are many images

### ISSUE THREAD

**Issue by jeangu2002** [nanostudio-org/nanogallery2#99]
Hello folks. I a am using nanogallery for my website. i am trying to display image albums but they seem not to appear when they contains many images( 30 image album for example).
Any idea why it is not working?

**Comment by jeangu2002** [comment]
Here is the URL: https://www.liegecitybreakers.be/fr/lcb/international/gallery

**Comment by Kris-B** [comment]
2 items have the same ID (=16): 1 album and 1 image

**Comment by Kris-B** [comment]
IDs should be unique, independantly of the item's kind

**Comment by jeangu2002** [comment]
Thanks. i didn't know
